"""BASICInterpreter mixin: core.

Core state, init, clocks, options, and shared helpers.

Auto-generated by tools/split_runtime_mixins.py — do not hand-edit bulk.
"""
# ruff: noqa: F401,F403,F405,E402,W291,W293
# Imports mirrored from monorepo runtime for method bodies.
import fnmatch
import json
import math
import random
import re
import os
import struct
import sys
import time

from ..config import DEFAULT_CONFIG, InterpreterConfig, SYSTEM_VAR_SPEC
from ..dialect_hint import DialectHint, parse_comment_dialect_line, split_dialect_hints
from ..constants import (
    CLI_EXIT_WORDS as _CLI_EXIT_WORDS,
    EXIT_HOLD_CONSOLE,
    EXPR_RESERVED_WORDS as _EXPR_RESERVED_WORDS,
    NUMERIC_BUILTIN_FUNCS as _NUMERIC_BUILTIN_FUNCS,
    NUMERIC_BUILTIN_FUNC_RE as _NUMERIC_BUILTIN_FUNC_RE,
    SAFE_EVAL_GLOBALS as _SAFE_EVAL_GLOBALS,
)
from ..expr.compile import CompiledExpr, int_slot
from ..expr.patterns import (
    RE_ARRAY_HEAD as _RE_ARRAY_HEAD,
    RE_COND_EQ as _RE_COND_EQ,
    RE_COND_NE as _RE_COND_NE,
    RE_DYNAMIC_CALL_REMAINS as _RE_DYNAMIC_CALL_REMAINS,
    RE_FILE_FUNC as _RE_FILE_FUNC,
    RE_FILE_FUNC_BBC as _RE_FILE_FUNC_BBC,
    RE_FN_CALL as _RE_FN_CALL,
    RE_FUNC_CALL as _RE_FUNC_CALL,
    RE_HAS_LETTER as _RE_HAS_LETTER,
    RE_INKEY_CALL as _RE_INKEY_CALL,
    RE_INT_DIV as _RE_INT_DIV,
    RE_MOD as _RE_MOD,
    RE_NUMERIC_FUNC_CALL as _RE_NUMERIC_FUNC_CALL,
    RE_TIME as _RE_TIME,
    RE_VAR_BASE_FULL as _RE_VAR_BASE_FULL,
    VAR_BASE_PATTERN as _VAR_BASE_PATTERN,
)

from ..format import UsingFormatter
from ..format.save_case import (
    Fold as _SaveFold,
    fold_from_save_case as _fold_from_save_case,
    format_program_line as _format_program_line_save_case,
    format_statement_part as _format_statement_part_save_case,
)
from ..repl.completion import configure_readline as _configure_repl_readline
from ..repl.help_browser import run_help_browser as _run_help_browser
from ..util import (
    basic_truth as _basic_truth,
    hard_exit as _hard_exit,
    near_equal as _near_equal,
    near_equal_sig as _near_equal_sig,
    probe_float_platform as _probe_float_platform,
)
from ..type_system import (
    ArrayStorage,
    BasicRuntimeError,
    ChainTransfer,
    DataItem,
    Dialect,
    FieldBuffer,
    FileChannel,
    FnReturn,
    CaseBlockLayout,
    CaseFrame,
    IfBlockLayout,
    IfFrame,
    ListCommand,
    LoopFrame,
    ProcReturn,
    ProgramExit,
    UserFunction,
    UserProcedure,
    VarKind,
)
from typing import Callable, Dict, List, Optional, Set, TextIO, Tuple

_SYSTEM_VAR_SPEC = SYSTEM_VAR_SPEC

       
# BBC Micro MODE specs (text grid, graphics resolution, PAR) — see bbc_modes.py.
from mini_basic.bbc_modes import bbc_mode_spec

from .helpers import (
    _get_readline_module,
    _windows_arrow_action,
    _windows_apply_arrow,
    _windows_editing_input,
    _prompt_editing_input,
    _parse_path_arg,
    _apply_pygame_display_defaults,
)

class RuntimeCoreMixin:
    """Mixin providing core-related BASICInterpreter methods."""

    def dprint(self, *args, **kwargs) -> None:
        """Debug print on every runtime mixin (Core is first in MRO).

        Same as free ``from mini_basic.util.debug import dprint`` / package
        ``from mini_basic import dprint`` — uses this interpreter's config.
        """
        from ..util.debug import dprint as _dprint
        from ..util.debug import set_active_debug_config

        set_active_debug_config(self.config)
        sep = kwargs.get('sep', ' ')
        end = kwargs.get('end', '\n')
        _dprint(*args, config=self.config, sep=sep, end=end)

    def __init__(self, config: Optional[InterpreterConfig] = None):
        self.config = config or InterpreterConfig()
        try:
            from ..util.debug import set_active_debug_config

            set_active_debug_config(self.config)
        except Exception:
            pass

        self.program: Dict[int, str] = {}
        self.line_indent: Dict[int, int] = {}
        self.labels: Dict[str, int] = {}
        self.variables: Dict[str, float] = {}
        self.int_variables: Dict[str, int] = {}
        self.str_variables: Dict[str, str] = {}
        self.stack: List[LoopFrame] = []
        self.if_stack: List[IfFrame] = []
        self.case_stack: List[CaseFrame] = []
        self._refresh_enabled = True
        self.trace_enabled = False
        self._input_active = False
        self._last_present_time = 0.0
        self._present_min_interval = 1.0 / 20.0
        self._mouse_x = 0
        self._mouse_y = 0
        self._mouse_buttons = 0
        self._bbc_custom_colours: Dict[int, Tuple[int, int, int]] = {}
        self.gosub_stack: List[Tuple[int, int]] = []
        self.resume_at: Optional[Tuple[int, int]] = None
        self.error_trap_line: int = 0
        self.error_trap_gosub: bool = False
        self._inline_error_handlers: Dict[int, List[Tuple[Optional[str], str]]] = {}
        self._on_error_skip_rest_of_line: Optional[int] = None
        self._run_error_handler_for_line: Optional[int] = None
        self._in_error_handler: bool = False
        self.on_close_action: Optional[str] = None
        # BBCSDL: ON CLOSE PROC cleanup : QUIT  — full handler text after ON CLOSE
        self._on_close_handler: Optional[str] = None
        self.error_resume_at: Optional[Tuple[int, int]] = None
        self.error_line_num: int = 0
        self.error_code_num: int = 0
        self.error_message: str = ''
        self.option_base: int = 0
        self.default_var_types: Dict[str, VarKind] = {}
        self._exec_line_nums: List[int] = []
        self._exec_stmt_count: int = 1
        self.time_value = 0.0
        self.time_set_at = 0.0
        self._init_time_clock()
        _float_platform = _probe_float_platform()
        self.machine_epsilon = _float_platform.epsilon
        self.float_decimal_digits = _float_platform.decimal_digits
        self.float_mantissa_digits = _float_platform.mantissa_digits
        self.float_radix = _float_platform.radix
        self.ieee754_binary64 = 1 if _float_platform.is_ieee754_binary64 else 0
        self.save_case = 0
        self.print_column = 0
        self.print_field_width = 10
        self.bbc_at_percent = 0
        self.bbc_page = 0x8000
        self.bbc_lomem = 0x8000
        self.bbc_himem = self.bbc_lomem + 400_000
        self.text_fg_colour: Optional[int] = None
        self.text_bg_colour: int = 0
        self._last_emitted_fg_colour: Optional[int] = None
        self.text_row = 0
        self.text_col = 0
        self.working_dir = os.path.normpath(os.getcwd())
        self._esc = '\033'
        self._if_layout_cache: Dict[int, IfBlockLayout] = {}
        self._case_layout_cache: Dict[int, CaseBlockLayout] = {}
        self._run_line_nums: List[int] = []
        self._run_line_index: Dict[int, int] = {}
        self._run_stmts: Dict[int, List[Tuple[Optional[str], str]]] = {}
        self._run_for_next: Dict[Tuple[int, str], int] = {}
        self._run_while_wend: Dict[int, int] = {}
        self._run_repeat_until: Dict[int, Tuple[int, str]] = {}
        self._var_subst_int_entries: List[Tuple[re.Pattern, str]] = []
        self._var_subst_float_entries: List[Tuple[re.Pattern, str]] = []
        self._compiled_expr_cache: Dict[Tuple[str, bool], CompiledExpr] = {}
        self._parse_command_cache: Dict[str, Tuple[str, str]] = {}
        self._ansi_fg_cache: Dict[int, str] = {}
        self._ansi_bg_cache: Dict[int, str] = {}
        self._ansi_reset_text: Optional[str] = None
        self._print_line_parts: List[str] = []
        self._console_write_buffer: List[str] = []
        self._program_stdout: Optional[TextIO] = None
        self._ansi_console_enabled = False
        self._ansi_console_tried = False
        self._saved_console_mode: Optional[int] = None  # stdout
        self._saved_console_mode_in: Optional[int] = None  # stdin
        self.file_channels: Dict[int, FileChannel] = {}
        self.field_buffers: Dict[int, FieldBuffer] = {}
        self._next_file_channel = 1
        self.stopped = False
        self.stop_resume_at: Optional[Tuple[int, int]] = None
        self.loaded_filename: Optional[str] = None
        self._program_source_numbered: Optional[bool] = None
        self._display = None
        self._display_live = False
        self._run_interrupt_watch = False
        self._text_viewport = None
        self._graphics_viewport = None
        self._graphics_mode = 8
        self.array_storage: Dict[Tuple[str, VarKind], ArrayStorage] = {}
        self.struct_defs: Dict[str, Dict[str, VarKind]] = {}
        self.struct_members: Dict[str, object] = {}  # dotted keys e.g. 'pt.x%' -> value (suffix in key for uniqueness)
        self.data_items: List[DataItem] = []
        self.data_line_starts: Dict[int, int] = {}
        self._data_lines_ordered: List[int] = []
        self._data_locations: List[Tuple[int, int, int]] = []
        self.data_pointer: int = 0
        self.user_functions: Dict[str, UserFunction] = {}
        self.user_procedures: Dict[str, UserProcedure] = {}
        self.proc_stack: List[List[Tuple[str, VarKind, object, bool]]] = []
        # Pygame stubs for BBCSDL gfxlib etc.
        self._gfx_next_texture_id: int = 1
        self._gfx_textures: dict = {}
        self._proc_skip_lines: Set[int] = set()
        self._rnd_last: float = 0.0
        self.program_args: List[str] = []
        self._fn_skip_lines: Set[int] = set()
        self._in_fn_body = False
        self._fn_local_error_return: Optional[str] = None
        self._active_fn: Optional[UserFunction] = None
        self._fn_direct_eval = False
        self._array_aliases: Dict[Tuple[str, VarKind], Tuple[str, VarKind]] = {}
        self._local_save_stack: List[List[Tuple[str, object]]] = []
        self._in_proc_body = False
        self._definitions_dirty = True
        self._active_line_num: int = -1
        self._active_stmt_index: int = 0
        self._active_statement: str = ''
        self._active_stmt_parts: Optional[List[Tuple[Optional[str], str]]] = None

    def _terminal_tee_enabled(self) -> bool:
        return bool(self.config.tee_terminal) and self._display_enabled()

    def _tee_terminal_backspace(self) -> None:
        if self._program_stdout is not None:
            return
        out = sys.stdout
        out.write('\b \b')
        out.flush()

    def _tee_apply_terminal_char(
        self,
        buffer: List[str],
        code: str,
        limit: int,
    ) -> bool:
        if code in ('\r', '\n'):
            self._tee_finish_input_line()
            return True
        if code == '\x03':
            raise KeyboardInterrupt
        if code in ('\x08', '\x7f'):
            if buffer:
                buffer.pop()
                self._tee_emit_input_backspace()
            return False
        if code in ('\x00', '\xe0'):
            if sys.platform == 'win32':
                import msvcrt
                msvcrt.getwch()
            return False
        if code.isprintable() and len(buffer) < limit:
            buffer.append(code)
            self._tee_emit_input_char(code)
        return False

    def _ensure_ansi_console(self) -> None:
        if self._ansi_console_tried:
            return
        self._ansi_console_tried = True
        if self._program_stdout is not None:
            self._ansi_console_enabled = False
            return
        for stream in (sys.stdout, sys.stderr):
            reconfigure = getattr(stream, 'reconfigure', None)
            if callable(reconfigure):
                try:
                    reconfigure(write_through=True)
                except Exception:
                    pass
        if sys.platform != 'win32':
            self._ansi_console_enabled = True
        else:
            try:
                import ctypes
                kernel32 = ctypes.windll.kernel32
                # stdout: enable VT processing so FG$/ANSI colours work
                handle_out = kernel32.GetStdHandle(-11)  # STD_OUTPUT_HANDLE
                mode_out = ctypes.c_ulong()
                enable_vt = 0x0004  # ENABLE_VIRTUAL_TERMINAL_PROCESSING
                if kernel32.GetConsoleMode(handle_out, ctypes.byref(mode_out)):
                    self._saved_console_mode = mode_out.value
                    if kernel32.SetConsoleMode(handle_out, mode_out.value | enable_vt):
                        self._ansi_console_enabled = True
                # stdin: save so we can restore line/echo/mouse flags after RUN
                handle_in = kernel32.GetStdHandle(-10)  # STD_INPUT_HANDLE
                mode_in = ctypes.c_ulong()
                if kernel32.GetConsoleMode(handle_in, ctypes.byref(mode_in)):
                    self._saved_console_mode_in = mode_in.value
            except Exception:
                self._ansi_console_enabled = False

        # Never enter the alternate screen here. Streaming PRINT uses the
        # normal scrollback. Grid mode (goto) may enter alt-screen later;
        # _restore_console always leaves it and resets terminal modes so
        # PowerShell scrollback / PSReadLine keep working after exit.

    def _substitute_bbc_memory_vars(self, expr: str) -> str:
        for name, attr in (
            ('HIMEM', 'bbc_himem'),
            ('LOMEM', 'bbc_lomem'),
            ('PAGE', 'bbc_page'),
        ):
            expr = re.sub(
                rf'(?<![A-Za-z0-9_]){name}(?![A-Za-z0-9_$])',
                str(getattr(self, attr)),
                expr,
                flags=re.IGNORECASE,
            )
        return expr

    def _bbcsdl_vdu_word(self, offset: int) -> int:
        """BBCSDL ``@vdu%!offset`` system structure (common piechart/aspect fields).

        208 / 212 = graphics width / height in *pixels* (wiki). With OS scale 2
        those values sit at the screen centre in OS coordinates — piechart uses
        them as Cx%/Cy%. 220 ≈ character height in OS units.
        """
        width = int(self.config.graphics_width or 640)
        height = int(self.config.graphics_height or 512)
        y_scale = 2
        try:
            from ..bbc_modes import bbc_os_scales

            _xs, y_scale = bbc_os_scales(width, height)
        except Exception:
            pass
        cell_h = 8
        if self._display_enabled() and hasattr(self._display, 'cell_height'):
            cell_h = int(getattr(self._display, 'cell_height', 8) or 8)
        table = {
            208: width,
            212: height,
            220: cell_h * max(1, y_scale),
        }
        return int(table.get(int(offset), 0))

    def _substitute_bbcsdl_special_vars(self, expr: str) -> str:
        width = self.config.graphics_width or 1280
        height = self.config.graphics_height or 1024
        # @vdu%!n indirection before bare @vdu%
        def _vdu_ind(match: re.Match) -> str:
            return str(self._bbcsdl_vdu_word(int(match.group(1))))

        # Allow spaces around % / ! so broken unglue forms like ``@VDU %!220``
        # still resolve (piechart label MOVE).
        expr = re.sub(
            r'(?<![A-Za-z0-9_])@vdu\s*%\s*!\s*(\d+)',
            _vdu_ind,
            expr,
            flags=re.IGNORECASE,
        )
        replacements = {
            '@platform%': '64' if sys.maxsize > 2 ** 32 else '0',
            '@hwnd%': '1',
            '@memhdc%': '1',
            '@ispal%': '0',
            '@vdu%': '0',
            '@vdu.tr%': str(width),
            '@vdu.tb%': str(height),
            '@size.x%': str(width),
            '@size.y%': str(height),
        }
        for token, value in replacements.items():
            expr = re.sub(
                rf'(?<![A-Za-z0-9_]){re.escape(token)}',
                value,
                expr,
                flags=re.IGNORECASE,
            )
        return expr

    def _split_at_depth(
        self,
        text: str,
        delim: str,
        *,
        skip_empty: bool = False,
        preserve_trailing: bool = False,
    ) -> List[str]:
        """Split text by delimiter at depth 0, respecting strings and parentheses."""

        def _normalize_part(raw: str) -> str:
            return raw.lstrip() if preserve_trailing else raw.strip()
        parts: List[str] = []
        current: List[str] = []
        depth = 0
        in_string = False
        i = 0
        n = len(text)

        while i < n:
            ch = text[i]
            if ch == '"':
                current.append(ch)
                if i + 1 < n and text[i + 1] == '"':
                    # escaped "" (either inside open string or empty literal handling)
                    i += 1
                    current.append(text[i])
                    # do not flip in_string for escaped pair; it stays as-is or will be handled by next "
                else:
                    in_string = not in_string
            elif not in_string:
                if ch == '(':
                    depth += 1
                    current.append(ch)
                elif ch == ')':
                    depth = max(0, depth - 1)
                    current.append(ch)
                elif ch == '{':
                    depth += 1
                    current.append(ch)
                elif ch == '}':
                    depth = max(0, depth - 1)
                    current.append(ch)
                elif ch == delim and depth == 0:
                    part = _normalize_part(''.join(current))
                    if not skip_empty or part:
                        parts.append(part)
                    current = []
                else:
                    current.append(ch)
            else:
                current.append(ch)
            i += 1

        part = _normalize_part(''.join(current))
        if not skip_empty or part:
            parts.append(part)
        return parts

    def _split_first_at_depth(self, text: str, delim: str) -> Tuple[str, str]:
        """Split at the first delimiter at depth 0. Returns (before, after)."""
        if not text:
            return '', ''

        depth = 0
        in_string = False
        i = 0
        n = len(text)

        while i < n:
            ch = text[i]
            if ch == '"':
                in_string = not in_string
                if in_string and i + 1 < n and text[i + 1] == '"':
                    i += 1
            elif not in_string:
                if ch == '(':
                    depth += 1
                elif ch == ')':
                    depth = max(0, depth - 1)
                elif ch == delim and depth == 0:
                    return text[:i].strip(), text[i + 1:].strip()
            i += 1

        return text.strip(), ''

    def _split_args(self, arg: str) -> List[str]:
        return self._split_at_depth(arg, ',')

    def _split_colon_statements(self, line: str) -> List[str]:
        stripped = line.strip()
        if stripped.startswith("'") or stripped.upper().startswith("REM"):
            return [stripped]
        # BBC event handlers keep their full colon tail:
        #   ON CLOSE PROC cleanup : QUIT
        #   ON ERROR PROC cleanup : IF ERR=17 … ELSE …
        # (keywords.txt: ON CLOSE [LOCAL] <stmt>{:<stmt>}[:RETURN])
        if re.match(
            r'^ON\s+(CLOSE|ERROR|MOUSE|MOVE|SYS|TIME)\b',
            stripped,
            re.IGNORECASE,
        ):
            return [stripped]
        parts: List[str] = []
        current: List[str] = []
        in_string = False
        after_then = False
        index = 0
        while index < len(line):
            ch = line[index]
            if ch == '"':
                in_string = not in_string
                current.append(ch)
                index += 1
                continue
            if (
                not in_string
                and not after_then
                and line[index:index + 4].upper() == 'THEN'
                and (index == 0 or not line[index - 1].isalnum())
                and (index + 4 >= len(line) or not line[index + 4].isalnum())
            ):
                after_then = True
                current.append(line[index:index + 4])
                index += 4
                continue
            if ch == ':' and not in_string:
                part = ''.join(current).strip()
                if part.upper().startswith('REM') or part.lstrip().startswith("'"):
                    current.append(ch)
                    index += 1
                    continue
                if after_then:
                    current.append(ch)
                    index += 1
                    continue
                if part:
                    head_cmd, _ = self._parse_command(part)
                    if head_cmd in ('WHEN', 'OTHERWISE'):
                        current.append(ch)
                        index += 1
                        continue
                head_cmd, _ = self._parse_command(part)
                if (
                    part
                    and not head_cmd  # if it parses as a command (even glued like printj), : is separator not label
                    and self._RE_VAR_BASE_FULL.fullmatch(part)
                    and not self._is_statement_keyword(part)
                ):
                    current.append(ch)
                    index += 1
                    continue
                if part:
                    parts.append(part)
                current = []
                after_then = False
                index += 1
                continue
            current.append(ch)
            index += 1
        part = ''.join(current).strip()
        if part:
            parts.append(part)
        return parts

    def _split_statement_indent(self, statement: str) -> Tuple[int, str]:
        match = re.match(r'^([ \t]*)(.*)$', statement)
        if not match:
            return 0, statement.strip()
        return self._indent_width(match.group(1)), match.group(2).strip()

    def _compute_stop_resume_at(
        self,
        line_num: int,
        stmt_index: int,
        stmt_count: int,
        line_nums: List[int],
    ) -> Optional[Tuple[int, int]]:
        if stmt_index + 1 < stmt_count:
            return (line_num, stmt_index + 1)
        try:
            line_index = line_nums.index(line_num)
        except ValueError:
            return None
        if line_index + 1 >= len(line_nums):
            return None
        return (line_nums[line_index + 1], 0)

    def _map_renumber_line_ref(self, token: str, mapping: Dict[int, int]) -> str:
        token = token.strip()
        if not re.fullmatch(r'\d+', token):
            return token
        if token == '0':
            return token
        old = int(token)
        return str(mapping.get(old, old))

    def _invalidate_run_prepare_caches(self) -> None:
        self._run_stmts.clear()
        self._run_for_next.clear()
        self._run_while_wend.clear()
        self._run_repeat_until.clear()
        self._var_subst_int_entries.clear()
        self._var_subst_float_entries.clear()
        self._compiled_expr_cache.clear()

    def _bigint_enabled(self) -> bool:
        return bool(self.config.bigint_enabled)

    def _register_numeric_var(self, base: str, kind: VarKind) -> None:
        # BBCSDL 64-bit ints use storage keys like 'a%%' (suffix included).
        is_i64 = base.endswith('%%')
        name_root = base[:-2] if is_i64 else base
        sig_len = self._var_significant_length()
        if sig_len > 0:
            # for limited sig, the pattern should match any longer name that
            # normalizes to this base (e.g. ABCD normalizes to AB)
            match_pat = r'\b' + re.escape(name_root) + r'[A-Za-z0-9_]*\b(?![%$!#])'
        else:
            match_pat = r'\b' + re.escape(name_root) + r'\b(?![%$!#])'
        if kind == 'int':
            existing_patterns = {
                pattern.pattern
                for pattern, var in self._var_subst_int_entries
                if var == base
            }
            id_flags = self._identifier_re_flags()
            if is_i64:
                # Match a%% before a% (longer suffix first via sort by key length).
                patterns = [
                    re.compile(
                        r'\b' + re.escape(name_root) + r'\s*%%(?!\d)(?!\()',
                        id_flags,
                    )
                ]
            else:
                # (?!%) so a%% is not partially matched as a% + %.
                # (?<![@A-Za-z0-9_]) not bare \b: word-boundary after @ would
                # match ``vdu%`` inside BBCSDL ``@vdu%!220`` (piechart MOVE).
                patterns = [
                    re.compile(
                        r'(?<![@A-Za-z0-9_])'
                        + re.escape(name_root)
                        + r'\s*%(?!%)(?!\d)(?!\()',
                        id_flags,
                    )
                ]
                if name_root and self.default_var_types.get(name_root[0].upper()) == 'int':
                    patterns.append(re.compile(match_pat, id_flags))
            for pattern in patterns:
                if pattern.pattern not in existing_patterns:
                    self._var_subst_int_entries.append((pattern, base))
            # Longer keys (a%%) before shorter (a) so substitution order is safe.
            self._var_subst_int_entries.sort(key=lambda item: len(item[1]), reverse=True)
            return
        if kind == 'float':
            if any(var == base for _, var in self._var_subst_float_entries):
                return
            self._var_subst_float_entries.append(
                (
                    re.compile(match_pat, self._identifier_re_flags()),
                    base,
                )
            )
            self._var_subst_float_entries.sort(key=lambda item: len(item[1]), reverse=True)

    @staticmethod
    def _int_slot(name: str) -> str:
        return int_slot(name)

    def _replace_int_vars_for_compile(self, expr: str) -> Tuple[str, Tuple[str, ...]]:
        int_vars: List[str] = []

        id_flags = self._identifier_re_flags()

        def repl_percent(match: re.Match) -> str:
            name = self._normalize_identifier(match.group(1))
            if name not in int_vars:
                int_vars.append(name)
            return self._int_slot(name)

        expr = re.sub(
            rf'\b({self._VAR_BASE_PATTERN})%',
            repl_percent,
            expr,
            flags=id_flags,
        )

        def repl_bare(match: re.Match) -> str:
            name = self._normalize_identifier(match.group(1))
            if name.upper() in _EXPR_RESERVED_WORDS:
                return match.group(0)
            if self.default_var_types.get(name[0].upper()) != 'int':
                return match.group(0)
            if name not in int_vars:
                int_vars.append(name)
            return self._int_slot(name)

        expr = re.sub(
            rf'\b({self._VAR_BASE_PATTERN})\b(?![%$!#])',
            repl_bare,
            expr,
            flags=id_flags,
        )
        return expr, tuple(int_vars)

    def _extract_float_vars_for_compile(self, expr: str) -> Tuple[str, ...]:
        float_vars: List[str] = []
        for match in re.finditer(
            rf'\b({self._VAR_BASE_PATTERN})\b',
            expr,
            flags=self._identifier_re_flags(),
        ):
            name = self._normalize_identifier(match.group(1))
            if name.startswith('__ib_') and name.endswith('__'):
                continue
            if name == '__basic_time__':
                continue
            if name.upper() in _EXPR_RESERVED_WORDS:
                continue
            if name not in float_vars:
                float_vars.append(name)
        return tuple(float_vars)

    def _is_if_line_jump_target(self, then_code: str) -> bool:
        token = then_code.strip()
        if re.fullmatch(r'\d+', token):
            return True
        return self._normalize_identifier(token) in self.labels

    def resolve_jump_target(self, token: str) -> int:
        token = token.strip()
        if re.fullmatch(r'\d+', token):
            return int(token)
        key = self._normalize_identifier(token)
        if key in self.labels:
            return self.labels[key]
        raise ValueError(f'unknown line or label: {token}')

    def _branch_code_looks_like_line_jump(self, code: str) -> bool:
        code = code.strip()
        if not code:
            return False
        if re.fullmatch(r'\d+', code):
            return True
        if self._looks_like_statement(code):
            return False
        return self._normalize_identifier(code) in self.labels

    def _maybe_auto_enable_pygame_now(self, *, announce: bool = False) -> None:
        """Enable pygame when a graphics statement runs (MODE/GCOL/PLOT/...)."""
        if self.config.display_locked:
            return
        if self.config.dialect not in self._GRAPHICS_DIALECTS:
            return
        if self._display_backend_name() != 'terminal':
            return
        self._enable_pygame_display(announce=announce)

    def _check_user_interrupt(self) -> None:
        """Abort RUN if Ctrl+C or ESC was pressed in the launching terminal."""
        if not getattr(self, '_run_interrupt_watch', False):
            return
        from mini_basic.util.session import terminal_interrupt_pending

        kind = terminal_interrupt_pending()
        if kind is None:
            return
        raise KeyboardInterrupt

    def _maybe_auto_enable_pygame_from_text(
        self,
        text: str,
        *,
        announce: bool = True,
    ) -> None:
        """REPL/immediate: enable pygame when a line uses graphics or BBC display cmds."""
        statement = text.strip()
        if not statement:
            return
        self._maybe_auto_enable_pygame_display([(0, statement, 0)], announce=announce)

    def _announce_bbc_sdl_keyword_hints(
        self,
        parsed_lines: List[Tuple[int, str, int]],
    ) -> None:
        """Portability notes for BBC BASIC for SDL 2.0 keyword spelling.

        mini_basic accepts WEND, ENDWHILE, END WHILE, BREAK, etc. These notes
        only matter if you will also run the program under BBCSDL.
        """
        if self.config.dialect != 'bbc':
            return
        legacy: List[str] = []
        for line_num, statement, _ in parsed_lines:
            upper = statement.upper()
            if re.search(r'\bEND\s+IF\b', upper):
                legacy.append(
                    f'line {line_num}: for BBCSDL write ENDIF '
                    f'(not "END IF"); mini_basic accepts both'
                )
            if re.search(r'\bEND\s+WHILE\b', upper):
                legacy.append(
                    f'line {line_num}: for BBCSDL write ENDWHILE '
                    f'(not "END WHILE"); mini_basic accepts both'
                )
            if re.search(r'\bWEND\b', upper) and 'ENDWHILE' not in upper:
                legacy.append(
                    f'line {line_num}: for BBCSDL prefer ENDWHILE '
                    f'(SDL rejects WEND); mini_basic accepts WEND and ENDWHILE'
                )
            if re.search(r'\bBREAK\b', upper):
                legacy.append(
                    f'line {line_num}: for BBCSDL use EXIT FOR / EXIT WHILE / '
                    f'EXIT REPEAT (not BREAK); mini_basic accepts BREAK'
                )
        if not legacy:
            return
        print(
            'Note: BBCSDL portability (this program still runs here as written):'
        )
        for hint in legacy[:4]:
            print(f'  {hint}')
        if len(legacy) > 4:
            print(f'  …and {len(legacy) - 4} more')

    def _refresh_defint_bare_subst_patterns(self) -> None:
        """DEFINT makes bare A..Z names alias the same integer as A%..Z%."""
        id_flags = self._identifier_re_flags()
        existing = {
            (pattern.pattern, var)
            for pattern, var in self._var_subst_int_entries
        }
        for letter, kind in self.default_var_types.items():
            if kind != 'int' or len(letter) != 1:
                continue
            pattern = re.compile(
                r'\b' + re.escape(letter) + r'\b(?![%$!#])',
                id_flags,
            )
            key = (pattern.pattern, letter)
            if key not in existing:
                self._var_subst_int_entries.append((pattern, letter))
        self._var_subst_int_entries.sort(key=lambda item: len(item[1]), reverse=True)

    @staticmethod
    def _is_rem_only_statement(rest: str) -> bool:
        return bool(re.match(r'^REM(?:\s|$)', rest.strip(), re.IGNORECASE))

    def _unknown_statement_message(self, line: str) -> str:
        keyword = self._statement_keyword(line)
        if keyword in self._UNIMPLEMENTED_COMMANDS:
            detail = self._UNIMPLEMENTED_COMMANDS[keyword]
            return f'? Unimplemented: {detail}'
        # Crunched BBC forms (PRINTTAB, DEFPROC…) only expand in --dialect bbc.
        if (
            getattr(self.config, 'dialect', None) != 'bbc'
            and re.search(
                r'\b(PRINTTAB|PRINTSPC|PRINTCHR\$|DEFPROC|DEFPROC\w|'
                r'ENDWHILE|ENDCASE|ENDIF|PROCPUT|PROC\w)\b',
                line,
                re.IGNORECASE,
            )
        ):
            hint = keyword or line.strip().split()[0] if line.strip() else 'statement'
            return (
                f'? Unknown statement: {hint}  '
                f'(BBC-style glued form? try: --dialect bbc)'
            )
        if keyword:
            return f'? Unknown statement: {keyword}'
        preview = line.strip()
        if len(preview) > 48:
            preview = preview[:45] + '...'
        return f'? Syntax error: `{preview}`'

    def _is_structured_if(self, rest: str) -> bool:
        """True when rest is ``cond THEN`` with nothing after THEN (block IF / ENDIF)."""
        text = rest.strip()
        then_at = self._find_then_keyword(text)
        if then_at is None:
            return False
        return not text[then_at + 4:].strip()

    def _split_if_else_parts(self, rest: str) -> Tuple[str, Optional[str]]:
        parts: List[str] = []
        current: List[str] = []
        in_string = False
        depth = 0
        index = 0
        text = rest.strip()
        while index < len(text):
            ch = text[index]
            if ch == '"':
                in_string = not in_string
                current.append(ch)
                index += 1
                continue
            if not in_string and depth == 0 and text[index:index + 4].upper() == 'ELSE':
                before = text[max(0, index - 1):index]
                after = text[index + 4:index + 5]
                if (not before or not before[-1].isalnum()) and (not after or not after.isalnum()):
                    parts.append(''.join(current).strip())
                    current = []
                    index += 4
                    continue
            if ch == '(' and not in_string:
                depth += 1
            elif ch == ')' and not in_string:
                depth -= 1
            current.append(ch)
            index += 1
        parts.append(''.join(current).strip())
        if len(parts) == 1:
            return parts[0], None
        if len(parts) == 2:
            return parts[0], parts[1]
        raise ValueError('invalid IF syntax')

    def _extract_branch_condition(self, rest: str) -> str:
        text = rest.strip()
        then_at = self._find_then_keyword(text)
        if then_at is None or text[then_at + 4:].strip():
            raise ValueError('expected THEN at end of line')
        cond = text[:then_at].strip()
        if not cond:
            raise ValueError('expected THEN at end of line')
        return cond

    def _begin_if_branch(self, layout: IfBlockLayout, branch_index: int, condition: Optional[str]) -> Optional[int]:
        if not self.if_stack:
            self._runtime_error('? IF error', self._active_line_num or 0, 0)
            return None
        frame = self.if_stack[-1]
        if frame.branch_taken:
            return layout.endif_line
        if condition is None:
            frame.branch_taken = True
            return None
        if self._eval_condition(condition):
            frame.branch_taken = True
            return None
        return self._next_if_branch_line(layout, branch_index)

    def _is_case_of_header(self, rest: str) -> bool:
        return bool(re.match(r'^.+?\s+OF\s*$', rest.strip(), re.IGNORECASE))

    def _split_when_spec_and_inline(
        self,
        rest: str,
        *,
        case_true: bool = False,
    ) -> Tuple[str, Optional[str]]:
        text = rest.strip()
        if not text:
            raise ValueError('empty WHEN')
        if case_true:
            # Prefer BBC ``WHEN cond : body`` (colon at depth 0), but if the
            # text before the first colon already contains an assignment
            # (``WHEN R%<=0.5 A=1: B=2``), body starts at that assign — not at
            # the colon (which only separates multi-statement body).
            head, tail = self._split_first_at_depth(text, ':')
            assign_in_head = re.search(
                r'\s+([A-Za-z][A-Za-z0-9_%$]*)\s*=',
                head if head else text,
            )
            if assign_in_head:
                spec = text[: assign_in_head.start()].strip().rstrip(':').strip()
                inline = text[assign_in_head.start() :].strip()
                if spec:
                    return spec, inline or None
            if tail:
                return head, tail
            assign = re.search(
                r'\s+([A-Za-z][A-Za-z0-9_%$]*)\s*=',
                text,
            )
            if assign:
                spec = text[: assign.start()].strip().rstrip(':').strip()
                inline = text[assign.start() :].strip()
                if spec:
                    return spec, inline or None
            return text, None
        spec, inline = self._split_first_at_depth(text, ':')
        if not spec:
            raise ValueError('empty WHEN')
        return spec, inline or None

    def _select_case_branch(self, layout: CaseBlockLayout) -> Optional[int]:
        case_true = bool(
            layout.case_expr
            and re.fullmatch(r'TRUE', layout.case_expr.strip(), re.IGNORECASE),
        )
        if case_true:
            case_value: object = True
        else:
            try:
                case_value = self._eval_numeric(layout.case_expr or '0')
            except Exception as exc:
                self._emit_error(self._error_message('? CASE error', exc))
                return layout.otherwise_index
        for index, spec in enumerate(layout.branch_specs):
            if layout.otherwise_index is not None and index == layout.otherwise_index:
                continue
            if self._match_when_spec(case_value, spec, case_true=case_true):
                return index
        return layout.otherwise_index

    def _begin_case_branch(
        self,
        layout: CaseBlockLayout,
        branch_index: int,
        *,
        line_num: int,
        line_nums: List[int],
    ) -> Optional[int]:
        if not self.case_stack:
            self._emit_error('? CASE error')
            return None
        frame = self.case_stack[-1]
        if frame.branch_finished:
            return layout.exit_line
        if frame.branch_index is not None and branch_index != frame.branch_index:
            if branch_index > frame.branch_index:
                return layout.exit_line
            return self._next_case_branch_line(layout, branch_index)
        inline = layout.branch_inline[branch_index]
        if inline:
            frame.branch_finished = True
            result = self._execute_inline_statements(inline, line_num, line_nums)
            return layout.exit_line if result is None else result
        entry_line = self._case_branch_entry_line(layout, branch_index)
        if entry_line == line_num:
            entry_idx = self._line_index(entry_line, line_nums)
            if entry_idx + 1 < len(line_nums):
                return line_nums[entry_idx + 1]
            return layout.exit_line
        return entry_line

    def _decode_bbc_quoted_string(self, inner: str) -> str:
        out: List[str] = []
        index = 0
        while index < len(inner):
            ch = inner[index]
            if ch == '"':
                if index + 1 < len(inner) and inner[index + 1] == '"':
                    out.append('"')
                    index += 2
                    continue
                raise ValueError('expected string literal')
            out.append(ch)
            index += 1
        return ''.join(out)

    def _decode_string_literal(self, expr: str) -> str:
        expr = expr.strip()
        if len(expr) < 2 or expr[0] != '"' or expr[-1] != '"':
            raise ValueError('expected string literal')
        try:
            return json.loads(expr)
        except json.JSONDecodeError:
            return self._decode_bbc_quoted_string(expr[1:-1])

    def _decode_bbc_adjacent_string_literals(self, text: str) -> str:
        """Decode BBC chained literals: ``"one"'"two"`` → ``onetwo``."""
        text = text.strip()
        parts: List[str] = []
        index = 0
        while index < len(text):
            while index < len(text) and text[index].isspace():
                index += 1
            if index >= len(text):
                break
            if text[index] != '"':
                raise ValueError('expected string literal')
            end = index + 1
            while end < len(text) and text[end] != '"':
                end += 1
            if end >= len(text):
                raise ValueError('unterminated string literal')
            parts.append(self._decode_string_literal(text[index:end + 1]))
            index = end + 1
            while index < len(text) and text[index].isspace():
                index += 1
            if index < len(text) and text[index] == "'":
                peek = index + 1
                while peek < len(text) and text[peek].isspace():
                    peek += 1
                if peek < len(text) and text[peek] == '"':
                    index += 1
                    continue
            if index < len(text) and text[index] == '"':
                continue
            break
        if not parts:
            raise ValueError('expected string literal')
        return ''.join(parts)

    def _split_bbc_juxtaposed_string_parts(self, expr: str) -> List[str]:
        """Split BBC string juxtaposition: ``"Hi"STR$(n)`` or ``"a""b"``."""
        expr = expr.strip()
        parts: List[str] = []
        index = 0
        while index < len(expr):
            while index < len(expr) and expr[index].isspace():
                index += 1
            if index >= len(expr):
                break
            if expr[index] == '"':
                start = index
                while True:
                    if index >= len(expr) or expr[index] != '"':
                        break
                    end = index + 1
                    while end < len(expr) and expr[end] != '"':
                        end += 1
                    if end >= len(expr):
                        raise ValueError('unterminated string literal')
                    index = end + 1
                    while index < len(expr) and expr[index].isspace():
                        index += 1
                    if index < len(expr) and expr[index] == "'":
                        peek = index + 1
                        while peek < len(expr) and expr[peek].isspace():
                            peek += 1
                        if peek < len(expr) and expr[peek] == '"':
                            index += 1
                            continue
                    if index < len(expr) and expr[index] == '"':
                        continue
                    break
                parts.append(expr[start:index].strip())
                continue
            start = index
            depth = 0
            while index < len(expr):
                ch = expr[index]
                if ch == '"' and depth == 0:
                    break
                if ch == '(':
                    depth += 1
                elif ch == ')':
                    depth = max(0, depth - 1)
                elif ch == '+' and depth == 0:
                    break
                index += 1
            part = expr[start:index].strip()
            if part:
                parts.append(part)
        return parts or [expr]

    def _resolve_juxtaposed_string_part(self, part: str) -> str:
        part = part.strip()
        if part.startswith('"'):
            return self._decode_bbc_adjacent_string_literals(part)
        return self.eval_print_value(self._expand_dynamic_calls(part))

    def _split_string_concat(self, expr: str) -> List[str]:
        parts = self._split_at_depth(expr, '+', skip_empty=True)
        return parts or ['']

    def _resolve_string_atom(self, expr: str) -> str:
        expr = expr.strip()
        if expr.startswith('"'):
            return self._decode_bbc_adjacent_string_literals(expr)
        return self._resolve_string_value(expr)

    def _resolve_string_value(self, expr: str) -> str:
        expr = expr.strip()
        if self._looks_like_full_string_expr(expr):
            return self._eval_string_expr(expr)
        expr = self._expand_dynamic_calls(expr)
        upper = expr.upper()
        if upper == 'REPORT$':
            return self.error_message
        if upper == '@DIR$':
            return self._bbc_at_dir()
        if upper == '@LIB$':
            return self._bbc_at_lib()
        if upper == '@USR$':
            return self._bbc_at_usr()
        if upper == '@TMP$':
            return self._bbc_at_tmp()
        if upper == 'TIME$':
            return self._time_string()
        if self._expr_has_array_ref(expr):
            expr = self._substitute_array_references(expr)
            if expr.startswith('"'):
                return self._decode_bbc_adjacent_string_literals(expr)
        if expr.startswith('"'):
            return self._decode_bbc_adjacent_string_literals(expr)
        parsed = self._parse_array_lvalue(expr)
        if parsed is not None:
            base, kind, indices_expr = parsed
            if kind != 'str':
                raise ValueError('expected string value')
            return str(self._array_get(base, kind, self._eval_array_indices(indices_expr)))
        if re.fullmatch(r'INKEY\$', expr, re.IGNORECASE):
            return self._inkey_value()
        if re.fullmatch(r'GET\$', expr, re.IGNORECASE):
            code = self._read_get_char()
            return chr(code & 0xFF) if code else ''
        match = re.match(rf'^({self._VAR_BASE_PATTERN})\$$', expr)
        if match:
            return self.str_variables.get(
                self._normalize_identifier(match.group(1)),
                '',
            )
        # BBCSDL struct string member e.g. obj.name$   (full key 'obj.name$' in struct_members)
        dmatch = re.match(r'^(.+\..+)\$$', expr)
        if dmatch:
            key = dmatch.group(1) + '$'
            if key in self.struct_members:
                return str(self.struct_members[key])
            # also try without forcing if parse gave it
            if expr in self.struct_members:
                return str(self.struct_members[expr])
        raise ValueError(f"expected string value, got {expr}")

    def _ansi_sgr(self, *codes: int) -> str:
        return self._esc + '[' + ';'.join(str(int(c)) for c in codes) + 'm'

    def _looks_like_statement(self, text: str) -> bool:
        text = text.strip()
        if not text:
            return False
        cmd, _ = self._parse_command(text)
        if cmd:
            return True
        # Simple / compound assignment (same maximal-LHS rules as assign parse).
        # ``aand=0`` is a normal assignment, not ``a`` AND= 0.
        if '=' not in text:
            return False
        try:
            lhs, op, _rhs = self._parse_assignment_statement(text)
        except ValueError:
            return False
        if op != '=':
            self.dprint('[COMPOUND]', repr(text), repr(lhs), repr(op))
        if re.fullmatch(r'(OR|AND|EOR|XOR|DIV|MOD|NOT)', lhs, re.IGNORECASE):
            return False
        if self._parse_array_lvalue(lhs) is not None:
            return True
        if re.match(
            rf'^({self._VAR_BASE_PATTERN})([%$!#&]?)$',
            lhs,
            flags=self._identifier_re_flags(),
        ):
            return True
        return False

    def _classify_compact_if_branch(self, code: str, line_num: int) -> str:
        """Classify compact-IF branch code as statement, goto, or invalid."""
        del line_num  # goto validity depends on program/labels, not caller line
        code = code.strip()
        if not code:
            return 'empty'  # IF cond THEN  (no-op true branch)
        if self._in_fn_body and re.match(r'^=\s*.+', code):
            return 'statement'
        if self._looks_like_statement(code):
            return 'statement'
        if re.fullmatch(r'\d+', code):
            if not self._dialect_allows('if_then_line'):
                return 'invalid'
            return 'goto' if int(code) in self.program else 'invalid'
        if self._normalize_identifier(code) in self.labels:
            if not self._dialect_allows('if_then_line'):
                return 'invalid'
            return 'goto'
        return 'invalid'

    def _find_then_keyword(self, text: str) -> Optional[int]:
        """Index of THEN in compact IF rest (allows glued forms: ``P$THEN``, ``1THEN``).

        Classic MITS/BBC allow no space before THEN after digits/type suffixes.
        Do not match inside strings, or when THEN is part of an identifier (letter before).
        """
        in_string = False
        index = 0
        while index < len(text):
            ch = text[index]
            if ch == '"':
                in_string = not in_string
                index += 1
                continue
            if (
                not in_string
                and text[index:index + 4].upper() == 'THEN'
                and (index == 0 or not text[index - 1].isalpha())
                and (index + 4 >= len(text) or not text[index + 4].isalnum())
            ):
                return index
            index += 1
        return None

    def _split_bbc_compact_if_then(self, then_part: str) -> Tuple[str, str]:
        then_part = then_part.strip()
        then_at = self._find_then_keyword(then_part)
        if then_at is not None:
            condition = then_part[:then_at].strip()
            statement = then_part[then_at + 4:].strip()
            # Empty statement after THEN is a no-op (museum BETH: IF I$=P$THEN).
            if condition:
                return condition, statement
        # Spaced form still accepted via the same scan; fall back for BBC
        # "IF cond statement" without THEN (e.g. hanoi ``IF F>13 RUN``).
        # Prefer the *longest* condition (rightmost space split) whose tail
        # looks like a statement — do not require the condition to evaluate
        # successfully here (vars may not be ready; eval happens at execute).
        best: Optional[Tuple[str, str]] = None
        for match in re.finditer(r'\s+', then_part):
            condition = then_part[: match.start()].strip()
            statement = then_part[match.end() :].strip()
            if not condition or not statement:
                continue
            # MS/BBC: IF cond linenum  (no THEN) — e.g. IF Y$<>"N" 15
            # Do not let a trailing RHS number steal a real statement already
            # found: piechart ``IF Y% = Cy% + Depth Colour&() OR= 8``.
            if re.fullmatch(r'\d+', statement) and self._dialect_allows('if_then_line'):
                if best is None:
                    best = (condition, statement)
                continue
            if not self._looks_like_statement(statement):
                continue
            best = (condition, statement)
        if best is not None:
            return best
        # MS/BBC: IF Y$<>"N"15  (line number glued to the closing quote)
        glued = self._split_glued_string_linenum(then_part)
        if glued is not None:
            return glued
        # welcome: ``IF(I%AND1)=0:PLOT …`` — colon splits IF from body; condition
        # alone must still parse (body runs via trailing colon stmts).
        stripped = then_part.strip()
        if stripped and self._looks_like_if_condition_only(stripped):
            return stripped, ''
        raise ValueError('invalid IF syntax')

    def _split_glued_string_linenum(self, text: str) -> Optional[Tuple[str, str]]:
        """Split ``Y$<>\"N\"15`` into (``Y$<>\"N\"``, ``15``). Not ``IF A=15``."""
        if not self._dialect_allows('if_then_line'):
            return None
        in_string = False
        last_close = -1
        i = 0
        while i < len(text):
            if text[i] != '"':
                i += 1
                continue
            if in_string and i + 1 < len(text) and text[i + 1] == '"':
                i += 2
                continue
            in_string = not in_string
            if not in_string:
                last_close = i
            i += 1
        if in_string or last_close < 0:
            return None
        tail = text[last_close + 1 :].strip()
        if not re.fullmatch(r'\d+', tail):
            return None
        cond = text[: last_close + 1].strip()
        if not cond:
            return None
        return cond, tail

    def _looks_like_if_condition_only(self, text: str) -> bool:
        """True when text is a bare IF condition (no THEN, no trailing statement)."""
        text = text.strip()
        if not text or self._looks_like_statement(text):
            return False
        if self._find_then_keyword(text) is not None:
            return False
        # Not bare condition if a line number follows (IF cond 100 without THEN).
        if re.search(r'\s+\d+\s*$', text) and self._dialect_allows('if_then_line'):
            return False
        # Comparisons or parenthesized predicates, e.g. (I%AND1)=0
        if re.search(r'(<>|<=|>=|<|>|=)', text):
            return True
        return bool(re.search(r'\b(AND|OR|NOT|EOR|XOR)\b', text, re.IGNORECASE))

    def _if_error_detail(self, rest: str) -> str:
        """Extra hint for common compact-IF mistakes (esp. DEF FN returns)."""
        text = rest.strip()
        # IF cond =expr ELSE =expr  — missing THEN (DEF FN return style)
        if re.search(r'\bELSE\b', text, re.IGNORECASE) and not re.search(
            r'\bTHEN\b', text, re.IGNORECASE
        ):
            if re.search(r'=\s*\S', text):
                return (
                    'IF needs THEN before the branch '
                    '(DEF FN return: IF cond THEN =expr ELSE =expr)'
                )
            return 'IF needs THEN before the true-branch statement'
        # Only flag DEF-FN style when the first non-space after a comparison-like
        # ``=`` is itself ``=`` (``IF cond =expr``), not compact BBC
        # ``IF Y% = n Colour&() OR= 8`` (condition uses =, body is a statement).
        if not re.search(r'\bTHEN\b', text, re.IGNORECASE):
            m = re.match(r'^.+?\s+=\s*(=.*)$', text)
            if m:
                return (
                    'IF needs THEN before =return '
                    '(use: IF cond THEN =expr)'
                )
        return 'IF error'

    def _init_time_clock(self) -> None:
        """Start or restart the BBC-style centisecond clock at zero."""
        self.time_value = 0.0
        self.time_set_at = time.perf_counter()

    def _get_time(self) -> float:
        elapsed_cs = (time.perf_counter() - self.time_set_at) * 100.0
        return int(self.time_value + elapsed_cs)

    def _set_time(self, value: float) -> None:
        self.time_value = float(int(value))
        self.time_set_at = time.perf_counter()

    def _time_string(self) -> str:
        """BBC BASIC TIME$ — 24 characters: ``Day,dd Mon yyyy.hh:mm:ss``.

        jclock (and other demos) use ``VALMID$(Time$,17/20/23)`` for H/M/S.
        A short ``HH:MM:SS`` made those VAL 0 → all hands stacked at 12 o'clock.
        """
        import time
        # %a=Sun, %d=01..31, %b=Jan, %Y=2026, %H:%M:%S → 24 chars in C locale.
        return time.strftime('%a,%d %b %Y.%H:%M:%S')

    def _canonical_system_var_name(self, token: str) -> Optional[str]:
        """Map known mini_basic system vars (_case_sensitive, …).

        BBCSDL user identifiers may also start with ``_`` (e.g. flier ``_BOX``).
        Those are *not* system variables — return None so normal var/array
        paths handle them. Only names in ``_SYSTEM_VAR_SPEC`` are reserved.
        """
        token = token.strip()
        if not token.startswith('_'):
            return None
        if not re.fullmatch(r'_[A-Za-z][A-Za-z0-9_]*', token):
            return None
        key = token.lower()
        if key not in _SYSTEM_VAR_SPEC:
            return None
        return key

    def _get_system_var(self, name: str) -> float:
        key = self._canonical_system_var_name(name) or name
        # BBC ON ERROR: ERR / ERL must work in compiled IF conditions (piechart).
        upper = str(key).upper()
        if upper == 'ERR':
            return float(getattr(self, 'error_code_num', 0) or 0)
        if upper == 'ERL':
            return float(getattr(self, 'error_line_num', 0) or 0)
        if key == '_case_sensitive':
            override = self.config.identifiers_case_sensitive
            if override is None:
                return 2.0
            return 1.0 if override else 0.0
        spec = _SYSTEM_VAR_SPEC[key]
        target = self.config if spec['target'] == 'config' else self
        value = getattr(target, str(spec['attr']))
        if spec['kind'] == 'bool':
            return 1.0 if value else 0.0
        return float(value)

    def _set_system_var(self, name: str, value: float) -> None:
        key = self._canonical_system_var_name(name) or name
        spec = _SYSTEM_VAR_SPEC[key]
        if spec.get('readonly'):
            raise ValueError(f'read-only system variable: {name}')
        if spec['kind'] == 'bool':
            coerced = bool(int(value))
        else:
            coerced = int(value)
        coerced = max(int(spec['min']), min(int(spec['max']), coerced))
        if spec['kind'] == 'bool':
            coerced = bool(coerced)

        if key == '_case_sensitive':
            self.set_case_sensitivity(
                None if coerced == 2 else bool(coerced),
                announce=False,
            )
            return

        target = self.config if spec['target'] == 'config' else self
        setattr(target, str(spec['attr']), coerced)
        if key == '_optimization_level':
            self.config.__post_init__()
            self._compiled_expr_cache.clear()

    def _system_vars_in_expr(self, expr: str) -> Tuple[str, ...]:
        found: List[str] = []
        for name in _SYSTEM_VAR_SPEC:
            if re.search(rf'(?<![A-Za-z0-9_]){re.escape(name)}\b', expr):
                found.append(name)
        # BBC runtime error status (not underscore system vars; used in ON ERROR IF ERR=…)
        for name in ('ERR', 'ERL'):
            if re.search(rf'(?<![A-Za-z0-9_]){name}(?![A-Za-z0-9_$])', expr, re.IGNORECASE):
                # Keep source casing for eval namespace key (BBC uses ERR/ERL).
                m = re.search(
                    rf'(?<![A-Za-z0-9_])({name})(?![A-Za-z0-9_$])',
                    expr,
                    re.IGNORECASE,
                )
                if m and m.group(1) not in found:
                    found.append(m.group(1))
        return tuple(found)

    def _identifiers_case_sensitive(self) -> bool:
        """mini/bbc: case-sensitive by default; mits/com/tiny fold by default.

        When True (any dialect), statement keywords must also be the canonical
        uppercase form (``PRINT``, ``COLOUR``, ``FOR``) so mixed-case names are
        not stolen as commands. When False, keywords accept any case (``print``).
        Dialect still decides which keywords exist; only matching case changes.
        """
        override = self.config.identifiers_case_sensitive
        if override is not None:
            return override
        return self.config.dialect in ('mini', 'bbc')

    def _is_statement_keyword(self, token: str) -> bool:
        """True if token is a statement keyword under current case rules."""
        if not token:
            return False
        if self._identifiers_case_sensitive() and token != token.upper():
            return False
        return token.upper() in self._STMT_KEYWORDS

    def set_case_sensitivity(
        self,
        mode: Optional[bool],
        *,
        announce: bool = True,
    ) -> None:
        old_case = self._identifiers_case_sensitive()
        self.config.identifiers_case_sensitive = mode
        new_case = self._identifiers_case_sensitive()
        if old_case != new_case and self.program:
            self._clear_runtime_variables()
            if announce:
                print('Note: case mode changed — variable values cleared')
        self._definitions_dirty = True
        self._invalidate_program_caches()
        self._invalidate_run_prepare_caches()
        if announce:
            if mode is None:
                print('Case: auto (follows dialect)')
            else:
                print(f'Case: {"on" if mode else "off"}')

    def _var_significant_length(self) -> int:
        """Return how many characters of a variable name are significant.
        0 or large = full name (BBC, mini, modern).
        2 = classic Microsoft BASICs (Commodore, MS, AppleSoft etc.) where only
        first two letters + type suffix matter. This can cause collisions like
        PISTEET and PISTOLA both being "PI".
        """
        if self._identifiers_case_sensitive():
            return 0  # full significance
        dialect = self.config.dialect
        if dialect in ('bbc', 'mini'):
            return 0
        # commodore, mits, tiny etc. classic 2-letter significance
        return 2

    def _loop_var_matches(self, left: str, right: str) -> bool:
        """True when two FOR/NEXT variable names refer to the same loop counter."""
        if not left or not right:
            return not left and not right
        return self._normalize_identifier(left) == self._normalize_identifier(right)

    def _detokenize_fold(self) -> Optional[_SaveFold]:
        """Return LIST/SAVE case folding for mits/bbc (classic detokenize), or None for mini."""
        if self.config.dialect == 'mini':
            return None
        return _fold_from_save_case(self.save_case)

    def _identifier_re_flags(self) -> int:
        return 0 if self._identifiers_case_sensitive() else re.IGNORECASE

    def _check_dim_memory(self, bounds: Tuple[int, ...], kind: VarKind) -> None:
        lower_bound = self.option_base
        if any(b < lower_bound for b in bounds):
            raise ValueError('invalid DIM bounds')
        max_upper = self._bbc_max_dim_upper_bound(kind)
        if any(b > max_upper for b in bounds):
            raise ValueError('Out of memory')
        count = self._array_element_count(bounds, lower_bound)
        if count <= 0:
            raise ValueError('invalid DIM bounds')
        if len(bounds) > 1:
            max_cells = max(1, max_upper + 1)
            if count > max_cells * max_cells:
                raise ValueError('Out of memory')

    def _maybe_infer_fn_return_kind(
        self,
        fn: UserFunction,
        header_rest: str,
        return_expr: Optional[str],
    ) -> None:
        if self._def_fn_header_return_suffix(header_rest) is not None:
            return
        if not return_expr:
            return
        inferred = self._infer_fn_return_kind_from_expr(return_expr)
        if inferred is not None:
            fn.return_kind = inferred

    def _collect_fn_body_return_candidates(
        self,
        body_start: int,
        body_end: int,
        line_nums: List[int],
    ) -> List[str]:
        candidates: List[str] = []
        for line_num in line_nums:
            if line_num < body_start or line_num >= body_end:
                continue
            stmt_parts = self._run_stmts.get(line_num)
            if stmt_parts is None:
                stmt_parts = self._parse_line_statements(self.program[line_num])
            for _, text in stmt_parts:
                candidates.extend(self._collect_fn_return_expr_candidates(text))
        return candidates

    def _finalize_fn_return_kinds(self) -> None:
        limit = max(1, len(self.user_functions)) + 1
        for _ in range(limit):
            changed = False
            for fn in self.user_functions.values():
                if fn.multiline:
                    candidates = self._collect_fn_body_return_candidates(
                        fn.body_start,
                        fn.body_end,
                        self._run_line_nums,
                    )
                elif fn.body:
                    candidates = self._collect_fn_return_expr_candidates(fn.body)
                else:
                    candidates = []
                if self._apply_inferred_fn_return_kind(fn, candidates):
                    changed = True
            if not changed:
                break

    def _ensure_definitions_current(self) -> None:
        if self._definitions_dirty:
            self._refresh_user_definitions_from_program()

    def _rnd_value(self, arg_expr: Optional[str]) -> float:
        if arg_expr is None or not arg_expr.strip():
            value = random.random()
            self._rnd_last = value
            return value
        arg = float(self._eval_numeric(arg_expr.strip()))
        if arg == 0:
            return self._rnd_last
        if arg < 0:
            random.seed(int(abs(arg)))
            value = random.random()
            self._rnd_last = value
            return value
        if arg == 1:
            value = random.random()
            self._rnd_last = value
            return value
        if arg > 1:
            value = float(random.randint(1, int(arg)))
            self._rnd_last = value
            return value
        value = random.random()
        self._rnd_last = value
        return value

    def _sgn_value(self, arg_expr: str) -> float:
        value = self._eval_numeric(arg_expr.strip())
        if value > 0:
            return 1.0
        if value < 0:
            return -1.0
        return 0.0

    def _copy_array_storage(
        self,
        dest_base: str,
        dest_kind: VarKind,
        src_base: str,
        src_kind: VarKind,
    ) -> None:
        dest_key = self._resolve_array_key(dest_base, dest_kind)
        src_key = self._resolve_array_key(src_base, src_kind)
        _, _, src_data = self.array_storage[src_key]
        _, _, dest_data = self.array_storage[dest_key]
        self._copy_array_data(src_data, dest_data, dest_kind)

    def _copy_array_data(self, src_data: object, dest_data: object, kind: VarKind) -> None:
        if (
            isinstance(src_data, list)
            and src_data
            and isinstance(src_data[0], list)
        ):
            for row_index, src_row in enumerate(src_data):
                dest_row = dest_data[row_index]
                for col_index, value in enumerate(src_row):
                    dest_row[col_index] = self._coerce_array_copy_value(value, kind)
            return
        for index, value in enumerate(src_data):
            dest_data[index] = self._coerce_array_copy_value(value, kind)

    def _split_top_level_commas(self, expr: str) -> List[str]:
        return self._split_at_depth(expr, ',', skip_empty=True)

    def _split_dim_decls(self, rest: str) -> List[str]:
        return self._split_at_depth(rest, ',', skip_empty=True)

    def _ensure_var_subst_cache(self) -> None:
        if len(self._var_subst_int_entries) < len(self.int_variables):
            for var in self.int_variables:
                self._register_numeric_var(var, 'int')
        if len(self._var_subst_float_entries) < len(self.variables):
            for var in self.variables:
                self._register_numeric_var(var, 'float')

    def _substitute_bbc_hex_literals(self, expr: str) -> str:
        result: List[str] = []
        index = 0
        in_string = False
        while index < len(expr):
            ch = expr[index]
            if ch == '"':
                in_string = not in_string
                result.append(ch)
                index += 1
                continue
            if not in_string and ch == '%':
                end = index + 1
                while end < len(expr) and expr[end] in '01':
                    end += 1
                if end > index + 1:
                    result.append(str(int(expr[index + 1:end], 2)))
                    index = end
                    continue
            if not in_string and ch == '&':
                end = index + 1
                while end < len(expr) and expr[end] in '0123456789ABCDEFabcdef':
                    end += 1
                if end > index + 1:
                    result.append(str(int(expr[index + 1:end], 16)))
                    index = end
                    continue
            result.append(ch)
            index += 1
        return ''.join(result)

    def _substitute_bbc_numeric_constants(self, expr: str) -> str:
        constants = {
            'SQR5': math.sqrt(5.0),
        }
        for name, value in constants.items():
            expr = re.sub(
                rf'(?<![A-Za-z0-9_]){name}\b',
                str(value),
                expr,
                flags=re.IGNORECASE,
            )
        # Commodore special: the π symbol (U+03C0) is the constant 3.14159...
        # (the letters "PI" are a regular variable in Commodore dialect)
        pi_char = '\u03c0'
        if pi_char in expr:
            expr = re.sub(
                rf'(?<![A-Za-z0-9_]){re.escape(pi_char)}(?![A-Za-z0-9_])',
                str(math.pi),
                expr,
            )
        return expr

    def _substitute_boolean_literals(self, expr: str) -> str:
        expr = re.sub(r'\bTRUE\b', '-1', expr, flags=re.IGNORECASE)
        expr = re.sub(r'\bFALSE\b', '0', expr, flags=re.IGNORECASE)
        return expr

    def _boolean_literal_value(self, expr: str) -> Optional[float]:
        token = expr.strip()
        if re.fullmatch(r'TRUE', token, re.IGNORECASE):
            return -1.0
        if re.fullmatch(r'FALSE', token, re.IGNORECASE):
            return 0.0
        return None

    def _boolean_keyword_at(self, expr: str, index: int, word: str) -> bool:
        if not expr[index:index + len(word)].upper() == word:
            return False
        end = index + len(word)
        if index > 0 and (expr[index - 1].isalnum() or expr[index - 1] == '_'):
            return False
        if end < len(expr) and (expr[end].isalnum() or expr[end] == '_'):
            return False
        return True

    def _boolean_relop_at(self, expr: str, index: int) -> Optional[str]:
        for op in ('<>', '>=', '<=', '=', '<', '>'):
            if not expr.startswith(op, index):
                continue
            if op == '=':
                if index > 0 and expr[index - 1] in '<>!':
                    continue
                if index + 1 < len(expr) and expr[index + 1] == '=':
                    continue
            if op == '<':
                if expr.startswith('<=', index) or (
                    index + 1 < len(expr) and expr[index + 1] == '='
                ):
                    continue
            if op == '>':
                if expr.startswith('>=', index) or (
                    index + 1 < len(expr) and expr[index + 1] == '='
                ):
                    continue
            return op
        return None

    def _boolean_skip_ws(self, expr: str, index: int) -> int:
        while index < len(expr) and expr[index].isspace():
            index += 1
        return index

    def _boolean_find_arith_end(self, expr: str, start: int) -> int:
        index = start
        depth = 0
        in_string = False
        while index < len(expr):
            ch = expr[index]
            if ch == '"':
                in_string = not in_string
                index += 1
                continue
            if in_string:
                index += 1
                continue
            if ch == '(':
                depth += 1
                index += 1
                continue
            if ch == ')':
                if depth > 0:
                    depth -= 1
                    index += 1
                    continue
                break
            if depth == 0:
                for word in ('AND', 'OR', 'NOT', 'XOR', 'EOR', 'EQV', 'IMP'):
                    if self._boolean_keyword_at(expr, index, word):
                        return index
                if self._boolean_relop_at(expr, index) is not None:
                    return index
            index += 1
        return index

    def _strip_outer_parens(self, expr: str) -> str:
        expr = expr.strip()
        while len(expr) >= 2 and expr.startswith('(') and expr.endswith(')'):
            end = self._match_paren(expr, 0)
            if end == len(expr) - 1:
                expr = expr[1:-1].strip()
            else:
                break
        return expr

    def _split_at_first_semicolon(self, text: str) -> Tuple[str, str]:
        return self._split_first_at_depth(text, ';')

    def _decode_console_key(self, raw: object) -> int:
        if isinstance(raw, bytes):
            if raw in (b'\x00', b'\xe0') and sys.platform == 'win32':
                import msvcrt
                ext = msvcrt.getch()
                if isinstance(ext, bytes) and len(ext) == 1:
                    return 0x100 + ext[0]
            if raw:
                return raw[0]
            return 0
        if isinstance(raw, str) and raw:
            return ord(raw[0])
        return 0

    def _sync_field_buffer_from_var(self, var_name: str, value: str, left: bool) -> bool:
        for buffer_info in self.field_buffers.values():
            if var_name not in buffer_info.fields:
                continue
            offset, width = buffer_info.fields[var_name]
            if len(value) < width:
                if left:
                    padded = value + ' ' * (width - len(value))
                else:
                    padded = ' ' * (width - len(value)) + value
            else:
                padded = value[:width] if left else value[-width:]
            buffer_info.buffer[offset:offset + width] = padded.encode('latin-1')
            base, kind = self._parse_var_token(var_name)
            if kind == 'str':
                self.str_variables[base] = padded
            return True
        return False

    def _loc_value(self, file_num: int) -> float:
        file_num = int(file_num)
        buffer_info = self.field_buffers.get(file_num)
        if buffer_info is not None:
            return float(buffer_info.current_record)
        file_channel = self._get_file_channel(file_num)
        if file_channel is None:
            raise ValueError('file not open')
        pos = file_channel.handle.tell()
        return float(pos // 128)

    def _lof_value(self, file_num: int) -> float:
        file_num = int(file_num)
        file_channel = self._get_file_channel(file_num)
        if file_channel is None:
            raise ValueError('file not open')
        handle = file_channel.handle
        current_pos = handle.tell()
        handle.seek(0, 2)
        size = handle.tell()
        handle.seek(current_pos)
        return float(size)

    def _ptr_value(self, file_num: int) -> float:
        file_num = int(file_num)
        file_channel = self._get_file_channel(file_num)
        if file_channel is None:
            raise ValueError('file not open')
        return float(file_channel.handle.tell())

    def _eof_value(self, file_num: int) -> float:
        """BBC ``EOF#channel``: true (-1) when no more bytes/chars can be read.

        Do **not** compare ``tell()`` cookies from text-mode handles: on Windows
        (and with ``TextIOWrapper``) ``tell()`` is an opaque cookie, not a byte
        offset, so ``pos >= end`` falsely reports EOF after the first ``INPUT#``
        (broke animal.dat reload — only A$(0) loaded, tree empty → ``Is it an?``).
        """
        file_num = int(file_num)
        file_channel = self._get_file_channel(file_num)
        if file_channel is None:
            return 0.0
        if file_channel.eof:
            return -1.0
        handle = file_channel.handle
        # Peek one character; restore position via the opaque cookie.
        try:
            cookie = handle.tell()
        except Exception:
            cookie = None
        ch = handle.read(1)
        if not ch:
            file_channel.eof = True
            return -1.0
        if cookie is not None:
            try:
                handle.seek(cookie)
            except Exception:
                # Last resort: cannot unget — leave stream advanced (rare).
                pass
        else:
            # No tell support: try to push back via buffer if binary-like.
            try:
                if hasattr(handle, 'seek') and hasattr(handle, 'readable'):
                    handle.seek(handle.tell() - len(ch.encode(handle.encoding or 'utf-8')))
            except Exception:
                pass
        return 0.0

    def _cvi_value(self, arg: str) -> float:
        text = self._eval_string_arg(arg)
        if len(text) != 2:
            raise ValueError('CVI requires 2-byte string')
        return float(struct.unpack('<h', text.encode('latin-1'))[0])

    def _cvs_value(self, arg: str) -> float:
        text = self._eval_string_arg(arg)
        if len(text) != 4:
            raise ValueError('CVS requires 4-byte string')
        return float(struct.unpack('<f', text.encode('latin-1'))[0])

    def _cvd_value(self, arg: str) -> float:
        text = self._eval_string_arg(arg)
        if len(text) != 8:
            raise ValueError('CVD requires 8-byte string')
        return float(struct.unpack('<d', text.encode('latin-1'))[0])

    def _mki_value(self, arg: str) -> str:
        value = int(self._eval_numeric(arg))
        if value < -32768:
            value = -32768
        elif value > 32767:
            value = 32767
        return struct.pack('<h', value).decode('latin-1')

    def _mks_value(self, arg: str) -> str:
        return struct.pack('<f', float(self._eval_numeric(arg))).decode('latin-1')

    def _mkd_value(self, arg: str) -> str:
        return struct.pack('<d', float(self._eval_numeric(arg))).decode('latin-1')

    def _inline_next_var_mismatch(
        self,
        loop_var: str,
        stmt_parts: List[Tuple[Optional[str], str]],
        start_idx: int,
    ) -> Optional[str]:
        """Return the NEXT variable name when it does not match ``loop_var``."""
        opened: List[str] = [loop_var]
        extra_depth = 0
        for idx in range(start_idx, len(stmt_parts)):
            _, text = stmt_parts[idx]
            cmd, rest = self._parse_command(text)
            if cmd == 'FOR':
                match = self._match_for_clause(rest)
                if match:
                    v = match.group(1) + (match.group(2) or '')
                    opened.append(self._parse_var_token(v)[0])
                else:
                    extra_depth += 1
            elif cmd in ('WHILE', 'REPEAT'):
                extra_depth += 1
            elif cmd in ('WEND', 'UNTIL'):
                if extra_depth > 0:
                    extra_depth -= 1
            elif cmd == 'NEXT':
                names = self._prepare_next_vars(
                    self._parse_next_vars(rest), opened, match_stack=True,
                )
                for next_var in names:
                    if extra_depth > 0:
                        extra_depth -= 1
                        continue
                    if not opened:
                        return next_var or '?'
                    top = opened[-1]
                    if next_var and not self._loop_var_matches(next_var, top):
                        return next_var
                    popped = opened.pop()
                    if self._loop_var_matches(popped, loop_var):
                        return None
        return None

    def _swap_lvalues(self, left_token: str, right_token: str) -> None:
        left = self._read_lvalue(left_token)
        right = self._read_lvalue(right_token)
        if left[2] != right[2]:
            raise ValueError('type mismatch')
        left_value = left[4]
        self._write_lvalue(left, right[4])
        self._write_lvalue(right, left_value)

    def _reset_run_state(self) -> None:
        self.variables.clear()
        self.int_variables.clear()
        self.str_variables.clear()
        self.array_storage.clear()
        self.data_pointer = 0
        self._rnd_last = 0.0
        self._refresh_enabled = True
        self.stack.clear()
        self.if_stack.clear()
        self.gosub_stack.clear()
        self.proc_stack.clear()
        self.resume_at = None
        self.error_trap_line = 0
        self.error_trap_gosub = False
        self._inline_error_handlers.clear()
        self._on_error_skip_rest_of_line = None
        self._run_error_handler_for_line = None
        self._in_error_handler = False
        self.on_close_action = None
        self._on_close_handler = None
        self.error_resume_at = None
        self.error_line_num = 0
        self.error_code_num = 0
        self.error_message = ''
        self.option_base = 0
        self.default_var_types.clear()
        self.print_column = 0
        self.bbc_at_percent = 0
        self.bbc_page = 0x8000
        self.bbc_lomem = 0x8000
        self.bbc_himem = self.bbc_lomem + 400_000
        self.text_fg_colour = None
        self.text_bg_colour = 0
        self._last_emitted_fg_colour = None
        self.text_row = 0
        self.text_col = 0
        self._print_line_parts = []
        self._console_write_buffer = []
        self._last_present_time = 0.0
        self._clear_stop_state()
        self._run_aborted = False

    def run(self):
        if not self.program:
            print('No program loaded.')
            return

        self._reset_run_state()
        if self._program_stdout is None:
            self._ensure_ansi_console()
        self._close_file_channels()
        self._prepare_run()
        self._apply_dialect_hints_from_program(announce=False)
        self._maybe_auto_enable_pygame_from_program(announce=True)
        self._apply_program_refresh_off_at_start()
        self._announce_program_graphics()
        self._ensure_display()
        self._apply_program_refresh_off_at_start()

        self._run_interrupt_watch = True
        try:
            self._run_program_loop(0)
        except KeyboardInterrupt:
            self._run_aborted = True
            print('\nGoodbye!')
        except BasicRuntimeError:
            # BASIC runtime error (including unknown statements) was already printed by _runtime_error.
            # Do not let the Python exception leak as a traceback to the user.
            pass
        finally:
            self._run_interrupt_watch = False
            self._flush_program_output()
            if not self.stopped:
                self._close_file_channels()
            hold = self.config.hold_display_open and not getattr(self, '_run_aborted', False)
            self._shutdown_display(hold=hold)
            # Always put the host shell (PowerShell scrollback / line editing)
            # back to normal — including after a finished RUN with no Ctrl+C.
            try:
                self._restore_console()
            except Exception:
                pass

    def cont(self) -> None:
        if not self._stop_resume_valid():
            self._emit_error("?Can't continue")
            self._clear_stop_state()
            return

        resume_line, _ = self.stop_resume_at
        self.resume_at = self.stop_resume_at
        self.stopped = False
        self.stop_resume_at = None

        if self._program_stdout is None:
            self._ensure_ansi_console()
        self._prepare_run()
        self._ensure_display()

        start_index = self._run_line_index.get(resume_line)
        if start_index is None:
            self._emit_error("?Can't continue")
            self._clear_stop_state()
            return

        self._run_interrupt_watch = True
        try:
            self._run_program_loop(start_index)
        except KeyboardInterrupt:
            self._run_aborted = True
            print('\nGoodbye!')
        except BasicRuntimeError:
            # Error already printed
            pass
        finally:
            self._run_interrupt_watch = False
            self._flush_program_output()
            if not self.stopped:
                self._close_file_channels()
            self._shutdown_display()

    def _compute_loop_depths(self) -> Dict[int, int]:
        line_nums = sorted(self.program)
        headers, bodies, ends = self._collect_def_layout(line_nums)
        depths: Dict[int, int] = {}
        outer = 0
        inner = 0

        for line_num in line_nums:
            parts = self._split_colon_statements(self.program[line_num])
            in_def_body = line_num in bodies
            active = inner if in_def_body else outer
            line_depth = active
            if in_def_body:
                line_depth = 1 + inner
            for part in parts:
                _, text = self._extract_label_prefix(part)
                if not text:
                    continue
                cmd, rest = self._parse_command(text)
                if cmd in (
                    'NEXT', 'WEND', 'UNTIL', 'ENDIF', 'ELSE', 'ELSEIF', 'ELIF',
                    'ENDCASE', 'WHEN', 'OTHERWISE',
                ):
                    line_depth = (1 + max(0, active - 1)) if in_def_body else max(0, active - 1)
                    break

            depths[line_num] = line_depth

            for part in parts:
                _, text = self._extract_label_prefix(part)
                if not text:
                    continue
                cmd, rest = self._parse_command(text)
                if line_num in headers or line_num in ends:
                    continue
                if cmd in ('FOR', 'WHILE', 'REPEAT', 'CASE'):
                    if in_def_body:
                        inner += 1
                    else:
                        outer += 1
                elif cmd == 'IF' and self._is_structured_if(rest):
                    if in_def_body:
                        inner += 1
                    else:
                        outer += 1
                elif cmd in ('NEXT', 'WEND', 'UNTIL', 'ENDIF', 'ENDCASE'):
                    if in_def_body:
                        inner = max(0, inner - 1)
                    else:
                        outer = max(0, outer - 1)
        return depths

    def resolve_path(self, filename: str) -> str:
        filename = _parse_path_arg(filename)
        if not filename:
            raise ValueError('missing filename')
        if os.path.isabs(filename):
            return os.path.normpath(filename)
        return os.path.normpath(os.path.join(self.working_dir, filename))

    def resolve_load_path(self, filename: str) -> str:
        """Resolve a LOAD/CHAIN path; append .bas/.bbc if the name has no extension.

        If the exact path exists, it is returned. Otherwise, when the basename has
        no extension, try ``.bas`` then ``.bbc`` (and uppercase variants). Does not
        invent an extension when the user already supplied one (e.g. ``.txt``).
        """
        path = self.resolve_path(filename)
        if os.path.isfile(path):
            return path
        _root, ext = os.path.splitext(path)
        if ext:
            return path
        for suffix in ('.bas', '.bbc', '.BAS', '.BBC'):
            candidate = path + suffix
            if os.path.isfile(candidate):
                return candidate
        return path

    def change_dir(self, path: Optional[str] = None) -> None:
        if not path:
            print(self.working_dir)
            return
        try:
            path = _parse_path_arg(path)
        except ValueError:
            self._emit_error('? CD path')
            return
        target = path if os.path.isabs(path) else os.path.normpath(os.path.join(self.working_dir, path))
        if not os.path.isdir(target):
            self._emit_error('? Directory not found')
            return
        self.working_dir = os.path.normpath(target)

    def new(self, *, clear_loaded_filename: bool = True, announce: bool = True):
        self.program.clear()
        self.line_indent.clear()
        self.labels.clear()
        self.variables.clear()
        self.int_variables.clear()
        self.str_variables.clear()
        self.array_storage.clear()
        self.struct_defs.clear()
        self.struct_members.clear()
        self.data_items.clear()
        self.data_line_starts.clear()
        self._data_lines_ordered.clear()
        self._data_locations.clear()
        self.data_pointer = 0
        self.user_functions.clear()
        self.user_procedures.clear()
        self._definitions_dirty = True
        self.proc_stack.clear()
        self._rnd_last = 0.0
        self.stack.clear()
        self.if_stack.clear()
        self.gosub_stack.clear()
        self.resume_at = None
        self.error_trap_line = 0
        self.error_trap_gosub = False
        self._inline_error_handlers.clear()
        self._on_error_skip_rest_of_line = None
        self._run_error_handler_for_line = None
        self._in_error_handler = False
        self.error_resume_at = None
        self.error_line_num = 0
        self.error_code_num = 0
        self.error_message = ''
        self.option_base = 0
        self.default_var_types.clear()
        self._close_file_channels()
        self._clear_stop_state()
        if clear_loaded_filename:
            self.loaded_filename = None
        self._program_source_numbered = None
        self._invalidate_program_caches()
        self._run_line_nums = []
        self._run_line_index = {}
        self._run_stmts = {}
        self._run_for_next = {}
        self._run_while_wend = {}
        self._var_subst_int_entries = []
        self._var_subst_float_entries = []
        self._compiled_expr_cache = {}
        if announce:
            print('Program cleared.', file=self._get_error_stream())

    @staticmethod
    def _preview_source_line(line: str, *, limit: int = 56) -> str:
        text = ' '.join(line.rstrip('\n').split())
        if len(text) > limit:
            return text[: limit - 3] + '...'
        return text

    def _append_indented_continuation(
        self,
        numbered: List[Tuple[int, str, int]],
        statement: str,
        indent: int,
    ) -> None:
        if not numbered:
            raise ValueError('indented continuation without a numbered line')
        line_num, prev_stmt, prev_indent = numbered[-1]
        numbered[-1] = (
            line_num,
            f'{prev_stmt}: {statement}',
            max(prev_indent, indent),
        )

    def _classify_multiline_def_start(self, text: str) -> Optional[str]:
        text = text.strip()
        if not text:
            return None
        for part in self._split_colon_statements(text):
            _, statement = self._extract_label_prefix(part)
            if not statement:
                continue
            cmd, rest = self._parse_command(statement)
            if cmd != 'DEF':
                return None
            rest_strip = rest.strip()
            # DEFINT/DEFSNG/DEFDBL/DEFSTR are type defaults, not multiline DEF.
            if re.match(r'^(INT|SNG|DBL|STR)\b', rest_strip, re.IGNORECASE):
                return None
            if self._RE_DEF_PROC.match(rest_strip):
                return 'proc'
            if re.search(r'\)\s*=', rest_strip):
                return None
            try:
                self._parse_def_fn_header(rest_strip)
                return 'fn'
            except ValueError:
                return None
        return None

    def auto_entry(self, start: int = 10, step: int = 10):
        print(f'AUTO from {start} step {step} (empty line to exit)')
        self._auto_entry_loop(start, step)

    def def_block_entry(self, first_statement: str, step: int = 10) -> None:
        kind = self._classify_multiline_def_start(first_statement)
        if kind is None:
            self._emit_error('? DEF error')
            return
        if kind == 'proc' and not self._dialect_allows('PROC'):
            self._emit_error('? DEF PROC not allowed in mits/commodore/tiny dialect')
            return
        if kind == 'fn' and not self._dialect_allows('multiline_def'):
            if not self._report_dialect_violation(
                'multiline DEF FN not allowed in mits/commodore/tiny dialect'
            ):
                return

        start = self._next_auto_line_start(step)
        stored_num, statement = self._parse_auto_line(start, first_statement)
        indent, statement = self._preserve_or_parse_indent(
            stored_num,
            statement,
            fallback_line=start,
        )
        self.set_program_line(stored_num, statement, indent)
        next_line = stored_num + step
        kind_label = 'DEF PROC' if kind == 'proc' else 'DEF FN'
        print(f'{kind_label} entry from {next_line} step {step} (empty line to exit)')
        self._auto_entry_loop(next_line, step)
        self._ensure_definitions_current()

    def edit_line(self, line_num: int):
        current = self.program.get(line_num)
        indent = self.line_indent.get(line_num, 0)
        indent_text = ' ' * indent
        number_field = self._format_line_number(line_num, True)
        if current is not None:
            print(f'{number_field}{indent_text}{current}')
        else:
            print(f'{number_field}(new line)')
        try:
            default = f'{indent_text}{current}' if current else ''
            # Call via helpers module so tests can patch helpers._prompt_editing_input.
            from . import helpers as _helpers
            text = _helpers._prompt_editing_input(f'{line_num} ', default)
        except (KeyboardInterrupt, EOFError):
            print()
            return
        if not text:
            # Empty Enter: cancel edit — leave existing line unchanged (do not delete).
            # Delete with bare line number at > (e.g. 15) or NEW/clear line content.
            return
        stored_num, statement = self._parse_auto_line(line_num, text)
        new_indent, statement = self._preserve_or_parse_indent(
            stored_num,
            statement,
            fallback_line=line_num,
        )
        if stored_num != line_num:
            self.line_indent.pop(line_num, None)
        self.set_program_line(stored_num, statement, new_indent)

