"""BASICInterpreter mixin: defs.

DEF FN / DEF PROC, LOCAL, and user callables.

Auto-generated by tools/split_runtime_mixins.py — do not hand-edit bulk.
"""
# ruff: noqa: F401,F403,F405,E402,W291,W293
# Imports mirrored from monorepo runtime for method bodies.
import fnmatch
import json
import math
import random
import re
import os
import struct
import sys
import time

from ..config import DEFAULT_CONFIG, InterpreterConfig, SYSTEM_VAR_SPEC
from ..dialect_hint import DialectHint, parse_comment_dialect_line, split_dialect_hints
from ..constants import (
    CLI_EXIT_WORDS as _CLI_EXIT_WORDS,
    EXIT_HOLD_CONSOLE,
    EXPR_RESERVED_WORDS as _EXPR_RESERVED_WORDS,
    NUMERIC_BUILTIN_FUNCS as _NUMERIC_BUILTIN_FUNCS,
    NUMERIC_BUILTIN_FUNC_RE as _NUMERIC_BUILTIN_FUNC_RE,
    SAFE_EVAL_GLOBALS as _SAFE_EVAL_GLOBALS,
)
from ..expr.compile import CompiledExpr, int_slot
from ..expr.patterns import (
    RE_ARRAY_HEAD as _RE_ARRAY_HEAD,
    RE_COND_EQ as _RE_COND_EQ,
    RE_COND_NE as _RE_COND_NE,
    RE_DYNAMIC_CALL_REMAINS as _RE_DYNAMIC_CALL_REMAINS,
    RE_FILE_FUNC as _RE_FILE_FUNC,
    RE_FILE_FUNC_BBC as _RE_FILE_FUNC_BBC,
    RE_FN_CALL as _RE_FN_CALL,
    RE_FUNC_CALL as _RE_FUNC_CALL,
    RE_HAS_LETTER as _RE_HAS_LETTER,
    RE_INKEY_CALL as _RE_INKEY_CALL,
    RE_INT_DIV as _RE_INT_DIV,
    RE_MOD as _RE_MOD,
    RE_NUMERIC_FUNC_CALL as _RE_NUMERIC_FUNC_CALL,
    RE_TIME as _RE_TIME,
    RE_VAR_BASE_FULL as _RE_VAR_BASE_FULL,
    PROC_FN_NAME_PATTERN as _PROC_FN_NAME_PATTERN,
    VAR_BASE_PATTERN as _VAR_BASE_PATTERN,
)

from ..format import UsingFormatter
from ..format.save_case import (
    Fold as _SaveFold,
    fold_from_save_case as _fold_from_save_case,
    format_program_line as _format_program_line_save_case,
    format_statement_part as _format_statement_part_save_case,
)
from ..repl.completion import configure_readline as _configure_repl_readline
from ..repl.help_browser import run_help_browser as _run_help_browser
from ..util import (
    basic_truth as _basic_truth,
    hard_exit as _hard_exit,
    near_equal as _near_equal,
    near_equal_sig as _near_equal_sig,
    probe_float_platform as _probe_float_platform,
)
from ..type_system import (
    ArrayStorage,
    BasicRuntimeError,
    ChainTransfer,
    DataItem,
    Dialect,
    FieldBuffer,
    FileChannel,
    FnReturn,
    CaseBlockLayout,
    CaseFrame,
    IfBlockLayout,
    IfFrame,
    ListCommand,
    LoopFrame,
    ProcReturn,
    ProgramExit,
    ProgramStop,
    UserFunction,
    UserProcedure,
    VarKind,
)
from typing import Callable, Dict, List, Optional, Set, TextIO, Tuple

_SYSTEM_VAR_SPEC = SYSTEM_VAR_SPEC

       
# BBC Micro MODE specs (text grid, graphics resolution, PAR) — see bbc_modes.py.
from mini_basic.bbc_modes import bbc_mode_spec

from .helpers import (
    _get_readline_module,
    _windows_arrow_action,
    _windows_apply_arrow,
    _windows_editing_input,
    _prompt_editing_input,
    _parse_path_arg,
    _apply_pygame_display_defaults,
)

class RuntimeDefsMixin:
    """Mixin providing defs-related BASICInterpreter methods."""

    def _parse_def_fn_header(self, rest: str) -> UserFunction:
        # BBC: DEF FNgetbmp  (no ()) and DEF FNfoo(x).
        match = re.match(
            rf'^FN_?\s*{_PROC_FN_NAME_PATTERN}(%|\$)?\s*(?:\((.*)\))?\s*$',
            rest.strip(),
            flags=re.IGNORECASE,
        )
        if not match:
            got = rest.strip() or '(empty)'
            raise ValueError(f'need FNname or FNname(args), got {got!r}')
        name = self._normalize_identifier(match.group(1))
        return_suffix = match.group(2)
        return_kind: VarKind = 'float'
        if return_suffix == '$':
            return_kind = 'str'
        elif return_suffix == '%':
            return_kind = 'int'
        params: List[Tuple[str, VarKind]] = []
        array_params: List[str] = []
        params_text = (match.group(3) or '').strip()
        if params_text:
            for token in self._split_args(params_text):
                param_name, param_kind, is_array = self._parse_param_token(token)
                params.append((param_name, param_kind))
                if is_array:
                    array_params.append(param_name)
        return UserFunction(
            name=name,
            return_kind=return_kind,
            params=tuple(params),
            array_params=tuple(array_params),
        )

    def _def_fn_header_return_suffix(self, header_rest: str) -> Optional[str]:
        match = re.match(
            rf'^FN_?\s*{_PROC_FN_NAME_PATTERN}(%|\$)?\s*(?:\(|$)',
            header_rest.strip(),
            flags=re.IGNORECASE,
        )
        if not match:
            return None
        return match.group(2)

    def _warn_def_fn_missing_returns(self) -> None:
        for fn in self.user_functions.values():
            if not fn.multiline:
                continue
            candidates = self._collect_fn_body_return_candidates(
                fn.body_start,
                fn.body_end,
                self._run_line_nums,
            )
            if candidates:
                continue
            print(
                f'? Line {fn.body_start}: DEF FN body needs =return '
                f'(e.g. THEN = 1)'
            )

    def _parse_def_fn_rest(self, rest: str) -> UserFunction:
        match = re.match(
            rf'^FN_?\s*{_PROC_FN_NAME_PATTERN}(%|\$)?\s*(?:\((.*)\))?\s*=\s*(.+)$',
            rest.strip(),
            flags=re.IGNORECASE,
        )
        if not match:
            raise ValueError('invalid DEF FN syntax')
        fn = self._parse_def_fn_header(
            f"FN{match.group(1)}{match.group(2) or ''}({match.group(3) or ''})"
        )
        body = match.group(4).strip()
        if not body:
            raise ValueError('empty DEF FN body')
        fn.body = body
        self._maybe_infer_fn_return_kind(
            fn,
            f"FN{match.group(1)}{match.group(2) or ''}({match.group(3) or ''})",
            body,
        )
        return fn

    def _register_def_fn(self, rest: str) -> None:
        fn = self._parse_def_fn_rest(rest)
        self.user_functions[fn.name] = fn
        self._fn_memoable.clear()
        self._fn_memo_steps.clear()
        self._fn_memo.clear()

    def _lookup_user_function(self, name: str):
        """Find DEF FN by stored name; fold case if the exact key is missing.

        BBC listings keep ``DEF FNstrip`` under ``strip`` when identifiers are
        case-sensitive. Calls and tests may still write ``FNSTRIP`` / ``STRIP``.
        """
        key = self._normalize_identifier(name)
        fn = self.user_functions.get(key)
        if fn is not None:
            return fn
        folded = key.lower()
        for stored, candidate in self.user_functions.items():
            if stored.lower() == folded:
                return candidate
        return None

    def _is_def_fn_or_proc_header(self, cmd: str, rest: str) -> bool:
        if cmd != 'DEF':
            return False
        rest_strip = rest.strip()
        try:
            self._parse_def_proc_header(rest_strip)
            return True
        except ValueError:
            pass
        if re.search(r'\)\s*=', rest_strip):
            return False
        try:
            self._parse_def_fn_header(rest_strip)
            return True
        except ValueError:
            return False

    def _parse_def_proc_header(self, rest: str) -> UserProcedure:
        """Parse ``PROC name(params)`` optionally followed by same-line body.

        BBCSDL hanoi style::

            DEF PROCHANOI(A,B,C,D) IF A=0 ENDPROC
            PROCHANOI(A-1,...)
            ENDPROC
        """
        text = rest.strip()
        # Allow trailing body after the closing ')' or bare name.
        # Use PROC_FN_NAME_PATTERN (includes numeric PROC4); not letter-only.
        match = re.match(
            rf'^PROC_?\s*{_PROC_FN_NAME_PATTERN}\s*(?:\((.*)\))?\s*(.*)$',
            text,
            re.IGNORECASE,
        )
        if not match:
            raise ValueError('invalid DEF PROC header')
        name = self._normalize_identifier(match.group(1))
        params: List[Tuple[str, VarKind]] = []
        array_params: List[str] = []
        return_params: List[str] = []
        params_text = (match.group(2) or '').strip()
        if params_text:
            for token in self._split_args(params_text):
                raw = token.strip()
                is_return = False
                ret_m = re.match(r'^RETURN\s+(.+)$', raw, re.IGNORECASE)
                if ret_m:
                    is_return = True
                    raw = ret_m.group(1).strip()
                param_name, param_kind, is_array = self._parse_param_token(raw)
                params.append((param_name, param_kind))
                if is_array:
                    array_params.append(param_name)
                if is_return:
                    return_params.append(param_name)
        header_stmt = (match.group(3) or '').strip()
        return UserProcedure(
            name=name,
            params=tuple(params),
            array_params=tuple(array_params),
            return_params=tuple(return_params),
            header_stmt=header_stmt,
        )

    def _call_procedure(self, proc: UserProcedure, args: List[str]) -> None:
        if len(args) != len(proc.params):
            raise ValueError('wrong number of arguments')
        bindings: List[Tuple[str, VarKind, object]] = []
        array_aliases: Dict[Tuple[str, VarKind], Tuple[str, VarKind]] = {}
        array_param_set = set(proc.array_params)
        return_param_set = set(getattr(proc, 'return_params', ()) or ())
        return_targets: List[Tuple[str, VarKind, str]] = []
        for (param_name, param_kind), arg_expr in zip(proc.params, args):
            if param_name in array_param_set:
                actual_base, actual_kind = self._parse_array_ref(arg_expr.strip())
                if actual_kind != param_kind:
                    raise ValueError('array parameter type mismatch')
                array_aliases[(param_name, param_kind)] = (actual_base, actual_kind)
                continue
            if param_kind == 'str':
                bindings.append((param_name, param_kind, self._eval_string_expr(arg_expr)))
            elif param_kind == 'int':
                bindings.append((
                    param_name,
                    param_kind,
                    self._coerce_int_storage(self._eval_numeric(arg_expr)),
                ))
            else:
                bindings.append((param_name, param_kind, self._eval_numeric(arg_expr)))
            if param_name in return_param_set:
                return_targets.append((param_name, param_kind, arg_expr.strip()))
        saved = self._apply_fn_param_bindings(bindings)
        saved_array_aliases = dict(self._array_aliases)
        self._array_aliases.update(array_aliases)
        self.proc_stack.append(saved)
        try:
            if self._trace_call('PROC', proc.name):
                raise ProgramStop()
            # Same-line prefix on DEF PROC line (e.g. IF A=0 ENDPROC) runs first.
            header = (getattr(proc, 'header_stmt', None) or '').strip()
            if header:
                line_nums = sorted(self.program.keys()) or [0]
                def_line = proc.body_start or 0
                if (
                    proc.body_start
                    and proc.body_end
                    and proc.body_start <= proc.body_end
                    and line_nums
                ):
                    try:
                        bi = line_nums.index(proc.body_start)
                        # Multi-line: body_start is first line *after* DEF.
                        if proc.body_start != proc.body_end or bi > 0:
                            def_line = (
                                line_nums[bi - 1]
                                if bi > 0 and proc.body_start != proc.body_end
                                else proc.body_start
                            )
                    except ValueError:
                        def_line = proc.body_start
                self._execute_inline_statements(header, def_line, line_nums)
                # Pure single-line DEF PROC … ENDPROC: no multi-line body.
                if proc.body_start == proc.body_end and re.search(
                    r'\bENDPROC\b', header, re.IGNORECASE
                ):
                    return
            self._run_procedure_body(proc)
        except ProcReturn:
            pass
        except BasicRuntimeError:
            # Let outer error trap / RESUME handling deal with it (e.g. trap was set
            # outside the PROC). Do not turn it into a generic PROC error.
            raise
        finally:
            outgoing: List[Tuple[str, VarKind, object]] = []
            for param_name, param_kind, dest_expr in return_targets:
                if param_kind == 'str':
                    value = self.str_variables.get(param_name, '')
                elif param_kind == 'int':
                    value = self.int_variables.get(param_name, 0)
                else:
                    value = self.variables.get(param_name, 0.0)
                outgoing.append((dest_expr, param_kind, value))
            saved_outer = self.proc_stack.pop()
            self._restore_fn_param_bindings(saved_outer)
            self._array_aliases = saved_array_aliases
            for dest_expr, param_kind, value in outgoing:
                try:
                    self._assign_input_value(
                        dest_expr,
                        value if param_kind == 'str' else str(value),
                    )
                except Exception:
                    loc = self._read_lvalue(dest_expr)
                    self._write_lvalue(loc, value)

    def _collect_def_layout(
        self,
        line_nums: List[int],
    ) -> Tuple[Set[int], Set[int], Set[int]]:
        headers: Set[int] = set()
        bodies: Set[int] = set()
        ends: Set[int] = set()
        idx = 0
        while idx < len(line_nums):
            line_num = line_nums[idx]
            stmt_parts = self._run_stmts.get(line_num)
            if stmt_parts is None:
                stmt_parts = self._parse_line_statements(self.program[line_num])
            handled = False
            for _, text in stmt_parts:
                cmd, rest = self._parse_command(text)
                if cmd != 'DEF':
                    continue
                if self._RE_DEF_PROC.match(rest.strip()):
                    end_line = self._find_matching_endproc(line_num, line_nums)
                    if end_line is not None and idx + 1 < len(line_nums):
                        headers.add(line_num)
                        ends.add(end_line)
                        end_idx = self._line_index(end_line, line_nums)
                        for body_idx in range(idx + 1, end_idx):
                            bodies.add(line_nums[body_idx])
                        idx = end_idx
                        handled = True
                    break
                if re.search(r'\)\s*=', rest):
                    break
                try:
                    self._parse_def_fn_header(rest)
                except ValueError:
                    break
                end_line = self._find_matching_end_def(line_num, line_nums)
                if end_line is None:
                    equals_return = self._find_def_fn_equals_return(line_num, line_nums)
                    if equals_return is not None:
                        equals_line, _ = equals_return
                        headers.add(line_num)
                        bodies.add(equals_line)
                        end_idx = self._line_index(equals_line, line_nums)
                        idx = end_idx
                        handled = True
                    break
                if idx + 1 >= len(line_nums):
                    break
                headers.add(line_num)
                ends.add(end_line)
                end_idx = self._line_index(end_line, line_nums)
                for body_idx in range(idx + 1, end_idx):
                    bodies.add(line_nums[body_idx])
                idx = end_idx
                handled = True
                break
            if not handled:
                idx += 1
        return headers, bodies, ends

    def _fn_source_text(self, fn: UserFunction) -> str:
        if not fn.multiline:
            return fn.body or ''
        parts: List[str] = []
        header_line = int(getattr(fn, 'header_line', 0) or 0)
        for line_num in sorted(self.program):
            if header_line and line_num == header_line:
                parts.append(self.program[line_num])
            elif fn.body_start <= line_num < fn.body_end:
                parts.append(self.program[line_num])
        return '\n'.join(parts)

    def _fn_is_memoable(self, fn: UserFunction) -> bool:
        if fn.array_params:
            return False
        if not self._fn_memoable and self.user_functions:
            self._rebuild_fn_memoable()
        elif fn.name not in self._fn_memoable and self.user_functions:
            self._rebuild_fn_memoable()
        return bool(self._fn_memoable.get(fn.name, False))

    def _fn_reaches_self(self, name: str, callees: Dict[str, Set[str]]) -> bool:
        """True if *name* is recursive (direct self-call or a mutual cycle)."""
        graph: Dict[str, Set[str]] = {}
        for stored, called in callees.items():
            graph[stored.lower()] = {c.lower() for c in called}
        start = str(name).lower()
        seen: Set[str] = set()
        stack = list(graph.get(start, ()))
        while stack:
            cur = stack.pop()
            if cur == start:
                return True
            if cur in seen:
                continue
            seen.add(cur)
            stack.extend(graph.get(cur, ()))
        return False

    def _rebuild_fn_memoable(self) -> None:
        """Cache only pure recursive DEF FN (self-call or mutual cycle)."""
        local_ok: Dict[str, bool] = {}
        callees: Dict[str, Set[str]] = {}
        for fn in self.user_functions.values():
            ok, called = self._fn_local_memoable(fn)
            local_ok[fn.name] = ok
            callees[fn.name] = called
        memoable = dict(local_ok)
        changed = True
        while changed:
            changed = False
            for name, ok in list(memoable.items()):
                if not ok:
                    continue
                for callee in callees.get(name, ()):
                    if not memoable.get(callee, False):
                        memoable[name] = False
                        changed = True
                        break
        for name in list(memoable):
            if memoable[name] and not self._fn_reaches_self(name, callees):
                memoable[name] = False
        self._fn_memoable = memoable
        steps: Dict[str, list] = {}
        for fn in self.user_functions.values():
            if not memoable.get(fn.name):
                continue
            compiled = self._compile_fn_memo_steps(fn)
            if compiled is not None:
                steps[fn.name] = compiled
        self._fn_memo_steps = steps

    def _fn_local_memoable(self, fn: UserFunction) -> Tuple[bool, Set[str]]:
        if fn.array_params:
            return False, set()
        text = self._fn_source_text(fn)
        text = re.sub(r'"[^"]*"', ' ', text)
        text = re.sub(r'\bREM\b.*', ' ', text, flags=re.IGNORECASE)
        ident_re = re.compile(
            rf'(?<![A-Za-z0-9_])({_VAR_BASE_PATTERN})([$%#!]?)',
            re.IGNORECASE,
        )
        allowed = set(_FN_MEMO_KEYWORDS)
        allowed.update(_FN_MEMO_PURE_BUILTINS)
        for param_name, _kind in fn.params:
            allowed.add(self._normalize_identifier(param_name).upper().rstrip('%$!#'))
            allowed.add(self._normalize_identifier(param_name).upper())
        fname = str(fn.name).upper()
        allowed.add(fname)
        allowed.add('FN' + fname)
        allowed.add('FN_' + fname)
        for match in re.finditer(r'\bLOCAL\b\s*([^\n:]+)', text, re.IGNORECASE):
            for token in match.group(1).split(','):
                raw = token.strip().split('(')[0].strip()
                if not raw:
                    continue
                norm = self._normalize_identifier(raw)
                allowed.add(norm.upper())
                allowed.add(norm.upper().rstrip('%$!#'))
        called: Set[str] = set()
        for match in _RE_FN_CALL.finditer(text):
            callee = self._normalize_identifier(match.group(1))
            called.add(callee)
            allowed.add(callee.upper())
            allowed.add(('FN' + callee).upper())
        for match in ident_re.finditer(text):
            raw = (match.group(1) + (match.group(2) or '')).upper()
            base = match.group(1).upper()
            if raw in _FN_MEMO_IMPURE or base in _FN_MEMO_IMPURE:
                return False, set()
            if raw.startswith('FN') and len(raw) > 2:
                continue
            if raw in allowed or base in allowed:
                continue
            return False, set()
        return True, called

    def _fn_assign_matches(self, fn: UserFunction, var: str) -> bool:
        token = self._normalize_identifier(var.strip().rstrip('%$!#'))
        fname = str(fn.name)
        low = token.lower()
        return low in (fname.lower(), 'fn' + fname.lower(), 'fn_' + fname.lower())

    def _fn_stmt_return_expr(self, fn: UserFunction, text: str) -> Optional[str]:
        stripped = text.strip()
        if not stripped:
            return None
        if stripped.startswith('='):
            return stripped[1:].strip() or None
        if '=' not in stripped:
            return None
        try:
            var, op, expr = self._parse_assignment_statement(stripped)
        except ValueError:
            return None
        if op != '=' or not self._fn_assign_matches(fn, var):
            return None
        return expr

    def _compile_fn_memo_steps(self, fn: UserFunction) -> Optional[list]:
        """Straight-line IF/return bodies compiled to a tiny AST. None → slow path."""
        if not fn.multiline:
            body = (fn.body or '').strip()
            if not body:
                return None
            ast = self._fn_memo_parse(body)
            return None if ast is None else [('ret', ast)]
        texts: List[str] = []
        for line_num in sorted(self.program):
            if not (fn.body_start <= line_num < fn.body_end):
                continue
            parts = self._run_stmts.get(line_num)
            if parts is None:
                parts = self._parse_line_statements(self.program[line_num])
            for _, text in parts:
                cmd, rest = self._parse_command(text)
                if cmd in ('END', 'REM') or not text.strip():
                    continue
                texts.append(text)

        def is_exit(stmt: str) -> bool:
            scmd, srest = self._parse_command(stmt)
            return scmd == 'END' or (scmd == 'EXIT' and srest.strip().upper() == 'FUNCTION')

        def return_expr(stmts: List[str], index: int) -> Optional[str]:
            """Expr if stmts[index] ends the call: ``= e``, or ``FNx = e`` then exit/end."""
            stmt = stmts[index]
            expr = self._fn_stmt_return_expr(fn, stmt)
            if expr is None or stmt.strip().startswith('='):
                return expr
            # FNx = e only sets the result; later statements may still change it.
            if index + 1 == len(stmts) or is_exit(stmts[index + 1]):
                return expr
            return None

        steps: list = []
        for index, text in enumerate(texts):
            cmd, rest = self._parse_command(text)
            if cmd == 'IF':
                try:
                    then_part, else_part = self._split_if_else_parts(rest)
                except ValueError:
                    return None
                if else_part:
                    return None
                cond, then_code = self._split_bbc_compact_if_then(then_part)
                then_stmts = [
                    piece.strip()
                    for piece in then_code.split(':')
                    if piece.strip()
                ]
                if not then_stmts or is_exit(then_stmts[0]):
                    return None
                ret_expr = return_expr(then_stmts, 0)
                if ret_expr is None or not all(is_exit(t) for t in then_stmts[1:]):
                    return None
                if (
                    len(then_stmts) == 1
                    and not then_stmts[0].startswith('=')
                    and index + 1 < len(texts)
                ):
                    # IF c THEN FNx = e with more body after it: not a return.
                    return None
                cond_ast = self._fn_memo_parse(cond)
                expr_ast = self._fn_memo_parse(ret_expr)
                if cond_ast is None or expr_ast is None:
                    return None
                steps.append(('if_ret', cond_ast, expr_ast))
                continue
            if is_exit(text):
                continue
            expr = return_expr(texts, index)
            if expr is None:
                return None
            expr_ast = self._fn_memo_parse(expr)
            if expr_ast is None:
                return None
            steps.append(('ret', expr_ast))
        return steps or None

    def _fn_memo_tokenize(self, text: str) -> Optional[list]:
        tokens: list = []
        i = 0
        n = len(text)
        while i < n:
            ch = text[i]
            if ch.isspace():
                i += 1
                continue
            if ch in '+-*/(),':
                tokens.append(ch)
                i += 1
                continue
            two = text[i:i + 2]
            if two in ('<=', '>=', '<>'):
                tokens.append(two)
                i += 2
                continue
            if ch in '<>=':
                tokens.append(ch)
                i += 1
                continue
            if ch == '"':
                j = i + 1
                while j < n and text[j] != '"':
                    j += 1
                if j >= n:
                    return None
                tokens.append(('str', text[i + 1:j]))
                i = j + 1
                continue
            if ch.isdigit() or (ch == '.' and i + 1 < n and text[i + 1].isdigit()):
                j = i
                while j < n and (text[j].isdigit() or text[j] == '.'):
                    j += 1
                raw = text[i:j]
                tokens.append(('num', float(raw) if '.' in raw else int(raw)))
                i = j
                continue
            if ch.isalpha() or ch == '_':
                j = i
                while j < n and (text[j].isalnum() or text[j] in '_%$!'):
                    j += 1
                tokens.append(('id', text[i:j]))
                i = j
                continue
            return None
        return tokens

    def _fn_memo_parse(self, text: str) -> Optional[tuple]:
        tokens = self._fn_memo_tokenize(text)
        if tokens is None:
            return None
        state = {'i': 0}

        def peek():
            i = state['i']
            return tokens[i] if i < len(tokens) else None

        def eat(expected=None):
            tok = peek()
            if expected is not None and tok != expected:
                return None
            if tok is None:
                return None
            state['i'] += 1
            return tok

        def parse_cmp():
            left = parse_add()
            if left is None:
                return None
            tok = peek()
            if tok in ('=', '<>', '<', '>', '<=', '>='):
                eat()
                right = parse_add()
                if right is None:
                    return None
                return ('cmp', tok, left, right)
            return left

        def parse_add():
            left = parse_mul()
            if left is None:
                return None
            while peek() in ('+', '-'):
                op = eat()
                right = parse_mul()
                if right is None:
                    return None
                left = ('add' if op == '+' else 'sub', left, right)
            return left

        def parse_mul():
            left = parse_unary()
            if left is None:
                return None
            while peek() in ('*', '/'):
                op = eat()
                right = parse_unary()
                if right is None:
                    return None
                left = ('mul' if op == '*' else 'div', left, right)
            return left

        def parse_unary():
            if peek() == '-':
                eat()
                inner = parse_unary()
                if inner is None:
                    return None
                return ('neg', inner)
            if peek() == '+':
                eat()
                return parse_unary()
            return parse_atom()

        def parse_atom():
            tok = peek()
            if tok is None:
                return None
            if isinstance(tok, tuple) and tok[0] in ('num', 'str'):
                eat()
                return ('const', tok[1])
            if tok == '(':
                eat()
                inner = parse_cmp()
                if inner is None or eat(')') is None:
                    return None
                return inner
            if isinstance(tok, tuple) and tok[0] == 'id':
                eat()
                name = tok[1]
                if peek() == '(':
                    eat()
                    args: list = []
                    if peek() != ')':
                        while True:
                            arg = parse_cmp()
                            if arg is None:
                                return None
                            args.append(arg)
                            if peek() == ',':
                                eat()
                                continue
                            break
                    if eat(')') is None:
                        return None
                    raw = name
                    if raw[:2].upper() == 'FN':
                        raw = raw[2:].lstrip('_')
                    callee_fn = self._lookup_user_function(raw)
                    if callee_fn is None:
                        return None
                    return ('call', callee_fn.name, tuple(args))
                pname, _kind = self._parse_var_token(name)
                return ('param', pname)
            return None

        tree = parse_cmp()
        if tree is None or peek() is not None:
            return None
        return tree


_FN_MEMO_KEYWORDS = frozenset({
    'IF', 'THEN', 'ELSE', 'ELSEIF', 'ELIF', 'ENDIF',
    'FOR', 'TO', 'STEP', 'NEXT', 'WHILE', 'WEND',
    'REPEAT', 'UNTIL', 'CASE', 'WHEN', 'OTHERWISE', 'ENDCASE',
    'END', 'DEF', 'FN', 'EXIT', 'FUNCTION', 'LOCAL',
    'AND', 'OR', 'NOT', 'XOR', 'EOR', 'EQV', 'IMP', 'MOD', 'DIV',
    'TRUE', 'FALSE', 'LET', 'REM',
})
_FN_MEMO_PURE_BUILTINS = frozenset({
    'ABS', 'INT', 'FIX', 'SGN', 'SQR', 'SQRT', 'SIN', 'COS', 'TAN',
    'ASN', 'ASIN', 'ACS', 'ACOS', 'ATN', 'ATAN', 'SINRAD', 'COSRAD', 'TANRAD',
    'DEG', 'RAD', 'LOG', 'EXP', 'PI', 'LEN', 'VAL', 'ASC',
    'CHR', 'STR', 'LEFT', 'RIGHT', 'MID', 'INSTR', 'STRING', 'SPACE',
    'HEX', 'OCT', 'BIN', 'UCASE', 'LCASE', 'CINT', 'CSNG', 'CDBL',
    'SNG', 'DBL', 'FLOAT', 'NEAR', 'NEARSIG',
    'CHR$', 'STR$', 'LEFT$', 'RIGHT$', 'MID$', 'STRING$', 'SPACE$',
    'HEX$', 'OCT$', 'BIN$', 'UCASE$', 'LCASE$',
})
_FN_MEMO_IMPURE = frozenset({
    'RND', 'TIME', 'TIMER', 'GET', 'INKEY', 'INKEY$', 'GET$',
    'POS', 'VPOS', 'POINT', 'TINT', 'ADVAL', 'MOUSE',
    'ERR', 'ERL', 'LOC', 'LOF', 'EOF', 'PTR', 'EXT', 'ARG', 'ARG$',
    'INPUT', 'PRINT', 'READ', 'DATA', 'RESTORE',
    'PLOT', 'DRAW', 'MOVE', 'CIRCLE', 'RECTANGLE', 'LINE', 'MODE',
    'COLOUR', 'COLOR', 'GCOL', 'CLS', 'CLG', 'VDU', 'SYS', 'OSCLI',
    'SOUND', 'BEEP', 'WAIT', 'CALL', 'PROC', 'ENDPROC',
    'OPENIN', 'OPENOUT', 'OPENUP', 'OPEN', 'CLOSE', 'BGET', 'BPUT',
    'CHAIN', 'RUN', 'LOAD', 'SAVE',
    'FG$', 'BG$', 'RGB$', 'BGRGB$', 'ANSI$', 'RESET$',
})

