"""BASICInterpreter mixin: defs.

DEF FN / DEF PROC, LOCAL, and user callables.

Auto-generated by tools/split_runtime_mixins.py — do not hand-edit bulk.
"""
# ruff: noqa: F401,F403,F405,E402,W291,W293
# Imports mirrored from monorepo runtime for method bodies.
import fnmatch
import json
import math
import random
import re
import os
import struct
import sys
import time

from ..config import DEFAULT_CONFIG, InterpreterConfig, SYSTEM_VAR_SPEC
from ..dialect_hint import DialectHint, parse_comment_dialect_line, split_dialect_hints
from ..constants import (
    CLI_EXIT_WORDS as _CLI_EXIT_WORDS,
    EXIT_HOLD_CONSOLE,
    EXPR_RESERVED_WORDS as _EXPR_RESERVED_WORDS,
    NUMERIC_BUILTIN_FUNCS as _NUMERIC_BUILTIN_FUNCS,
    NUMERIC_BUILTIN_FUNC_RE as _NUMERIC_BUILTIN_FUNC_RE,
    SAFE_EVAL_GLOBALS as _SAFE_EVAL_GLOBALS,
)
from ..expr.compile import CompiledExpr, int_slot
from ..expr.patterns import (
    RE_ARRAY_HEAD as _RE_ARRAY_HEAD,
    RE_COND_EQ as _RE_COND_EQ,
    RE_COND_NE as _RE_COND_NE,
    RE_DYNAMIC_CALL_REMAINS as _RE_DYNAMIC_CALL_REMAINS,
    RE_FILE_FUNC as _RE_FILE_FUNC,
    RE_FILE_FUNC_BBC as _RE_FILE_FUNC_BBC,
    RE_FN_CALL as _RE_FN_CALL,
    RE_FUNC_CALL as _RE_FUNC_CALL,
    RE_HAS_LETTER as _RE_HAS_LETTER,
    RE_INKEY_CALL as _RE_INKEY_CALL,
    RE_INT_DIV as _RE_INT_DIV,
    RE_MOD as _RE_MOD,
    RE_NUMERIC_FUNC_CALL as _RE_NUMERIC_FUNC_CALL,
    RE_TIME as _RE_TIME,
    RE_VAR_BASE_FULL as _RE_VAR_BASE_FULL,
    PROC_FN_NAME_PATTERN as _PROC_FN_NAME_PATTERN,
    VAR_BASE_PATTERN as _VAR_BASE_PATTERN,
)

from ..format import UsingFormatter
from ..format.save_case import (
    Fold as _SaveFold,
    fold_from_save_case as _fold_from_save_case,
    format_program_line as _format_program_line_save_case,
    format_statement_part as _format_statement_part_save_case,
)
from ..repl.completion import configure_readline as _configure_repl_readline
from ..repl.help_browser import run_help_browser as _run_help_browser
from ..util import (
    basic_truth as _basic_truth,
    hard_exit as _hard_exit,
    near_equal as _near_equal,
    near_equal_sig as _near_equal_sig,
    probe_float_platform as _probe_float_platform,
)
from ..type_system import (
    ArrayStorage,
    BasicRuntimeError,
    ChainTransfer,
    DataItem,
    Dialect,
    FieldBuffer,
    FileChannel,
    FnReturn,
    CaseBlockLayout,
    CaseFrame,
    IfBlockLayout,
    IfFrame,
    ListCommand,
    LoopFrame,
    ProcReturn,
    ProgramExit,
    UserFunction,
    UserProcedure,
    VarKind,
)
from typing import Callable, Dict, List, Optional, Set, TextIO, Tuple

_SYSTEM_VAR_SPEC = SYSTEM_VAR_SPEC

       
# BBC Micro MODE specs (text grid, graphics resolution, PAR) — see bbc_modes.py.
from mini_basic.bbc_modes import bbc_mode_spec

from .helpers import (
    _get_readline_module,
    _windows_arrow_action,
    _windows_apply_arrow,
    _windows_editing_input,
    _prompt_editing_input,
    _parse_path_arg,
    _apply_pygame_display_defaults,
)

class RuntimeDefsMixin:
    """Mixin providing defs-related BASICInterpreter methods."""

    def _parse_def_fn_header(self, rest: str) -> UserFunction:
        match = re.match(
            rf'^FN_?\s*{_PROC_FN_NAME_PATTERN}(%|\$)?\s*\((.*)\)\s*$',
            rest.strip(),
            flags=re.IGNORECASE,
        )
        if not match:
            raise ValueError('invalid DEF FN header')
        name = self._normalize_identifier(match.group(1))
        return_suffix = match.group(2)
        return_kind: VarKind = 'float'
        if return_suffix == '$':
            return_kind = 'str'
        elif return_suffix == '%':
            return_kind = 'int'
        params: List[Tuple[str, VarKind]] = []
        array_params: List[str] = []
        params_text = match.group(3).strip()
        if params_text:
            for token in self._split_args(params_text):
                param_name, param_kind, is_array = self._parse_param_token(token)
                params.append((param_name, param_kind))
                if is_array:
                    array_params.append(param_name)
        return UserFunction(
            name=name,
            return_kind=return_kind,
            params=tuple(params),
            array_params=tuple(array_params),
        )

    def _def_fn_header_return_suffix(self, header_rest: str) -> Optional[str]:
        match = re.match(
            rf'^FN_?\s*{_PROC_FN_NAME_PATTERN}(%|\$)?\s*\(',
            header_rest.strip(),
            flags=re.IGNORECASE,
        )
        if not match:
            return None
        return match.group(2)

    def _warn_def_fn_missing_returns(self) -> None:
        for fn in self.user_functions.values():
            if not fn.multiline:
                continue
            candidates = self._collect_fn_body_return_candidates(
                fn.body_start,
                fn.body_end,
                self._run_line_nums,
            )
            if candidates:
                continue
            print(
                f'? Line {fn.body_start}: DEF FN body needs =return '
                f'(e.g. THEN = 1)'
            )

    def _parse_def_fn_rest(self, rest: str) -> UserFunction:
        match = re.match(
            rf'^FN_?\s*{_PROC_FN_NAME_PATTERN}(%|\$)?\s*\((.*)\)\s*=\s*(.+)$',
            rest.strip(),
            flags=re.IGNORECASE,
        )
        if not match:
            raise ValueError('invalid DEF FN syntax')
        fn = self._parse_def_fn_header(
            f"FN{match.group(1)}{match.group(2) or ''}({match.group(3)})"
        )
        body = match.group(4).strip()
        if not body:
            raise ValueError('empty DEF FN body')
        fn.body = body
        self._maybe_infer_fn_return_kind(
            fn,
            f"FN{match.group(1)}{match.group(2) or ''}({match.group(3)})",
            body,
        )
        return fn

    def _register_def_fn(self, rest: str) -> None:
        fn = self._parse_def_fn_rest(rest)
        self.user_functions[fn.name] = fn

    def _lookup_user_function(self, name: str):
        """Find DEF FN by stored name; fold case if the exact key is missing.

        BBC listings keep ``DEF FNstrip`` under ``strip`` when identifiers are
        case-sensitive. Calls and tests may still write ``FNSTRIP`` / ``STRIP``.
        """
        key = self._normalize_identifier(name)
        fn = self.user_functions.get(key)
        if fn is not None:
            return fn
        folded = key.lower()
        for stored, candidate in self.user_functions.items():
            if stored.lower() == folded:
                return candidate
        return None

    def _is_def_fn_or_proc_header(self, cmd: str, rest: str) -> bool:
        if cmd != 'DEF':
            return False
        rest_strip = rest.strip()
        try:
            self._parse_def_proc_header(rest_strip)
            return True
        except ValueError:
            pass
        if re.search(r'\)\s*=', rest_strip):
            return False
        try:
            self._parse_def_fn_header(rest_strip)
            return True
        except ValueError:
            return False

    def _parse_def_proc_header(self, rest: str) -> UserProcedure:
        """Parse ``PROC name(params)`` optionally followed by same-line body.

        BBCSDL hanoi style::

            DEF PROCHANOI(A,B,C,D) IF A=0 ENDPROC
            PROCHANOI(A-1,...)
            ENDPROC
        """
        text = rest.strip()
        # Allow trailing body after the closing ')' or bare name.
        # Use PROC_FN_NAME_PATTERN (includes numeric PROC4); not letter-only.
        match = re.match(
            rf'^PROC_?\s*{_PROC_FN_NAME_PATTERN}\s*(?:\((.*)\))?\s*(.*)$',
            text,
            re.IGNORECASE,
        )
        if not match:
            raise ValueError('invalid DEF PROC header')
        name = self._normalize_identifier(match.group(1))
        params: List[Tuple[str, VarKind]] = []
        array_params: List[str] = []
        return_params: List[str] = []
        params_text = (match.group(2) or '').strip()
        if params_text:
            for token in self._split_args(params_text):
                raw = token.strip()
                is_return = False
                ret_m = re.match(r'^RETURN\s+(.+)$', raw, re.IGNORECASE)
                if ret_m:
                    is_return = True
                    raw = ret_m.group(1).strip()
                param_name, param_kind, is_array = self._parse_param_token(raw)
                params.append((param_name, param_kind))
                if is_array:
                    array_params.append(param_name)
                if is_return:
                    return_params.append(param_name)
        header_stmt = (match.group(3) or '').strip()
        return UserProcedure(
            name=name,
            params=tuple(params),
            array_params=tuple(array_params),
            return_params=tuple(return_params),
            header_stmt=header_stmt,
        )

    def _call_procedure(self, proc: UserProcedure, args: List[str]) -> None:
        if len(args) != len(proc.params):
            raise ValueError('wrong number of arguments')
        bindings: List[Tuple[str, VarKind, object]] = []
        array_aliases: Dict[Tuple[str, VarKind], Tuple[str, VarKind]] = {}
        array_param_set = set(proc.array_params)
        return_param_set = set(getattr(proc, 'return_params', ()) or ())
        return_targets: List[Tuple[str, VarKind, str]] = []
        for (param_name, param_kind), arg_expr in zip(proc.params, args):
            if param_name in array_param_set:
                actual_base, actual_kind = self._parse_array_ref(arg_expr.strip())
                if actual_kind != param_kind:
                    raise ValueError('array parameter type mismatch')
                array_aliases[(param_name, param_kind)] = (actual_base, actual_kind)
                continue
            if param_kind == 'str':
                bindings.append((param_name, param_kind, self._eval_string_expr(arg_expr)))
            elif param_kind == 'int':
                bindings.append((
                    param_name,
                    param_kind,
                    self._coerce_int_storage(self._eval_numeric(arg_expr)),
                ))
            else:
                bindings.append((param_name, param_kind, self._eval_numeric(arg_expr)))
            if param_name in return_param_set:
                return_targets.append((param_name, param_kind, arg_expr.strip()))
        saved = self._apply_fn_param_bindings(bindings)
        saved_array_aliases = dict(self._array_aliases)
        self._array_aliases.update(array_aliases)
        self.proc_stack.append(saved)
        try:
            # Same-line prefix on DEF PROC line (e.g. IF A=0 ENDPROC) runs first.
            header = (getattr(proc, 'header_stmt', None) or '').strip()
            if header:
                line_nums = sorted(self.program.keys()) or [0]
                def_line = proc.body_start or 0
                if (
                    proc.body_start
                    and proc.body_end
                    and proc.body_start <= proc.body_end
                    and line_nums
                ):
                    try:
                        bi = line_nums.index(proc.body_start)
                        # Multi-line: body_start is first line *after* DEF.
                        if proc.body_start != proc.body_end or bi > 0:
                            def_line = (
                                line_nums[bi - 1]
                                if bi > 0 and proc.body_start != proc.body_end
                                else proc.body_start
                            )
                    except ValueError:
                        def_line = proc.body_start
                self._execute_inline_statements(header, def_line, line_nums)
                # Pure single-line DEF PROC … ENDPROC: no multi-line body.
                if proc.body_start == proc.body_end and re.search(
                    r'\bENDPROC\b', header, re.IGNORECASE
                ):
                    return
            self._run_procedure_body(proc)
        except ProcReturn:
            pass
        except BasicRuntimeError:
            # Let outer error trap / RESUME handling deal with it (e.g. trap was set
            # outside the PROC). Do not turn it into a generic PROC error.
            raise
        finally:
            outgoing: List[Tuple[str, VarKind, object]] = []
            for param_name, param_kind, dest_expr in return_targets:
                if param_kind == 'str':
                    value = self.str_variables.get(param_name, '')
                elif param_kind == 'int':
                    value = self.int_variables.get(param_name, 0)
                else:
                    value = self.variables.get(param_name, 0.0)
                outgoing.append((dest_expr, param_kind, value))
            saved_outer = self.proc_stack.pop()
            self._restore_fn_param_bindings(saved_outer)
            self._array_aliases = saved_array_aliases
            for dest_expr, param_kind, value in outgoing:
                try:
                    self._assign_input_value(
                        dest_expr,
                        value if param_kind == 'str' else str(value),
                    )
                except Exception:
                    loc = self._read_lvalue(dest_expr)
                    self._write_lvalue(loc, value)

    def _collect_def_layout(
        self,
        line_nums: List[int],
    ) -> Tuple[Set[int], Set[int], Set[int]]:
        headers: Set[int] = set()
        bodies: Set[int] = set()
        ends: Set[int] = set()
        idx = 0
        while idx < len(line_nums):
            line_num = line_nums[idx]
            stmt_parts = self._run_stmts.get(line_num)
            if stmt_parts is None:
                stmt_parts = self._parse_line_statements(self.program[line_num])
            handled = False
            for _, text in stmt_parts:
                cmd, rest = self._parse_command(text)
                if cmd != 'DEF':
                    continue
                if self._RE_DEF_PROC.match(rest.strip()):
                    end_line = self._find_matching_endproc(line_num, line_nums)
                    if end_line is not None and idx + 1 < len(line_nums):
                        headers.add(line_num)
                        ends.add(end_line)
                        end_idx = self._line_index(end_line, line_nums)
                        for body_idx in range(idx + 1, end_idx):
                            bodies.add(line_nums[body_idx])
                        idx = end_idx
                        handled = True
                    break
                if re.search(r'\)\s*=', rest):
                    break
                try:
                    self._parse_def_fn_header(rest)
                except ValueError:
                    break
                end_line = self._find_matching_end_def(line_num, line_nums)
                if end_line is None:
                    equals_return = self._find_def_fn_equals_return(line_num, line_nums)
                    if equals_return is not None:
                        equals_line, _ = equals_return
                        headers.add(line_num)
                        bodies.add(equals_line)
                        end_idx = self._line_index(equals_line, line_nums)
                        idx = end_idx
                        handled = True
                    break
                if idx + 1 >= len(line_nums):
                    break
                headers.add(line_num)
                ends.add(end_line)
                end_idx = self._line_index(end_line, line_nums)
                for body_idx in range(idx + 1, end_idx):
                    bodies.add(line_nums[body_idx])
                idx = end_idx
                handled = True
                break
            if not handled:
                idx += 1
        return headers, bodies, ends

