"""BASICInterpreter mixin: dialect.

Dialect detection and compatibility helpers.

Auto-generated by tools/split_runtime_mixins.py — do not hand-edit bulk.
"""
# ruff: noqa: F401,F403,F405,E402,W291,W293
# Imports mirrored from monorepo runtime for method bodies.
import fnmatch
import json
import math
import random
import re
import os
import struct
import sys
import time

from ..config import DEFAULT_CONFIG, InterpreterConfig, SYSTEM_VAR_SPEC
from ..dialect_hint import DialectHint, parse_comment_dialect_line, split_dialect_hints
from ..constants import (
    CLI_EXIT_WORDS as _CLI_EXIT_WORDS,
    EXIT_HOLD_CONSOLE,
    EXPR_RESERVED_WORDS as _EXPR_RESERVED_WORDS,
    NUMERIC_BUILTIN_FUNCS as _NUMERIC_BUILTIN_FUNCS,
    NUMERIC_BUILTIN_FUNC_RE as _NUMERIC_BUILTIN_FUNC_RE,
    SAFE_EVAL_GLOBALS as _SAFE_EVAL_GLOBALS,
)
from ..expr.compile import CompiledExpr, int_slot
from ..expr.patterns import (
    RE_ARRAY_HEAD as _RE_ARRAY_HEAD,
    RE_COND_EQ as _RE_COND_EQ,
    RE_COND_NE as _RE_COND_NE,
    RE_DYNAMIC_CALL_REMAINS as _RE_DYNAMIC_CALL_REMAINS,
    RE_FILE_FUNC as _RE_FILE_FUNC,
    RE_FILE_FUNC_BBC as _RE_FILE_FUNC_BBC,
    RE_FN_CALL as _RE_FN_CALL,
    RE_FUNC_CALL as _RE_FUNC_CALL,
    RE_HAS_LETTER as _RE_HAS_LETTER,
    RE_INKEY_CALL as _RE_INKEY_CALL,
    RE_INT_DIV as _RE_INT_DIV,
    RE_MOD as _RE_MOD,
    RE_NUMERIC_FUNC_CALL as _RE_NUMERIC_FUNC_CALL,
    RE_TIME as _RE_TIME,
    RE_VAR_BASE_FULL as _RE_VAR_BASE_FULL,
    VAR_BASE_PATTERN as _VAR_BASE_PATTERN,
)

from ..format import UsingFormatter
from ..format.save_case import (
    Fold as _SaveFold,
    fold_from_save_case as _fold_from_save_case,
    format_program_line as _format_program_line_save_case,
    format_statement_part as _format_statement_part_save_case,
)
from ..repl.completion import configure_readline as _configure_repl_readline
from ..repl.help_browser import run_help_browser as _run_help_browser
from ..util import (
    basic_truth as _basic_truth,
    hard_exit as _hard_exit,
    near_equal as _near_equal,
    near_equal_sig as _near_equal_sig,
    probe_float_platform as _probe_float_platform,
)
from ..type_system import (
    ArrayStorage,
    BasicRuntimeError,
    ChainTransfer,
    DataItem,
    Dialect,
    FieldBuffer,
    FileChannel,
    FnReturn,
    CaseBlockLayout,
    CaseFrame,
    IfBlockLayout,
    IfFrame,
    ListCommand,
    LoopFrame,
    ProcReturn,
    ProgramExit,
    UserFunction,
    UserProcedure,
    VarKind,
)
from typing import Callable, Dict, List, Optional, Set, TextIO, Tuple

_SYSTEM_VAR_SPEC = SYSTEM_VAR_SPEC

       
# BBC Micro MODE specs (text grid, graphics resolution, PAR) — see bbc_modes.py.
from mini_basic.bbc_modes import bbc_mode_spec

from .helpers import (
    _get_readline_module,
    _windows_arrow_action,
    _windows_apply_arrow,
    _windows_editing_input,
    _prompt_editing_input,
    _parse_path_arg,
    _apply_pygame_display_defaults,
)

class RuntimeDialectMixin:
    """Mixin providing dialect-related BASICInterpreter methods."""

    def _dialect_allows(self, feature: str) -> bool:
        dialect = self.config.dialect
        if dialect == 'mini':
            return True
        if feature == 'if_goto':
            return dialect in self._IF_GOTO_DIALECTS
        if feature == 'if_then_line':
            return dialect in self._IF_THEN_LINE_DIALECTS
        if feature == 'multiline_def':
            return dialect not in self._NUMBERED_GOTO_DIALECTS
        if feature == 'numbered_program':
            return True
        if feature == 'unnumbered_program':
            return dialect not in self._NUMBERED_GOTO_DIALECTS
        if feature in self._MINI_ONLY_FUNCS or feature == 'mini_only_func':
            return dialect == 'mini'
        if feature.upper() in self._MINI_ONLY_CMDS:
            return dialect == 'mini'
        if feature in self._MITS_FORBIDDEN_CMDS:
            return dialect not in self._NUMBERED_GOTO_DIALECTS
        return True

    def _dialect_status_line(self) -> str:
        """Single status line for bare DIALECT and set_dialect announcements."""
        strict_label = 'on' if self.config.strict_dialect else 'off'
        return (
            f'Dialect: {self.config.dialect}  strict: {strict_label}  '
            f'case: {self._case_sensitivity_label()}'
        )

    def set_dialect(
        self,
        dialect: Dialect,
        *,
        strict: Optional[bool] = None,
        announce: bool = True,
    ) -> bool:
        if dialect == self.config.dialect and strict is None:
            if announce:
                print(self._dialect_status_line())
            return True
        old_case = self._identifiers_case_sensitive()
        if self.program and not self._validate_dialect_for_loaded_program(dialect):
            if announce:
                self._emit_error('? DIALECT error')
            return False
        self.config.dialect = dialect
        if strict is not None:
            self.config.strict_dialect = strict
        new_case = self._identifiers_case_sensitive()
        if old_case != new_case and self.program:
            self._clear_runtime_variables()
            if announce:
                print('Note: case mode changed — variable values cleared')
        self._definitions_dirty = True
        self._invalidate_program_caches()
        self._invalidate_run_prepare_caches()
        if announce:
            print(self._dialect_status_line())
        return True

    def _hint_def_fn_close_keyword(self, def_line: int, line_nums: List[int]) -> None:
        start_idx = self._line_index(def_line, line_nums)
        for line_num in line_nums[start_idx + 1:]:
            stmt_parts = self._run_stmts.get(line_num)
            if stmt_parts is None:
                stmt_parts = self._parse_line_statements(self.program[line_num])
            for _, text in stmt_parts:
                cmd, rest = self._parse_command(text)
                if cmd != 'END':
                    continue
                key = rest.strip().upper()
                if key == 'DEF':
                    return
                if key in self._END_KEYWORD_HINTS:
                    print(
                        f'? Line {line_num}: use {self._END_KEYWORD_HINTS[key]}, '
                        f'not END {rest.strip()}'
                    )
                    return
        self._emit_error(f'? Line {def_line}: multiline DEF FN needs a body ending with END DEF')

    def _auto_entry_loop(self, line_num: int, step: int) -> None:
        while True:
            try:
                default = self.program.get(line_num, '')
                # Call via helpers module so tests can patch helpers._prompt_editing_input.
                from . import helpers as _helpers
                text = _helpers._prompt_editing_input(f'{line_num} ', default)
            except (KeyboardInterrupt, EOFError):
                print()
                break
            if not text:
                break
            stored_num, statement = self._parse_auto_line(line_num, text)
            indent, statement = self._preserve_or_parse_indent(
                stored_num,
                statement,
                fallback_line=line_num,
            )
            self.set_program_line(stored_num, statement, indent)
            line_num = stored_num + step

