"""BASICInterpreter mixin: graphics.

Display, MODE/VDU/graphics, INKEY, sound, OSCLI.

Auto-generated by tools/split_runtime_mixins.py — do not hand-edit bulk.
"""
# ruff: noqa: F401,F403,F405,E402,W291,W293
# Imports mirrored from monorepo runtime for method bodies.
import fnmatch
import json
import math
import random
import re
import os
import struct
import sys
import time

from ..config import DEFAULT_CONFIG, InterpreterConfig, SYSTEM_VAR_SPEC
from ..dialect_hint import DialectHint, parse_comment_dialect_line, split_dialect_hints
from ..constants import (
    CLI_EXIT_WORDS as _CLI_EXIT_WORDS,
    EXIT_HOLD_CONSOLE,
    EXPR_RESERVED_WORDS as _EXPR_RESERVED_WORDS,
    NUMERIC_BUILTIN_FUNCS as _NUMERIC_BUILTIN_FUNCS,
    NUMERIC_BUILTIN_FUNC_RE as _NUMERIC_BUILTIN_FUNC_RE,
    SAFE_EVAL_GLOBALS as _SAFE_EVAL_GLOBALS,
)
from ..expr.compile import CompiledExpr, int_slot
from ..expr.patterns import (
    RE_ARRAY_HEAD as _RE_ARRAY_HEAD,
    RE_COND_EQ as _RE_COND_EQ,
    RE_COND_NE as _RE_COND_NE,
    RE_DYNAMIC_CALL_REMAINS as _RE_DYNAMIC_CALL_REMAINS,
    RE_FILE_FUNC as _RE_FILE_FUNC,
    RE_FILE_FUNC_BBC as _RE_FILE_FUNC_BBC,
    RE_FN_CALL as _RE_FN_CALL,
    RE_FUNC_CALL as _RE_FUNC_CALL,
    RE_HAS_LETTER as _RE_HAS_LETTER,
    RE_INKEY_CALL as _RE_INKEY_CALL,
    RE_INT_DIV as _RE_INT_DIV,
    RE_MOD as _RE_MOD,
    RE_NUMERIC_FUNC_CALL as _RE_NUMERIC_FUNC_CALL,
    RE_TIME as _RE_TIME,
    RE_VAR_BASE_FULL as _RE_VAR_BASE_FULL,
    VAR_BASE_PATTERN as _VAR_BASE_PATTERN,
)

from ..format import UsingFormatter
from ..format.save_case import (
    Fold as _SaveFold,
    fold_from_save_case as _fold_from_save_case,
    format_program_line as _format_program_line_save_case,
    format_statement_part as _format_statement_part_save_case,
)
from ..repl.completion import configure_readline as _configure_repl_readline
from ..repl.help_browser import run_help_browser as _run_help_browser
from ..util import (
    basic_truth as _basic_truth,
    hard_exit as _hard_exit,
    near_equal as _near_equal,
    near_equal_sig as _near_equal_sig,
    probe_float_platform as _probe_float_platform,
)
from ..type_system import (
    ArrayStorage,
    BasicRuntimeError,
    ChainTransfer,
    DataItem,
    Dialect,
    FieldBuffer,
    FileChannel,
    FnReturn,
    CaseBlockLayout,
    CaseFrame,
    IfBlockLayout,
    IfFrame,
    ListCommand,
    LoopFrame,
    ProcReturn,
    ProgramExit,
    UserFunction,
    UserProcedure,
    VarKind,
)
from typing import Callable, Dict, List, Optional, Set, TextIO, Tuple

_SYSTEM_VAR_SPEC = SYSTEM_VAR_SPEC

       
# BBC Micro MODE specs (text grid, graphics resolution, PAR) — see bbc_modes.py.
from mini_basic.bbc_modes import bbc_mode_spec

from .helpers import (
    _get_readline_module,
    _windows_arrow_action,
    _windows_apply_arrow,
    _windows_editing_input,
    _prompt_editing_input,
    _parse_path_arg,
    _apply_pygame_display_defaults,
)

class RuntimeGraphicsMixin:
    """Mixin providing graphics-related BASICInterpreter methods."""

    def _present_input_display(self) -> None:
        if not self._display_enabled():
            return
        self._display.present()
        self._last_present_time = time.monotonic()

    def _tee_echo_input_char_to_display(self, ch: str) -> None:
        if not ch or not self._display_enabled():
            return
        self._display.write(ch)
        self._present_input_display()

    def _tee_backspace_input_on_display(self) -> None:
        if not self._display_enabled():
            return
        backspace = getattr(self._display, 'backspace_input_char', None)
        if callable(backspace):
            backspace()
            self._present_input_display()

    def _tee_newline_on_display(self) -> None:
        if not self._display_enabled():
            return
        self._display.newline()
        self._present_input_display()

    def _pump_display_for_input(self) -> None:
        if not self._display_enabled():
            return
        if hasattr(self._display, 'pump_events'):
            self._display.pump_events()
        if not self._display.poll():
            self._invoke_on_close_and_exit()

    def _display_is_alive(self) -> bool:
        """True if the backend still has a usable surface."""
        disp = self._display
        if disp is None:
            return False
        if hasattr(disp, 'is_open'):
            return bool(disp.is_open)
        return True

    def _mark_display_closed(self) -> None:
        """Tear down a user-closed window; allow later RUN/MODE to reopen."""
        disp = self._display
        if disp is not None:
            try:
                mark = getattr(disp, 'mark_closed', None)
                if callable(mark):
                    mark()
                else:
                    disp.end_run()
            except Exception:
                try:
                    disp.end_run()
                except Exception:
                    pass
        self._display_live = False

    def _invoke_on_close_and_exit(self) -> None:
        """Run ``ON CLOSE`` handler (if any), then stop the program.

        BBCSDL: ``ON CLOSE PROC cleanup : QUIT`` — cleanup then exit when the
        window is closed. Handler is cleared first to avoid re-entrancy.
        Surfaces are torn down so the next RUN/MODE can open a new window.
        """
        self._mark_display_closed()
        handler = getattr(self, '_on_close_handler', None)
        self._on_close_handler = None
        self.on_close_action = None
        if handler and not getattr(self, '_in_on_close_handler', False):
            self._in_on_close_handler = True
            try:
                line_nums = sorted(self.program.keys()) or [0]
                for part in self._split_colon_statements(handler):
                    _, text = self._extract_label_prefix(part)
                    if not text:
                        continue
                    target = self._execute_statement(
                        0, text, line_nums, 0, 1, stmt_label=None, stmt_parts=None,
                    )
                    if target == -1:
                        break
            except ProgramExit:
                raise
            except Exception:
                pass
            finally:
                self._in_on_close_handler = False
        raise ProgramExit()

    def _shutdown_display(self, *, hold: Optional[bool] = None) -> None:
        if self._display is not None:
            try:
                do_hold = hold if hold is not None else self.config.hold_display_open
                # Only hold if the window is still open (user didn't X it).
                if do_hold and self._display_is_alive() and not getattr(
                    self, '_run_aborted', False
                ):
                    self._display.hold_open()
                self._display.end_run()
            except Exception:
                pass
        self._display_live = False
        # Do not pygame.quit() here. Full SDL teardown resets get_ticks() and
        # made the next RUN sleep on Clock.tick after the first flip.

    def _display_enabled(self) -> bool:
        return (
            self._display_live
            and self._display is not None
            and self._display_is_alive()
            and self._program_stdout is None
        )

    def _sync_graphics(self) -> None:
        if self._display_enabled() and hasattr(self._display, 'mark_dirty'):
            self._display.mark_dirty()

    def _update_mouse_from_display(self) -> None:
        """Refresh MOUSE x,y,b from the display (BBC MOUSE statement).

        Always sample the pointer immediately. Cached values only update in
        poll()/present paths; jclock does MOUSE before *REFRESH/INKEY, so
        without a live sample X%/Y% stay 0 and the clock sits lower-left.
        """
        if not self._display_enabled():
            return
        display = self._display
        # Prefer a dedicated refresh if present (updates OS-unit coords).
        updater = getattr(display, '_update_mouse_state', None)
        if callable(updater):
            try:
                updater()
            except Exception:
                pass
        if hasattr(display, 'mouse_state'):
            self._mouse_x, self._mouse_y, self._mouse_buttons = display.mouse_state()

    def _string_pixel_width(self, text: str) -> int:
        if self._display_enabled() and hasattr(self._display, 'cell_width'):
            return max(0, len(text)) * int(getattr(self._display, 'cell_width', 8))
        return max(0, len(text)) * 8

    def _set_custom_graphics_mode(
        self,
        width: int,
        height: int,
        *,
        charx: int = 8,
        chary: int = 16,
        ncols: int = 16,
        charset: int = 0,
    ) -> None:
        """BBCSDL VDU 23,22,width;height;charx,chary,ncols,charset."""
        self.config.graphics_width = max(1, int(width))
        self.config.graphics_height = max(1, int(height))
        self._graphics_mode = 0
        self._ensure_display()
        if self._display_enabled() and hasattr(self._display, 'set_graphics_size'):
            try:
                self._display.set_graphics_size(
                    self.config.graphics_width,
                    self.config.graphics_height,
                    charx=charx,
                    chary=chary,
                    ncols=ncols,
                    charset=charset,
                )
            except TypeError:
                # Older/test stubs without keyword params.
                self._display.set_graphics_size(
                    self.config.graphics_width,
                    self.config.graphics_height,
                )

    def pump_display_idle(self) -> bool:
        """Keep the pygame window alive while the REPL waits for input.

        Returns True to keep the REPL running. Window close tears down surfaces
        but does **not** exit the REPL — next RUN/MODE reopens the window.
        """
        if self._display is None or self._program_stdout is not None:
            return True
        if not self._display_live and not self._display_is_alive():
            return True
        # Streaming terminal: no window to pump; avoid empty full-grid present().
        if (
            self._display_backend_name() == 'terminal'
            and not getattr(self._display, '_positioned', False)
        ):
            return True
        if not self._display_is_alive():
            self._mark_display_closed()
            return True
        try:
            if hasattr(self._display, 'pump_events'):
                self._display.pump_events()
            self._display.present()
            if not self._display.poll():
                self._mark_display_closed()
        except Exception:
            self._mark_display_closed()
        return True

    def _ensure_display(self) -> None:
        if self._program_stdout is not None:
            return
        backend = (self.config.display or 'terminal').strip().lower()
        if backend in ('none', 'null'):
            return
        # REPL already has TerminalDisplay; CLI never did. After auto-enable
        # pygame, drop the console backend or MODE/COLOUR paint the terminal
        # (soccerball COLOUR 130 → green text screen) and CIRCLE/PLOT are no-ops.
        if backend == 'pygame' and self._display is not None:
            if type(self._display).__name__ != 'PygameDisplay':
                try:
                    self._display.end_run()
                except Exception:
                    pass
                self._display = None
                self._display_live = False
        if backend in ('', 'terminal'):
            # Create a real TerminalDisplay (grid + batched ANSI present)
            # so that high-volume TAB/PRINT programs are fast in terminal mode.
            if self._display is None:
                from mini_basic.display import create_display
                self._display = create_display(
                    'terminal',
                    text_cols=self.config.display_cols,
                    text_rows=self.config.display_rows,
                )
            if not self._display_live or not self._display_is_alive():
                self._display.begin_run()
                self._display_live = True
            return
        if self._display is None:
            from mini_basic.display import create_display, pygame_install_hint

            try:
                self._display = create_display(
                    backend,
                    text_cols=self.config.display_cols,
                    text_rows=self.config.display_rows,
                    graphics_width=self.config.graphics_width,
                    graphics_height=self.config.graphics_height,
                    scale=self.config.display_scale,
                    scale_locked=self.config.display_scale_locked,
                    caption=self.config.display_caption,
                    fps_limit=self.config.display_fps_limit,
                )
            except ImportError as exc:
                # Auto-enabled pygame without package installed, or locked request.
                if self.config.display_locked or backend != 'pygame':
                    raise ImportError(pygame_install_hint()) from exc
                print(
                    'pygame missing — falling back to terminal display.\n'
                    + pygame_install_hint()
                )
                self.config.display = 'terminal'
                self._display = create_display(
                    'terminal',
                    text_cols=self.config.display_cols,
                    text_rows=self.config.display_rows,
                )
                backend = 'terminal'
        if hasattr(self._display, 'fps_limit'):
            self._display.fps_limit = max(0, int(self.config.display_fps_limit))
        # Reopen after user closed the window (or first open).
        if self._display is not None:
            setattr(self._display, '_refresh_enabled', self._refresh_enabled)
        if not self._display_live or not self._display_is_alive():
            if self._display is not None:
                setattr(self._display, '_refresh_enabled', self._refresh_enabled)
            try:
                self._display.begin_run()
            except Exception:
                # Surface zombie: force full teardown and recreate once.
                try:
                    self._display.end_run()
                except Exception:
                    pass
                from mini_basic.display import create_display, ensure_no_pygame_leftovers
                ensure_no_pygame_leftovers()
                try:
                    self._display = create_display(
                        backend,
                        text_cols=self.config.display_cols,
                        text_rows=self.config.display_rows,
                        graphics_width=self.config.graphics_width,
                        graphics_height=self.config.graphics_height,
                        scale=self.config.display_scale,
                        scale_locked=self.config.display_scale_locked,
                        caption=self.config.display_caption,
                        fps_limit=self.config.display_fps_limit,
                    )
                except ImportError:
                    self.config.display = 'terminal'
                    self._display = create_display(
                        'terminal',
                        text_cols=self.config.display_cols,
                        text_rows=self.config.display_rows,
                    )
                self._display.begin_run()
            self._display_live = True
            if self._graphics_mode and hasattr(self._display, 'set_mode'):
                self._apply_bbc_mode(self._graphics_mode)
                self._display.set_mode(self._graphics_mode)

    def _colour_prefix_for_output(self) -> str:
        if self._display_enabled() and self.text_fg_colour is not None:
            self._display.set_colour(self.text_fg_colour)
            self._last_emitted_fg_colour = self.text_fg_colour
            return ''
        if self.text_fg_colour is None:
            self._last_emitted_fg_colour = None
            return ''
        if self._last_emitted_fg_colour == self.text_fg_colour:
            return ''
        self._last_emitted_fg_colour = self.text_fg_colour
        return self._ansi_fg_for_bbc_colour(self.text_fg_colour)

    def _live_terminal_size(self) -> Optional[Tuple[int, int]]:
        """Return (cols, rows) from the host terminal when it is a real TTY.

        Used for PRINT wrap / comma zones so a resizable console is not stuck
        at the MODE/default 80×30 grid. Returns None for pipes, tests, pygame.
        """
        backend = (self.config.display or 'terminal').strip().lower()
        if backend in ('none', 'null', 'pygame'):
            return None
        if self.config.display_locked and backend == 'none':
            return None
        try:
            if not sys.stdout.isatty():
                return None
        except Exception:
            return None
        try:
            import shutil

            size = shutil.get_terminal_size(fallback=(0, 0))
            cols = int(size.columns)
            rows = int(size.lines)
            if cols < 1 or rows < 1:
                return None
            return cols, rows
        except Exception:
            return None

    def _text_cols(self) -> int:
        live = self._live_terminal_size()
        if live is not None:
            return live[0]
        return max(1, int(self.config.display_cols))

    def _text_rows(self) -> int:
        live = self._live_terminal_size()
        if live is not None:
            return live[1]
        return max(1, int(self.config.display_rows))

    @staticmethod
    def _bbc_text_colour_code(code: int) -> int:
        """BBC COLOUR/VDU 17 logical colour (lower 8 bits; <128 fg, >=128 bg)."""
        return int(code) & 255

    def _graphics_plot_enabled(self) -> bool:
        spec = bbc_mode_spec(self._graphics_mode)
        if spec is None:
            return self._graphics_mode != 7
        return spec.plot_enabled

    def _display_backend_name(self) -> str:
        return (self.config.display or 'terminal').strip().lower()

    def _display_is_graphical(self) -> bool:
        return self._display_backend_name() not in ('', 'terminal', 'none', 'null')

    def _maybe_auto_enable_pygame_display(
        self,
        parsed_lines: List[Tuple[int, str, int]],
        *,
        announce: bool = True,
    ) -> None:
        if self.config.display_locked:
            return
        if self.config.dialect not in self._GRAPHICS_DIALECTS:
            return
        if self._display_backend_name() != 'terminal':
            return
        if not self._program_statements_use_graphics(parsed_lines):
            return
        self._enable_pygame_display(announce=announce)

    def _sync_display_caption(self, caption: str) -> None:
        """Window title follows the last successful LOAD (not the first .bbc)."""
        name = str(caption or '').strip() or 'mini_basic'
        self.config.display_caption = name
        disp = self._display
        if disp is None:
            return
        if hasattr(disp, 'caption'):
            disp.caption = name
        refresh = getattr(disp, '_refresh_window_caption', None)
        if callable(refresh):
            try:
                refresh()
            except Exception:
                pass

    def _enable_pygame_display(self, *, announce: bool = True) -> None:
        if self.config.display_locked:
            return
        if self._display_backend_name() != 'terminal':
            return
        from mini_basic.util.session import session_supports_gui

        if not session_supports_gui():
            if announce:
                print(
                    'Graphics skipped (text-only session; '
                    'use --display pygame if a window is available, '
                    'or unset MINIBASIC_NO_GRAPHICS / set DISPLAY)'
                )
            return
        from mini_basic.display import pygame_available, pygame_install_hint

        if not pygame_available():
            if announce:
                print(
                    'Graphics detected, but pygame is not installed — using terminal.\n'
                    + pygame_install_hint()
                )
            return
        self.config.display = 'pygame'
        self.config.hold_display_open = True
        _apply_pygame_display_defaults(self.config)
        if self.loaded_filename:
            self._sync_display_caption(os.path.basename(self.loaded_filename))
        if announce:
            print(
                'Graphics detected; pygame display enabled '
                '(use --display terminal to force text mode)'
            )

    def _bbc_path_with_trailing_sep(self, path: str) -> str:
        path = os.path.normpath(path)
        if not path.endswith(os.sep):
            path += os.sep
        return path

    def _bbc_at_dir(self) -> str:
        if self.loaded_filename:
            base = os.path.dirname(os.path.abspath(self.loaded_filename))
        else:
            base = self.working_dir
        return self._bbc_path_with_trailing_sep(base)

    def _bbc_at_lib(self) -> str:
        env = os.environ.get('BBCSDL_LIB', '').strip()
        if env:
            return self._bbc_path_with_trailing_sep(env)
        package_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        lib_dir = os.path.join(package_root, 'lib')
        if os.path.isdir(lib_dir):
            return self._bbc_path_with_trailing_sep(lib_dir)
        return self._bbc_at_dir()

    def _bbc_at_usr(self) -> str:
        env = os.environ.get('BBCSDL_USR', '').strip()
        if env:
            return self._bbc_path_with_trailing_sep(env)
        return self._bbc_path_with_trailing_sep(os.path.expanduser('~'))

    def _bbc_at_tmp(self) -> str:
        """BBCSDL ``@tmp$`` — temp directory with trailing separator (piechart GSAVE)."""
        env = os.environ.get('BBCSDL_TMP', '').strip()
        if env:
            return self._bbc_path_with_trailing_sep(env)
        import tempfile

        return self._bbc_path_with_trailing_sep(tempfile.gettempdir())

    def _ansi_fg_for_bbc_colour(self, colour: int) -> str:
        if colour < 8:
            return self._ansi_sgr(30 + colour)
        return f'{self._esc}[38;5;{colour}m'

    def _bbc_available_bytes(self) -> int:
        return max(0, int(self.bbc_himem) - int(self.bbc_lomem))

    def _bbc_bytes_per_dim_slot(self, kind: VarKind) -> int:
        # animal.txt: MAX=(HIMEM-LOMEM)/40 then DIM A$(MAX)
        if kind == 'str':
            return 40
        return 5

    def _bbc_max_dim_upper_bound(self, kind: VarKind) -> int:
        available = self._bbc_available_bytes()
        slot = self._bbc_bytes_per_dim_slot(kind)
        if available <= 0 or slot <= 0:
            return 0
        return available // slot

    def _bbc_bare_numeric_func_arg(
        self,
        expr: str,
        func_end: int,
        func: str,
    ) -> Optional[Tuple[Optional[str], int]]:
        pos = func_end
        while pos < len(expr) and expr[pos].isspace():
            pos += 1
        if pos < len(expr) and expr[pos] == '(':
            return None
        if func in self._BBC_BARE_NO_ARG_FUNCS:
            return None, pos
        # Glued string-func call as arg: VALMID$(s,i) / LENLEFT$(s,n) etc.
        str_func = re.match(
            r'^(MID\$|LEFT\$|RIGHT\$|CHR\$|STR\$|INKEY\$|STRING\$)\s*\(',
            expr[pos:],
            re.IGNORECASE,
        )
        if str_func:
            paren_start = pos + str_func.end() - 1
            paren_end = self._match_paren(expr, paren_start)
            if paren_end is not None and paren_end >= 0:
                arg = expr[pos : paren_end + 1]
                return arg, paren_end + 1
        if func in self._BBC_BARE_STRING_ARG_FUNCS:
            # Also accept quoted string literals: VAL"12"
            if pos < len(expr) and expr[pos] == '"':
                end = pos + 1
                while end < len(expr):
                    if expr[end] == '"':
                        end += 1
                        break
                    end += 1
                return expr[pos:end], end
            var_match = re.match(
                rf'^({self._VAR_BASE_PATTERN})([%$!#]?)',
                expr[pos:],
                self._identifier_re_flags(),
            )
            if not var_match:
                return None
            arg = var_match.group(1) + var_match.group(2)
            return arg, pos + var_match.end()
        if func == 'RND':
            num_match = re.match(r'^(-?\d+\.?\d*)', expr[pos:])
            if num_match:
                return num_match.group(1), pos + num_match.end()
            return None, pos
        # Nested glued numeric builtin: SINRADT → SINRAD + T, or RADT after SIN.
        nested = re.match(
            rf'({_NUMERIC_BUILTIN_FUNC_RE})',
            expr[pos:],
            re.IGNORECASE,
        )
        if nested:
            nfunc = nested.group(1).upper()
            n_end = pos + nested.end()
            inner = self._bbc_bare_numeric_func_arg(expr, n_end, nfunc)
            if inner is not None:
                iarg, iend = inner
                nested_val = self._eval_numeric_builtin_call(nfunc, iarg)
                return self._embed_numeric_for_eval(nested_val), iend
        var_match = re.match(
            rf'^({self._VAR_BASE_PATTERN})([%$!#]?)',
            expr[pos:],
            self._identifier_re_flags(),
        )
        if var_match:
            arg = var_match.group(1) + var_match.group(2)
            return arg, pos + var_match.end()
        num_match = re.match(r'^(-?\d+\.?\d*)', expr[pos:])
        if num_match:
            return num_match.group(1), pos + num_match.end()
        return None

    def _bbc_to_uint32(self, value: float) -> int:
        return int(value) & 0xFFFFFFFF

    def _bbc_hex_string(self, value: object) -> str:
        """Return uppercase hex digits (no 0x) for STR$~ / HEX$ / PRINT ~.

        Non-negative (incl. bigints): full hex. Negative: 32-bit two's complement.
        """
        try:
            ival = int(value)
        except (TypeError, ValueError):
            ival = int(float(value))
        if ival >= 0:
            return f'{ival:X}'
        else:
            uval = self._bbc_to_uint32(float(ival))
            return f'{uval:X}'

    def _bbc_bin_string(self, value: object) -> str:
        """Uppercase-free binary digits (no & or prefix) for BIN$.

        Non-negative (incl. bigints): full bits. Negative: 32-bit two's complement.
        """
        try:
            ival = int(value)
        except (TypeError, ValueError):
            ival = int(float(value))
        if ival >= 0:
            return format(ival, 'b')
        return format(self._bbc_to_uint32(float(ival)), 'b')

    def _pad_base_digits(self, digits: str, width: object) -> str:
        """HEX$(n, w) / BIN$(n, w): left-pad with 0; never truncate."""
        try:
            w = int(width)
        except (TypeError, ValueError):
            w = int(float(width))
        if w <= 0 or len(digits) >= w:
            return digits
        return digits.zfill(w)

    def _bbc_from_uint32(self, bits: int) -> float:
        if bits >= 0x80000000:
            bits -= 0x100000000
        return float(bits)

    def _bbc_bitwise_not(self, value: float) -> float:
        return self._bbc_from_uint32((~self._bbc_to_uint32(value)) & 0xFFFFFFFF)

    def _bbc_bitwise_xor(self, left: float, right: float) -> float:
        return self._bbc_from_uint32(
            self._bbc_to_uint32(left) ^ self._bbc_to_uint32(right),
        )

    def _bbc_bitwise_eqv(self, left: float, right: float) -> float:
        return self._bbc_from_uint32(
            (~(self._bbc_to_uint32(left) ^ self._bbc_to_uint32(right))) & 0xFFFFFFFF,
        )

    def _bbc_bitwise_imp(self, left: float, right: float) -> float:
        return self._bbc_from_uint32(
            ((~self._bbc_to_uint32(left)) & 0xFFFFFFFF) | self._bbc_to_uint32(right),
        )

    def _print_atom(self, expr: str) -> str:
        expr = expr.strip()
        if re.fullmatch(r'[-+]?(?:INF|INFINITY)', expr, re.IGNORECASE):
            return '-INF' if expr.startswith('-') else 'INF'
        if re.fullmatch(r'[-+]?\d+', expr):
            return expr
        # String variables / $ expressions must not go through arith (A$ is not Python).
        if '$' in expr or self._fragment_is_string_expr(expr):
            try:
                return self._eval_string_expr(expr)
            except Exception:
                pass
        if not self._RE_FN_CALL.search(expr) and '$' not in expr:
            try:
                reduced = self._eval_whole_arith(expr)
            except Exception:
                reduced = None
            if isinstance(reduced, int) and not isinstance(reduced, bool):
                return str(reduced)
            if isinstance(reduced, float):
                return self._format_number(reduced)
        try:
            if expr.upper() == '@%':
                return self._format_number(float(self.bbc_at_percent))
            system_name = self._canonical_system_var_name(expr)
        except ValueError:
            system_name = None
        if system_name:
            return self._format_number(self._get_system_var(system_name))
        # BBCSDL: a%% (64-bit / bigint storage) before a% (32-bit-style key).
        # Always format via _format_stored_int so we print full decimal digits,
        # never float scientific (SDL-style 1.222222E11 looks like a bug when
        # we already hold Python int / bigint behind %).
        id_flags = self._identifier_re_flags()
        int64_match = re.match(
            rf'^({self._VAR_BASE_PATTERN})%%$',
            expr,
            flags=id_flags,
        )
        if int64_match:
            key = self._normalize_identifier(int64_match.group(1)) + '%%'
            return self._format_stored_int(self.int_variables.get(key, 0))
        int_match = re.match(
            rf'^({self._VAR_BASE_PATTERN})%$',
            expr,
            flags=id_flags,
        )
        if int_match:
            return self._format_stored_int(
                self.int_variables.get(
                    self._normalize_identifier(int_match.group(1)),
                    0,
                )
            )
        # BBC # (double) / ! (single): always format as floating-point, never
        # expand float64 via int() into a long false-precision decimal
        # (e.g. a#=FNfact(100) → 9.3326…E157, not a 158-digit integer).
        float_suf_match = re.match(
            rf'^({self._VAR_BASE_PATTERN})[#!]$',
            expr,
            flags=id_flags,
        )
        if float_suf_match:
            base = self._normalize_identifier(float_suf_match.group(1))
            return self._format_number(float(self.variables.get(base, 0.0)))
        bare_match = re.match(
            rf'^({self._VAR_BASE_PATTERN})$',
            expr,
            flags=self._identifier_re_flags(),
        )
        if bare_match:
            base = self._normalize_identifier(bare_match.group(1))
            letter = base[0].upper() if base else ''
            if base in self.int_variables or self.default_var_types.get(letter) == 'int':
                return self._format_stored_int(self.int_variables.get(base, 0))
            if base in self.str_variables or self.default_var_types.get(letter) == 'str':
                return self.str_variables.get(base, '')
            if base in self.variables:
                return self._format_number(float(self.variables[base]))
        str_match = re.match(
            rf'^({self._VAR_BASE_PATTERN})\$$',
            expr,
            flags=self._identifier_re_flags(),
        )
        if str_match:
            return self.str_variables.get(
                self._normalize_identifier(str_match.group(1)),
                '',
            )
        # BBCSDL struct member access in print/eval context: obj.foo%  obj.bar$  obj.baz
        if '.' in expr:
            # try direct key lookup in struct_members (keys carry suffix like obj.bar$)
            if expr in self.struct_members:
                v = self.struct_members[expr]
                if isinstance(v, str):
                    return v
                if isinstance(v, (int, float)) and (expr.endswith('%') or expr.endswith('%%')):
                    return self._format_stored_int(v)
                if isinstance(v, (int, float)):
                    return self._format_number(float(v))
                return str(v)
            # also support without explicit suf on lookup for bare dotted
            dkey = expr
            if dkey in self.struct_members:
                v = self.struct_members[dkey]
                return str(v) if isinstance(v, str) else (self._format_stored_int(v) if isinstance(v, int) else self._format_number(float(v)))
        parsed = self._parse_array_lvalue(expr)
        if parsed is not None:
            base, kind, indices_expr = parsed
            value = self._array_get(base, kind, self._eval_array_indices(indices_expr))
            if kind == 'str':
                return str(value)
            if kind == 'int':
                return self._format_stored_int(value)
            return self._format_number(float(value))
        if expr.startswith('"'):
            return self._decode_bbc_adjacent_string_literals(expr)
        return self._format_number(self._eval_numeric(expr))

    def _present_terminal_display(self) -> None:
        """Flush terminal display so TAB/PRINT updates are visible mid-loop.

        Streaming mode already writes through to stdout on each PRINT; only
        grid mode (after goto) needs a full present() repaint.
        """
        if (
            self._display is not None
            and hasattr(self._display, 'present')
            and self._display_backend_name() == 'terminal'
        ):
            if not getattr(self._display, '_positioned', False):
                # Still flush any held incomplete CSI + tail via present().
                try:
                    self._display.present()
                except Exception:
                    pass
                return
            try:
                self._display.present()
            except Exception:
                pass

    def _inkey_from_pygame(self) -> str:
        """Non-blocking key from pygame display, if active."""
        if not self._display_enabled():
            return ''
        if hasattr(self._display, 'pump_events'):
            try:
                self._display.pump_events()
            except Exception:
                pass
        pygame_mod = getattr(self._display, '_pygame', None)
        if pygame_mod is None or not pygame_mod.get_init():
            return ''
        try:
            pygame_mod.event.pump()
            for event in pygame_mod.event.get():
                if event.type != pygame_mod.KEYDOWN:
                    continue
                if event.key == pygame_mod.K_ESCAPE:
                    return '\x1b'
                try:
                    from ..display import pygame_keydown_char
                    ch = pygame_keydown_char(pygame_mod, event)
                except Exception:
                    ch = None
                if ch:
                    return ch
                if getattr(event, 'unicode', None):
                    return str(event.unicode)
        except Exception:
            return ''
        return ''

    def _inkey_value(self) -> str:
        # Prefer pygame when a graphical display owns the keyboard.
        pg = self._inkey_from_pygame()
        if pg:
            return pg
        if sys.platform == 'win32':
            try:
                import msvcrt
                if msvcrt.kbhit():
                    char = msvcrt.getch()
                    # Swallow DOS extended prefixes (arrows etc.) so they are not
                    # mistaken for printable keys in INKEY$ loops.
                    if char in (b'\x00', b'\xe0'):
                        if msvcrt.kbhit():
                            msvcrt.getch()
                        return ''
                    if isinstance(char, bytes):
                        return char.decode('latin-1', errors='ignore')
                    return char
                return ''
            except ImportError:
                return ''
        import select
        if not sys.stdin.isatty():
            return ''
        try:
            readable, _, _ = select.select([sys.stdin], [], [], 0)
            if readable:
                return sys.stdin.read(1)
            return ''
        except OSError:
            return ''

    def _drain_inkey_buffer(self) -> None:
        """Discard pending console/pygame key events.

        Windows keyboard autorepeat fills the console buffer so a held key makes
        every subsequent INKEY$(n) return in 0ms and a REPEAT loop finishes in
        one flash (user only sees the last TAB frame, e.g. ``x*19``).  Timed
        INKEY$(n) for n>0 clears stale input first, then waits for a *new*
        press (or timeout) — closer to usable BBC game-loop pacing on PCs.
        """
        for _ in range(256):
            if not self._inkey_value():
                break

    def _inkey_code(self) -> float:
        text = self._inkey_value()
        return float(ord(text[0])) if text else -1.0

    def _inkey_bbc_negative_scan(self, scan_code: int) -> float:
        """BBC INKEY(n) for n < 0: immediate keyboard scan (non-blocking)."""
        if self._display_enabled():
            if hasattr(self._display, 'pump_events'):
                self._display.pump_events()
            pygame_mod = getattr(self._display, '_pygame', None)
            if pygame_mod is not None and pygame_mod.get_init():
                pygame_mod.event.pump()
                pressed = pygame_mod.key.get_pressed()
                if pressed[pygame_mod.K_ESCAPE]:
                    return 27.0
                for key_code in range(32, 127):
                    if pressed[key_code]:
                        return float(key_code)
        text = self._inkey_value()
        if text:
            return float(ord(text[0]))
        return -1.0

    def _inkey_code_wait(self, timeout_cs: float) -> float:
        if timeout_cs < 0:
            return self._inkey_bbc_negative_scan(int(timeout_cs))
        # Make prior PRINT/TAB/PLOT visible before waiting (same-line REPEAT:PRINT:INKEY
        # loops; welcome PROCPLOT ends with D%=INKEY2 as a frame delay so invert zaps
        # are seen — terminal present alone is a no-op for pygame).
        self._flush_program_output()
        self._present_terminal_display()
        if timeout_cs > 0 and self._display_enabled():
            # Force: rate-limited flush was dropping every invert frame of the swoosh
            # (draw+erase finish inside one interval → only the final erase shows).
            self._flush_display(force=True)
        if timeout_cs == 0:
            # INKEY$(0) / INKEY(0): non-blocking poll.
            # Official Acorn docs call n=0 an indefinite wait, but classic game
            # listings (including RACE.BBC's K$=INKEY$(0) frame poll) treat 0 as
            # "return immediately with empty/-1 if no key". Use GET / GET$ /
            # INKEY$(-1) style waits only via GET$/GET for blocking input.
            if self._display_enabled() and not self._display.poll():
                self._invoke_on_close_and_exit()
            text = self._inkey_value()
            if text:
                return float(ord(text[0]))
            return -1.0

        # Positive timeout: wait up to n centiseconds for a key.
        # Windows autorepeat would otherwise make REPEAT:A$=INKEY$(10):… finish
        # hundreds of iterations in one flash (user only sees final TAB frame).
        # For short frame-style timeouts (n <= 50 cs) we:
        #   - return the first key seen
        #   - drain same-character autorepeat
        #   - still wait out the rest of the interval (stable frame pacing)
        # Longer timeouts return as soon as a key arrives (prompt-style).
        deadline = time.perf_counter() + (timeout_cs / 100.0)
        pad_frame = timeout_cs <= 50.0
        found: Optional[float] = None
        while True:
            if self._display_enabled() and not self._display.poll():
                self._invoke_on_close_and_exit()
            if found is None:
                text = self._inkey_value()
                if text:
                    found = float(ord(text[0]))
                    # Drop a burst of same-character autorepeat (bounded).
                    for _ in range(64):
                        more = self._inkey_value()
                        if not more or more != text:
                            break
                    if not pad_frame:
                        return found
            if time.perf_counter() >= deadline:
                return found if found is not None else -1.0
            # While padding the frame, discard a small burst of held-key noise.
            if found is not None:
                for _ in range(16):
                    if not self._inkey_value():
                        break
            time.sleep(0.01)

