"""Module-level helpers shared by runtime mixins and the facade.

Auto-generated by tools/split_runtime_mixins.py.
Free functions that instance methods call by bare name live here so each
mixin module can import them into its globals.
"""
# ruff: noqa: F401,F403,F405,E402
import sys
from typing import Callable, Dict, List, Optional, Set, TextIO, Tuple

from ..config import DEFAULT_CONFIG, InterpreterConfig, SYSTEM_VAR_SPEC
from mini_basic.bbc_modes import bbc_mode_spec

def _get_readline_module():
    try:
        import readline
        return readline
    except ImportError:
        pass
    try:
        import importlib
        for name in ('pyreadline3', 'pyreadline'):
            try:
                return importlib.import_module(name)
            except ImportError:
                continue
    except ImportError:
        pass
    return None


def _windows_arrow_action(getwch, prefix: str) -> Optional[str]:
    legacy = {
        'K': 'left',
        'M': 'right',
        'H': 'up',
        'P': 'down',
    }
    if prefix in ('\x00', '\xe0'):
        code = getwch()
        return legacy.get(code)

    if prefix != '\x1b':
        return None

    try:
        second = getwch()
    except (EOFError, OSError):
        return None
    if second == '[':
        code = getwch()
        vt100 = {
            'D': 'left',
            'C': 'right',
            'A': 'up',
            'B': 'down',
        }
        return vt100.get(code)
    if second == 'O':
        code = getwch()
        vt52 = {
            'D': 'left',
            'C': 'right',
            'H': 'up',
            'F': 'down',
        }
        return vt52.get(code)
    return None


def _windows_apply_arrow(
    action: str,
    buffer: List[str],
    cursor: int,
    default: str,
) -> Tuple[List[str], int, bool]:
    redraw = False
    if action == 'left' and cursor > 0:
        cursor -= 1
    elif action == 'right':
        if cursor < len(buffer):
            cursor += 1
        elif not buffer and default:
            buffer[:] = list(default)
            cursor = len(buffer)
            redraw = True
    elif action == 'up' and default:
        buffer[:] = list(default)
        cursor = len(buffer)
        redraw = True
    return buffer, cursor, redraw


def _is_editable_char(ch: str) -> bool:
    """Accept normal BASIC source characters; drop accidental C0 controls.

    Ctrl+S (U+0013) etc. can be inserted by Windows console editing and then
    break ``TIME >= 100`` into ``TIME \\x13= 100`` → Python compile error.
    Allow tab; reject other controls below space.
    """
    if not ch:
        return False
    o = ord(ch[0])
    if o == 9:  # tab
        return True
    if o < 32 or o == 127:
        return False
    return True


def _sanitize_basic_source(text: str) -> str:
    """Strip C0 controls (except tab) from a BASIC source line."""
    return ''.join(ch for ch in text if ch == '\t' or (ord(ch) >= 32 and ord(ch) != 127))


def _windows_editing_input(
    prompt: str,
    default: str = '',
    getwch=None,
) -> str:
    import msvcrt

    if getwch is None:
        if not sys.stdin.isatty():
            return _sanitize_basic_source(input(prompt).rstrip())
        getwch = msvcrt.getwch

    buffer = list(_sanitize_basic_source(default))
    cursor = len(buffer)

    def place_cursor() -> None:
        column = len(prompt) + cursor + 1
        sys.stdout.write(f'\x1b[{column}G')
        sys.stdout.flush()

    def redraw() -> None:
        sys.stdout.write('\x1b[2K\r' + prompt + ''.join(buffer))
        place_cursor()

    redraw()

    while True:
        key = getwch()
        if key in ('\r', '\n'):
            sys.stdout.write('\n')
            sys.stdout.flush()
            return _sanitize_basic_source(''.join(buffer).rstrip())
        if key == '\x03':
            raise KeyboardInterrupt
        if key in ('\x08', '\x7f'):
            if cursor > 0:
                del buffer[cursor - 1]
                cursor -= 1
                redraw()
            continue
        if key in ('\x00', '\xe0', '\x1b'):
            action = _windows_arrow_action(getwch, key)
            if action:
                buffer, cursor, needs_redraw = _windows_apply_arrow(
                    action, buffer, cursor, default,
                )
                if needs_redraw:
                    redraw()
                else:
                    place_cursor()
            continue
        # Ignore control keys (e.g. Ctrl+S = U+0013) so they never enter source.
        if not _is_editable_char(key):
            continue
        buffer.insert(cursor, key)
        cursor += 1
        redraw()


def _prompt_editing_input(prompt: str, default: str = '') -> str:
    if sys.platform == 'win32' and sys.stdin.isatty():
        try:
            return _windows_editing_input(prompt, default)
        except (ImportError, OSError, ValueError):
            pass

    default = _sanitize_basic_source(default)
    readline = _get_readline_module()
    if readline is not None:
        saved_history: List[str] = []
        for index in range(1, readline.get_current_history_length() + 1):
            item = readline.get_history_item(index)
            if item is not None:
                saved_history.append(item)
        if hasattr(readline, 'clear_history'):
            readline.clear_history()
        if default:
            readline.add_history(default)

        def _prefill_hook() -> None:
            readline.set_startup_hook(None)
            if default:
                readline.insert_text(default)
                if hasattr(readline, 'redisplay'):
                    readline.redisplay()

        readline.set_startup_hook(_prefill_hook)
        try:
            return _sanitize_basic_source(input(prompt).rstrip())
        finally:
            readline.set_startup_hook(None)
            if hasattr(readline, 'clear_history'):
                readline.clear_history()
            for item in saved_history:
                readline.add_history(item)

    return _sanitize_basic_source(input(prompt).rstrip())


def _parse_path_arg(text: str) -> str:
    text = text.strip()
    if not text:
        raise ValueError('missing path')
    if text[0] in '"\'':
        quote = text[0]
        end = 1
        while end < len(text):
            if text[end] == quote:
                if end + 1 < len(text) and not text[end + 1].isspace():
                    raise ValueError('unexpected text after quoted path')
                return text[1:end]
            end += 1
        raise ValueError('unterminated quoted path')
    return text


def _apply_pygame_display_defaults(
    config: InterpreterConfig,
    *,
    gfx_customized: bool = False,
    cols_customized: bool = False,
    rows_customized: bool = False,
    scale_specified: bool = False,
) -> None:
    """Set BBC MODE 8-ish framebuffer and auto scale unless CLI overrode them."""
    mode8 = bbc_mode_spec(8)
    if mode8 is not None:
        if not gfx_customized:
            config.graphics_width = mode8.gfx_width
            config.graphics_height = mode8.gfx_height
        if not cols_customized:
            config.display_cols = mode8.text_cols
        if not rows_customized:
            config.display_rows = mode8.text_rows
    else:
        if not gfx_customized:
            config.graphics_width = 320
            config.graphics_height = 256
        if not cols_customized:
            config.display_cols = 40
        if not rows_customized:
            config.display_rows = 24
    if not scale_specified and not config.display_scale_locked:
        from mini_basic.display import auto_display_scale

        config.display_scale = auto_display_scale(
            graphics_width=config.graphics_width,
            graphics_height=config.graphics_height,
            text_cols=config.display_cols,
            text_rows=config.display_rows,
        )


