"""Module-level helpers shared by runtime mixins and the facade.

Auto-generated by tools/split_runtime_mixins.py.
Free functions that instance methods call by bare name live here so each
mixin module can import them into its globals.
"""
# ruff: noqa: F401,F403,F405,E402
import sys
from typing import Callable, Dict, List, Optional, Set, TextIO, Tuple

from ..config import DEFAULT_CONFIG, InterpreterConfig, SYSTEM_VAR_SPEC
from mini_basic.bbc_modes import bbc_mode_spec

def _get_readline_module():
    try:
        import readline
        return readline
    except ImportError:
        pass
    try:
        import importlib
        for name in ('pyreadline3', 'pyreadline'):
            try:
                return importlib.import_module(name)
            except ImportError:
                continue
    except ImportError:
        pass
    return None


def _is_editable_char(ch: str) -> bool:
    """Accept normal BASIC source characters; drop accidental C0 controls.

    Ctrl+S (U+0013) etc. can be inserted by Windows console editing and then
    break ``TIME >= 100`` into ``TIME \\x13= 100`` → Python compile error.
    Allow tab; reject other controls below space.
    """
    if not ch:
        return False
    o = ord(ch[0])
    if o == 9:  # tab
        return True
    if o < 32 or o == 127:
        return False
    return True


def _sanitize_basic_source(text: str) -> str:
    """Strip C0 controls (except tab) from a BASIC source line."""
    return ''.join(ch for ch in text if ch == '\t' or (ord(ch) >= 32 and ord(ch) != 127))


def _windows_arrow_action(getwch, prefix: str) -> Optional[str]:
    """Map special keys (arrows, Home/End, Ctrl+Left/Right, …)."""
    from mini_basic.repl.windows_input import parse_special_key

    return parse_special_key(getwch, prefix)


def _windows_apply_arrow(
    action: str,
    buffer: List[str],
    cursor: int,
    default: str,
) -> Tuple[List[str], int, bool]:
    """Apply named line-edit action (shared with REPL)."""
    from mini_basic.repl.windows_input import apply_line_edit

    return apply_line_edit(action, buffer, cursor, default=default)


def _windows_editing_input(
    prompt: str,
    default: str = '',
    getwch=None,
) -> str:
    """AUTO/EDIT line editor: Home/End, word motion, kill keys (like terminal)."""
    from mini_basic.repl.windows_input import windows_editing_input

    text = windows_editing_input(
        prompt,
        default=_sanitize_basic_source(default),
        getwch=getwch,
    )
    return _sanitize_basic_source(text)


def _prompt_editing_input(prompt: str, default: str = '') -> str:
    """
    Prompt for editable BASIC source (EDIT, AUTO, bare line number).

    Prefer readline (GNU on Unix, pyreadline3 on Windows). Custom msvcrt
    editor is only a fallback when no readline backend is installed.
    """
    default = _sanitize_basic_source(default)
    # Never drive pyreadline/input under pytest capture (non-TTY) — that yields
    # "pytest: reading from stdin while output is captured".
    readline = _get_readline_module()
    if readline is not None and sys.stdin.isatty():

        def _prefill_hook() -> None:
            readline.set_startup_hook(None)
            if default:
                readline.insert_text(default)
                if hasattr(readline, 'redisplay'):
                    readline.redisplay()

        # Do not clear_history(): that wiped pastable history when editing lines.
        readline.set_startup_hook(_prefill_hook)
        try:
            return _sanitize_basic_source(input(prompt).rstrip())
        finally:
            readline.set_startup_hook(None)

    if sys.platform == 'win32' and sys.stdin.isatty():
        try:
            return _windows_editing_input(prompt, default)
        except (ImportError, OSError, ValueError):
            pass

    return _sanitize_basic_source(input(prompt).rstrip())


def _parse_path_arg(text: str) -> str:
    text = text.strip()
    if not text:
        raise ValueError('missing path')
    if text[0] in '"\'':
        quote = text[0]
        end = 1
        while end < len(text):
            if text[end] == quote:
                if end + 1 < len(text) and not text[end + 1].isspace():
                    raise ValueError('unexpected text after quoted path')
                return text[1:end]
            end += 1
        raise ValueError('unterminated quoted path')
    return text


def _apply_pygame_display_defaults(
    config: InterpreterConfig,
    *,
    gfx_customized: bool = False,
    cols_customized: bool = False,
    rows_customized: bool = False,
    scale_specified: bool = False,
) -> None:
    """Set BBC MODE 8-ish framebuffer and auto scale unless CLI overrode them."""
    mode8 = bbc_mode_spec(8)
    if mode8 is not None:
        if not gfx_customized:
            config.graphics_width = mode8.gfx_width
            config.graphics_height = mode8.gfx_height
        if not cols_customized:
            config.display_cols = mode8.text_cols
        if not rows_customized:
            config.display_rows = mode8.text_rows
    else:
        if not gfx_customized:
            config.graphics_width = 320
            config.graphics_height = 256
        if not cols_customized:
            config.display_cols = 40
        if not rows_customized:
            config.display_rows = 24
    if not scale_specified and not config.display_scale_locked:
        from mini_basic.display import auto_display_scale

        config.display_scale = auto_display_scale(
            graphics_width=config.graphics_width,
            graphics_height=config.graphics_height,
            text_cols=config.display_cols,
            text_rows=config.display_rows,
        )


