"""BASICInterpreter mixin: io.

PRINT/INPUT/DATA/files, LIST/SAVE/LOAD, and formatting.

Auto-generated by tools/split_runtime_mixins.py — do not hand-edit bulk.
"""
# ruff: noqa: F401,F403,F405,E402,W291,W293
# Imports mirrored from monorepo runtime for method bodies.
import fnmatch
import json
import math
import random
import re
import os
import struct
import sys
import time

from ..config import DEFAULT_CONFIG, InterpreterConfig, SYSTEM_VAR_SPEC
from ..dialect_hint import DialectHint, parse_comment_dialect_line, split_dialect_hints
from ..constants import (
    CLI_EXIT_WORDS as _CLI_EXIT_WORDS,
    EXIT_HOLD_CONSOLE,
    EXPR_RESERVED_WORDS as _EXPR_RESERVED_WORDS,
    NUMERIC_BUILTIN_FUNCS as _NUMERIC_BUILTIN_FUNCS,
    NUMERIC_BUILTIN_FUNC_RE as _NUMERIC_BUILTIN_FUNC_RE,
    SAFE_EVAL_GLOBALS as _SAFE_EVAL_GLOBALS,
)
from ..expr.compile import CompiledExpr, int_slot
from ..expr.patterns import (
    RE_ARRAY_HEAD as _RE_ARRAY_HEAD,
    RE_COND_EQ as _RE_COND_EQ,
    RE_COND_NE as _RE_COND_NE,
    RE_DYNAMIC_CALL_REMAINS as _RE_DYNAMIC_CALL_REMAINS,
    RE_FILE_FUNC as _RE_FILE_FUNC,
    RE_FILE_FUNC_BBC as _RE_FILE_FUNC_BBC,
    RE_FN_CALL as _RE_FN_CALL,
    RE_FUNC_CALL as _RE_FUNC_CALL,
    RE_HAS_LETTER as _RE_HAS_LETTER,
    RE_INKEY_CALL as _RE_INKEY_CALL,
    RE_INT_DIV as _RE_INT_DIV,
    RE_MOD as _RE_MOD,
    RE_NUMERIC_FUNC_CALL as _RE_NUMERIC_FUNC_CALL,
    RE_TIME as _RE_TIME,
    RE_VAR_BASE_FULL as _RE_VAR_BASE_FULL,
    VAR_BASE_PATTERN as _VAR_BASE_PATTERN,
)

from ..format import UsingFormatter
from ..format.save_case import (
    Fold as _SaveFold,
    fold_from_save_case as _fold_from_save_case,
    format_program_line as _format_program_line_save_case,
    format_statement_part as _format_statement_part_save_case,
)
from ..repl.completion import configure_readline as _configure_repl_readline
from ..repl.help_browser import run_help_browser as _run_help_browser
from ..util import (
    basic_truth as _basic_truth,
    hard_exit as _hard_exit,
    near_equal as _near_equal,
    near_equal_sig as _near_equal_sig,
    probe_float_platform as _probe_float_platform,
)
from ..type_system import (
    ArrayStorage,
    BasicRuntimeError,
    ChainTransfer,
    DataItem,
    Dialect,
    FieldBuffer,
    FileChannel,
    FnReturn,
    CaseBlockLayout,
    CaseFrame,
    IfBlockLayout,
    IfFrame,
    ListCommand,
    LoopFrame,
    ProcReturn,
    ProgramExit,
    UserFunction,
    UserProcedure,
    VarKind,
)
from typing import Callable, Dict, List, Optional, Set, TextIO, Tuple

_SYSTEM_VAR_SPEC = SYSTEM_VAR_SPEC

       
# BBC Micro MODE specs (text grid, graphics resolution, PAR) — see bbc_modes.py.
from mini_basic.bbc_modes import bbc_mode_spec

from .helpers import (
    _get_readline_module,
    _windows_arrow_action,
    _windows_apply_arrow,
    _windows_editing_input,
    _prompt_editing_input,
    _parse_path_arg,
    _apply_pygame_display_defaults,
)

class RuntimeIoMixin:
    """Mixin providing io-related BASICInterpreter methods."""

    def _tee_terminal_write(self, text: str) -> None:
        if not text or self._program_stdout is not None:
            return
        out = sys.stdout
        out.write(text)
        out.flush()

    def _tee_emit_input_char(self, ch: str) -> None:
        self._tee_terminal_write(ch)
        self._tee_echo_input_char_to_display(ch)

    def _tee_emit_input_backspace(self) -> None:
        self._tee_terminal_backspace()
        self._tee_backspace_input_on_display()

    def _tee_finish_input_line(self) -> None:
        self._tee_terminal_write('\n')
        self._tee_newline_on_display()

    def _read_combined_tee_input_line(self, max_length: int = 255) -> str:
        """Read from the pygame window and/or terminal; echo to both."""
        display = self._display
        pygame_mod = getattr(display, '_pygame', None)
        buffer: List[str] = []
        limit = max(1, int(max_length))
        use_msvcrt = False
        msvcrt = None
        if sys.platform == 'win32' and sys.stdin.isatty() and self._program_stdout is None:
            try:
                import msvcrt as _msvcrt
            except ImportError:
                msvcrt = None
            else:
                msvcrt = _msvcrt
                use_msvcrt = True
        use_select = (
            not use_msvcrt
            and sys.stdin.isatty()
            and self._program_stdout is None
        )
        started_text_input = False
        dummy_sdl = os.environ.get('SDL_VIDEODRIVER', '').lower() == 'dummy'
        if pygame_mod is not None and getattr(display, '_open', False) and not dummy_sdl:
            pygame_mod.key.start_text_input()
            started_text_input = True
        from mini_basic.display import pygame_keydown_char
        try:
            while getattr(display, '_open', True):
                if pygame_mod is not None:
                    pygame_mod.event.pump()
                    for event in pygame_mod.event.get():
                        if event.type == pygame_mod.QUIT:
                            display._open = False
                            return ''
                        if event.type == pygame_mod.TEXTINPUT:
                            # Prefer TEXTINPUT for printables (do not also
                            # append from KEYDOWN — that double-fired and a
                            # bad "skip same as last char" filter turned
                            # 3344223344 into 34234).
                            for ch in event.text:
                                if not ch.isprintable() or len(buffer) >= limit:
                                    continue
                                buffer.append(ch)
                                self._tee_emit_input_char(ch)
                            continue
                        if event.type != pygame_mod.KEYDOWN:
                            continue
                        if event.key == pygame_mod.K_ESCAPE:
                            raise KeyboardInterrupt
                        if event.key in (pygame_mod.K_RETURN, pygame_mod.K_KP_ENTER):
                            self._tee_finish_input_line()
                            return ''.join(buffer)
                        if event.key == pygame_mod.K_BACKSPACE:
                            if buffer:
                                buffer.pop()
                                self._tee_emit_input_backspace()
                            continue
                        # Special keys only; printables come from TEXTINPUT.
                        continue
                if use_msvcrt and msvcrt is not None and msvcrt.kbhit():
                    code = msvcrt.getwch()
                    if self._tee_apply_terminal_char(buffer, code, limit):
                        return ''.join(buffer)
                if use_select:
                    import select
                    ready, _, _ = select.select([sys.stdin], [], [], 0)
                    if ready:
                        ch = sys.stdin.read(1)
                        if self._tee_apply_terminal_char(buffer, ch, limit):
                            return ''.join(buffer)
                if getattr(display, '_dirty', False):
                    display.present()
                elif hasattr(display, '_clock') and display._clock is not None:
                    display._clock.tick(getattr(display, 'fps_limit', 60))
                else:
                    time.sleep(0.01)
        finally:
            if started_text_input and pygame_mod is not None:
                pygame_mod.key.stop_text_input()
        return ''.join(buffer)

    def _read_terminal_line_windows(self) -> str:
        import msvcrt

        chars: List[str] = []
        while True:
            self._pump_display_for_input()
            if not msvcrt.kbhit():
                time.sleep(0.01)
                continue
            code = msvcrt.getwch()
            if code in ('\r', '\n'):
                self._tee_terminal_write('\n')
                self._tee_newline_on_display()
                return ''.join(chars)
            if code == '\x03':
                raise KeyboardInterrupt
            if code == '\x08':
                if chars:
                    chars.pop()
                    self._tee_terminal_backspace()
                    self._tee_backspace_input_on_display()
                continue
            if code in ('\x00', '\xe0'):
                msvcrt.getwch()
                continue
            chars.append(code)
            self._tee_terminal_write(code)
            self._tee_echo_input_char_to_display(code)

    def _read_terminal_line_select(self) -> str:
        import select

        chars: List[str] = []
        fd = sys.stdin.fileno()
        while True:
            self._pump_display_for_input()
            ready, _, _ = select.select([sys.stdin], [], [], 0.05)
            if not ready:
                continue
            ch = sys.stdin.read(1)
            if ch in ('\n', '\r'):
                self._tee_terminal_write('\n')
                self._tee_newline_on_display()
                return ''.join(chars)
            if ch == '\x03':
                raise KeyboardInterrupt
            if ch in ('\x7f', '\x08'):
                if chars:
                    chars.pop()
                    self._tee_terminal_backspace()
                    self._tee_backspace_input_on_display()
                continue
            chars.append(ch)
            self._tee_terminal_write(ch)
            self._tee_echo_input_char_to_display(ch)

    def _read_terminal_line_while_pumping_display(self) -> str:
        """Read stdin on the main thread while pumping display events if needed.

        Pure terminal (no pygame): use line-buffered ``input()`` so repeated
        digits and long numbers are not mangled by char-by-char getwch paths.
        Pygame tee mode still needs the msvcrt/select pump loops.
        """
        if self._program_stdout is not None:
            return ''
        has_pygame = getattr(self._display, '_pygame', None) is not None
        if not has_pygame:
            sys.stdout.flush()
            self._pump_display_for_input()
            try:
                return input().rstrip('\n\r')
            except EOFError:
                raise ProgramExit()
            except KeyboardInterrupt:
                print()
                self._run_aborted = True
                raise
        if sys.platform == 'win32' and sys.stdin.isatty():
            try:
                return self._read_terminal_line_windows()
            except ImportError:
                pass
        if sys.stdin.isatty():
            try:
                return self._read_terminal_line_select()
            except OSError:
                pass
        sys.stdout.flush()
        self._pump_display_for_input()
        return input().rstrip('\n\r')

    def _read_program_input(self, prompt: str = '? ') -> str:
        self._flush_program_output()
        self._ensure_display()
        if self._display_enabled():
            if prompt:
                self._print_program_text(prompt, newline=False)
                self._flush_display(force=True)
            self._input_active = True
            try:
                read_line = getattr(self._display, 'read_line', None)
                if self._terminal_tee_enabled():
                    self._tee_terminal_write(
                        '(type in the game window or this terminal, press Enter)\n',
                    )
                    line = self._read_combined_tee_input_line()
                elif callable(read_line):
                    try:
                        line = read_line()
                    except NotImplementedError:
                        # TerminalDisplay inherits base read_line that raises;
                        # fall back to stdin (tests / non-pygame backends).
                        line = self._read_terminal_line_while_pumping_display()
                else:
                    line = self._read_terminal_line_while_pumping_display()
            except EOFError:
                raise ProgramExit()
            except KeyboardInterrupt:
                if self._terminal_tee_enabled():
                    self._tee_terminal_write('\n')
                self._run_aborted = True
                raise
            finally:
                self._input_active = False
            if not self._display.poll():
                self._invoke_on_close_and_exit()
            if self.config.input_exit_words:
                token = line.strip().lower()
                if token in _CLI_EXIT_WORDS:
                    raise ProgramExit()
            return line
        self._flush_program_output()
        try:
            line = input(prompt)
        except EOFError:
            raise ProgramExit()
        except KeyboardInterrupt:
            print()
            self._run_aborted = True
            raise
        if self.config.input_exit_words:
            token = line.strip().lower()
            if token in _CLI_EXIT_WORDS:
                raise ProgramExit()
        return line

    def _restore_console(self) -> None:
        """Reset host terminal modes without wiping program output.

        Important: only leave the alternate screen if we entered it (grid/TAB
        mode). Emitting ESC[?1049l after a streaming Mandelbrot on the main
        buffer can make Windows Terminal discard/swap the visible scrollback
        so the plot disappears the moment RUN ends.
        """
        if self._program_stdout is not None:
            return
        out = sys.stdout
        # Under redirect_stdout / pipes, skip CSI writes. Sequences like
        # ESC[?25h contain '?' and break tests that assertNotIn('?', out).
        write_ansi = True
        try:
            write_ansi = bool(getattr(out, 'isatty', lambda: False)())
        except Exception:
            write_ansi = False
        disp = getattr(self, '_display', None)
        entered_alt = bool(disp is not None and getattr(disp, '_alt_screen', False))
        if write_ansi:
            try:
                # Always: colours/cursor back to normal (does not clear scrollback).
                out.write('\x1b[0m\x1b[?25h')
                # Only if grid mode used the private buffer:
                if entered_alt:
                    out.write('\x1b[?1049l')
                    try:
                        disp._alt_screen = False
                    except Exception:
                        pass
                # Private modes that can steal the mouse wheel / break PSReadLine.
                # These do not clear the screen when disabled.
                out.write(
                    '\x1b[?2004l'   # bracketed paste off
                    '\x1b[?1000l'   # mouse tracking off
                    '\x1b[?1002l'
                    '\x1b[?1003l'
                    '\x1b[?1006l'
                    '\x1b[?1005l'
                    '\x1b[?1l'      # normal cursor keys
                    '\x1b[?7h'      # wraparound on
                )
                out.flush()
            except Exception:
                pass
        elif entered_alt:
            try:
                disp._alt_screen = False
            except Exception:
                pass
        if sys.platform == 'win32':
            try:
                import ctypes

                kernel32 = ctypes.windll.kernel32
                if self._saved_console_mode is not None:
                    kernel32.SetConsoleMode(
                        kernel32.GetStdHandle(-11),  # STD_OUTPUT_HANDLE
                        self._saved_console_mode,
                    )
                if self._saved_console_mode_in is not None:
                    kernel32.SetConsoleMode(
                        kernel32.GetStdHandle(-10),  # STD_INPUT_HANDLE
                        self._saved_console_mode_in,
                    )
            except Exception:
                pass

    def _flush_display(self, force: bool = False) -> None:
        self._check_user_interrupt()
        self._ensure_display()
        if self._display_enabled():
            self._update_mouse_from_display()
            if force or self._refresh_enabled:
                now = time.monotonic()
                # Dense PLOT loops (saucer): still show progress, but present less
                # often so CPU spends time plotting. Patch present keeps it smooth.
                interval = self._present_min_interval
                gfx = getattr(self._display, '_gfx', None)
                plots = int(getattr(gfx, 'plot_count', 0) or 0) if gfx is not None else 0
                if not force and plots >= 64:
                    # ~8–12 Hz during plot storms (was 20 Hz full-frame uploads).
                    interval = max(interval, 1.0 / 10.0)
                # Grid PRINT in graphics modes sets compose_full; the dirty-rect
                # patch path skips text. Never rate-limit that compose, or hands
                # (Clock) present first and digital/title text never appears.
                compose_full = bool(getattr(self._display, '_compose_full', False))
                if force or compose_full or (now - self._last_present_time) >= interval:
                    self._display.present(force=force or compose_full)
                    self._last_present_time = now
                    if (
                        not self._input_active
                        and hasattr(self._display, 'pump_events')
                    ):
                        self._display.pump_events()
            if not self._input_active and not self._display.poll():
                self._invoke_on_close_and_exit()

    def _flush_program_output(self) -> None:
        self._print_flush_buffer()
        if not self._console_write_buffer:
            return
        out = self._get_program_stdout()
        out.write(''.join(self._console_write_buffer))
        out.flush()
        self._console_write_buffer.clear()

    def _print_finish_line(self) -> None:
        self.text_row += 1
        self.text_col = 0
        self.print_column = 0

    def _sync_print_column_after_input(self) -> None:
        """INPUT echoes via the display without updating print_column; resync after Enter."""
        if self._display_enabled() and hasattr(self._display, '_cursor_col'):
            self.print_column = max(0, int(self._display._cursor_col))
            if hasattr(self._display, '_cursor_row'):
                self.text_row = max(0, int(self._display._cursor_row))
            self.text_col = self.print_column
            return
        self.print_column = 0
        self.text_col = 0

    def _clear_screen(self) -> None:
        # Flush first — never discard pending PRINT text. Old code cleared
        # _console_write_buffer without writing, so a CLS after buffered PRINTs
        # (e.g. ROADRACE results: CLS then "YOU COMPLETED…") swallowed the screen.
        self._flush_program_output()
        self.text_row = 0
        self.text_col = 0
        self.print_column = 0
        self._last_emitted_fg_colour = None
        self._ensure_display()

        if self._display_enabled():
            # Always clear the draw buffer; with *REFRESH OFF, display.clear() skips present().
            self._display.clear()

        # Emit ANSI clear for terminal mode / captured stdout (used by tests for CLS/VDU12)
        out = self._get_program_stdout()
        use_console = self._program_stdout is None and out in (sys.stdout, sys.stderr)
        if use_console:
            self._ensure_ansi_console()
            if sys.platform == 'win32' and not self._ansi_console_enabled:
                os.system('cls')
                return
        sequence = f'{self._esc}[2J{self._esc}[H'
        out.write(sequence)
        out.flush()
        if self._display is not None and hasattr(self._display, 'present'):
            try:
                if getattr(self, '_refresh_enabled', True):
                    self._display.present(force=True)
            except Exception:
                pass
    def _display_write_vdu_string(self, text: str) -> None:
        self.dprint('[VDU]', 'text', repr(text))
        if not text:
            return

        buf = []
        i = 0

        while i < len(text):
            code = ord(text[i])

            self.dprint('[VDU]', 'ch', i, code, repr(text[i]))

            if code == 17:                      # BBC VDU 17 / COLOUR
                if buf:
                    #self._colour_prefix_for_output()
                    self._display.write(''.join(buf))
                    buf.clear()

                i += 1
                if i < len(text):
                    self._display.set_colour(ord(text[i]))
                    self.dprint('[VDU]', 'colour', ord(text[i]))
                i += 1
                continue

            buf.append(text[i])
            i += 1
        self.dprint('[VDU]', 'buf', repr(buf))
        if buf:
            self.dprint('[VDU]', 'write', repr(''.join(buf)))
            # self._colour_prefix_for_output()
            self._display.write(''.join(buf))
            buf.clear()

    def _print_flush_buffer(self, force_newline: bool = False) -> None:
        if not self._print_line_parts:
            return
        out = self._get_program_stdout()
        out.write(''.join(self._print_line_parts))
        if force_newline and self._print_line_parts[-1] != '\n':
            out.write('\n')
        out.flush()
        self._print_line_parts.clear()

    def _print_program_text(self, text: str, newline: bool) -> None:
        # Immediate mode (REPL ``PRINT`` after RUN): stay on the terminal.
        # Re-opening pygame here hid the numbers on the graphics window, and
        # poll() treating Esc as QUIT then raised ProgramExit → Goodbye!
        immediate = getattr(self, '_active_line_num', -1) == 0
        if not (immediate and not self._display_live):
            self._ensure_display()
        if newline and text and text[-1] == '\n':
            newline = False
        if self._display_enabled():
            if self._terminal_tee_enabled() or immediate:
                if text:
                    self._tee_terminal_write(text)
                if newline:
                    self._tee_terminal_write('\n')
            if text:
                self._display_write_vdu_string(text)
            if newline:
                self._display.newline()
                self._print_finish_line()
            if self._refresh_enabled and hasattr(self._display, 'mark_dirty'):
                self._display.mark_dirty()
            if not self._display.poll():
                if immediate:
                    self._mark_display_closed()
                else:
                    self._invoke_on_close_and_exit()
            return
        if text:
            prefix = self._colour_prefix_for_output()
            if prefix:
                text = prefix + text
        if self.config.print_line_buffering:
            self._print_line_parts.append(text)
            if newline:
                self._print_line_parts.append('\n')
                self._print_flush_buffer()
                self._print_finish_line()
            return
        if text:
            self._console_write_buffer.append(text)
        if newline:
            self._console_write_buffer.append('\n')
            self._print_finish_line()
            # Be lazy with flushes for terminal mode: high volume of PRINT TAB / positioned
            # output (as in RACE.BBC etc) would otherwise cause many small writes + flushes,
            # which is very slow on Windows console. Flush on volume or at sync points
            # (CLS, before input, shutdown, etc).
            if len(self._console_write_buffer) > 2048:
                self._flush_program_output()

    def _clear_stop_state(self) -> None:
        self.stopped = False
        self.stop_resume_at = None

    def _save_stop_position(
        self,
        line_num: int,
        stmt_index: int,
        stmt_count: int,
        line_nums: List[int],
    ) -> None:
        resume_at = self._compute_stop_resume_at(line_num, stmt_index, stmt_count, line_nums)
        self.stopped = resume_at is not None
        self.stop_resume_at = resume_at

    def _renumber_text_outside_strings(
        self,
        text: str,
        transform,
    ) -> str:
        result: List[str] = []
        index = 0
        while index < len(text):
            if text[index] == '"':
                end = index + 1
                while end < len(text) and text[end] != '"':
                    end += 1
                end = min(end + 1, len(text))
                result.append(text[index:end])
                index = end
                continue
            end = index
            while end < len(text) and text[end] != '"':
                end += 1
            if end > index:
                result.append(transform(text[index:end]))
            index = end
        return ''.join(result)

    def _renumber_statement_part(self, text: str, mapping: Dict[int, int]) -> str:
        body = text.strip()
        if not body:
            return text

        def transform(segment: str) -> str:
            def repl_goto_gosub(match: re.Match) -> str:
                return f'{match.group(1)} {self._map_renumber_line_ref(match.group(2), mapping)}'

            segment = re.sub(
                r'\b(GOTO|GOSUB)\s+(\d+)\b',
                repl_goto_gosub,
                segment,
                flags=re.IGNORECASE,
            )
            segment = re.sub(
                r'\bRESTORE\s+(\d+)\b',
                lambda match: f'RESTORE {self._map_renumber_line_ref(match.group(1), mapping)}',
                segment,
                flags=re.IGNORECASE,
            )
            on_error = re.fullmatch(
                r'ON\s+ERROR\s+(GOTO|GOSUB)\s+(\d+)\s*',
                segment.strip(),
                flags=re.IGNORECASE,
            )
            if on_error:
                return (
                    f'ON ERROR {on_error.group(1)} '
                    f'{self._map_renumber_line_ref(on_error.group(2), mapping)}'
                )
            on_match = re.match(
                r'ON\s+(.+?)\s+(GOTO|GOSUB)\s+(.+)$',
                segment.strip(),
                flags=re.IGNORECASE,
            )
            if on_match:
                targets = [
                    self._map_renumber_line_ref(token, mapping)
                    if re.fullmatch(r'\d+', token.strip())
                    else token.strip()
                    for token in self._split_args(on_match.group(3))
                    if token.strip()
                ]
                return (
                    f'ON {on_match.group(1)} {on_match.group(2)} '
                    + ', '.join(targets)
                )
            then_goto = re.fullmatch(
                r'(.+?)\s+THEN\s+GOTO\s+(\d+)\s*',
                segment.strip(),
                flags=re.IGNORECASE,
            )
            if then_goto:
                return (
                    f'{then_goto.group(1)} THEN GOTO '
                    f'{self._map_renumber_line_ref(then_goto.group(2), mapping)}'
                )
            bare_goto = re.fullmatch(
                r'(.+?)\s+GOTO\s+(\d+)\s*',
                segment.strip(),
                flags=re.IGNORECASE,
            )
            if bare_goto and not re.search(r'\bTHEN\b', bare_goto.group(1), re.IGNORECASE):
                return (
                    f'{bare_goto.group(1)} GOTO '
                    f'{self._map_renumber_line_ref(bare_goto.group(2), mapping)}'
                )
            then_line = re.fullmatch(
                r'(.+?)\s+THEN\s+(\d+)\s*',
                segment.strip(),
                flags=re.IGNORECASE,
            )
            if then_line and not re.search(r'\bGOTO\b', then_line.group(1), re.IGNORECASE):
                return (
                    f'{then_line.group(1)} THEN '
                    f'{self._map_renumber_line_ref(then_line.group(2), mapping)}'
                )
            return segment

        return self._renumber_text_outside_strings(body, transform)

    def _renumber_statement(self, statement: str, mapping: Dict[int, int]) -> str:
        parts: List[str] = []
        for part in self._split_colon_statements(statement):
            label, body = self._extract_label_prefix(part)
            if not body:
                parts.append(part)
                continue
            new_body = self._renumber_statement_part(body, mapping)
            if label:
                parts.append(f'{label}: {new_body}')
            else:
                parts.append(new_body)
        return ': '.join(parts)

    def _clear_runtime_variables(self) -> None:
        self.variables.clear()
        self.int_variables.clear()
        self.str_variables.clear()
        self.array_storage.clear()
        self.default_var_types.clear()
        self._invalidate_run_prepare_caches()

    def _format_stored_int(self, value: object) -> str:
        """Format an integer / %% / bigint for PRINT — full decimal, never float E-notation."""
        try:
            ival = int(value)
        except (TypeError, ValueError):
            return self._format_number(float(value))
        # bigint path (default): exact decimal. Even with bigint off, prefer
        # exact int text when the value is an integral float within safe range.
        if self._bigint_enabled() or isinstance(value, int):
            return str(ival)
        return self._format_number(float(value))

    def _report_dialect_violation(self, message: str) -> bool:
        if self.config.strict_dialect:
            self._emit_error(message)
            return False
        self._emit_error(f'Warning: {message}')
        return True

    def _format_runtime_error_location(
        self,
        line_num: int,
        stmt_index: int,
        stmt_count: int = 1,
        statement: Optional[str] = None,
    ) -> str:
        location = f'at line {line_num}' if line_num > 0 else ''
        if stmt_count > 1 and line_num > 0:
            location += f' statement {stmt_index + 1} of {stmt_count}'
        if statement:
            preview = ' '.join(statement.split())
            if len(preview) > 56:
                preview = preview[:53] + '...'
            if location:
                location += f' in `{preview}`'
            else:
                location = f'in immediate: `{preview}`'
        return location

    def _report_runtime_issue(self, message: str) -> None:
        line_num = self._active_line_num if self._active_line_num >= 0 else 0
        self._runtime_error(
            message,
            line_num,
            self._active_stmt_index,
            stmt_count=self._exec_stmt_count,
            statement=self._active_statement or None,
        )

    def _report_expression_error(self, expr: str, exc: Optional[Exception] = None) -> str:
        detail = self._expression_error_detail(expr, exc)
        self._report_runtime_issue(f'? Expression error: {detail}')
        return ''

    def _materialize_data_item(self, item: DataItem) -> DataItem:
        if item.kind == 'float':
            return item
        if item.kind == 'str':
            text = str(item.value)
            # Empty DATA fields (DATA a,,b) must stay empty strings for READ A$.
            # Evaluating '' as a number yields 0 and corrupts string READs.
            if not text.strip():
                return item
            stripped = text.strip()
            try:
                value = self._eval_numeric(stripped)
            except Exception:
                return item
            # Implicit 0 makes unknown names succeed. Keep unset words as
            # strings (DATA hello / ELIZA) but still eval defined vars
            # (DATA P after P=3) and real expressions (p * 3).
            bare = re.fullmatch(r'[_A-Za-z][A-Za-z0-9_]*[%$!#]?', stripped)
            if bare:
                key = self._normalize_identifier(stripped.rstrip('%$!#'))
                if (
                    key not in self.variables
                    and key not in self.int_variables
                    and key not in self.str_variables
                ):
                    return item
            return DataItem('float', value)
        return item

    def _restore_data_pointer(
        self,
        rest: str,
        line_num: int,
        stmt_index: int = 0,
    ) -> None:
        rest_strip = rest.strip()
        rel_match = re.match(r'^\+\s*(\d+)$', rest_strip)
        if rel_match:
            offset = int(rel_match.group(1))
            if offset < 1:
                raise ValueError('invalid RESTORE offset')
            following = [
                location for location in self._data_locations
                if location[0] > line_num
                or (location[0] == line_num and location[1] > stmt_index)
            ]
            if offset > len(following):
                raise ValueError('no DATA at RESTORE offset')
            self.data_pointer = following[offset - 1][2]
            return
        restore_line = int(self._eval_numeric(rest_strip))
        if restore_line not in self.data_line_starts:
            raise ValueError('no DATA on line')
        self.data_pointer = self.data_line_starts[restore_line]

    def _print_end_keyword_hint(self, line_num: int, rest: str) -> bool:
        key = rest.strip().upper()
        if not key:
            return False
        hint = self._END_KEYWORD_HINTS.get(key)
        if hint:
            self._emit_error(f'? Line {line_num}: use {hint}, not END {rest.strip()}')
            return True
        self._emit_error(f'? Line {line_num}: END stops the program — it takes no keyword')
        return True

    def _restore_fn_param_bindings(
        self,
        saved: List[Tuple[str, VarKind, object, bool]],
    ) -> None:
        for name, kind, old_val, had in reversed(saved):
            if kind == 'str':
                if had:
                    self.str_variables[name] = str(old_val)
                else:
                    self.str_variables.pop(name, None)
                continue
            if kind == 'int':
                if had:
                    self.int_variables[name] = self._coerce_int_storage(old_val)
                else:
                    self.int_variables.pop(name, None)
            else:
                if had:
                    self.variables[name] = float(old_val)
                else:
                    self.variables.pop(name, None)

    def _report_fn_eval_error(self, expr: str) -> str:
        detail = self._expression_error_detail(expr)
        if detail.startswith('FN'):
            message = f'? FN error: {detail}'
        else:
            message = '? FN error'
        self._report_runtime_issue(message)
        return ''

    def _restore_local_bindings(self) -> None:
        if not self._local_save_stack:
            return
        frame = self._local_save_stack.pop()
        for entry in reversed(frame):
            kind = entry[0]
            if kind == 'array':
                _, key, saved = entry
                if saved is None:
                    self.array_storage.pop(key, None)
                else:
                    self.array_storage[key] = saved
                continue
            _, name, saved = entry
            if kind == 'str':
                if saved is None:
                    self.str_variables.pop(name, None)
                else:
                    self.str_variables[name] = saved
            elif kind == 'int':
                if saved is None:
                    self.int_variables.pop(name, None)
                else:
                    self.int_variables[name] = saved
            else:
                if saved is None:
                    self.variables.pop(name, None)
                else:
                    self.variables[name] = saved

    def _format_number(self, value: float) -> str:
        # Preserve full integer text when eval left us a Python int / bigint
        # (e.g. FN return or %% after arith) — never coerce through float first.
        if isinstance(value, int) and not isinstance(value, bool):
            return self._format_stored_int(value)
        try:
            fval = float(value)
        except (TypeError, ValueError):
            return str(value)
        at = self.bbc_at_percent
        if at:
            width = at & 0xFF
            decimals = (at >> 8) & 0xFF
            fmt_type = (at >> 16) & 0xFF
            if fmt_type == 1:
                text = str(int(round(fval)))
            elif fmt_type == 2:
                text = f'{fval:.{decimals}f}'
            elif fmt_type == 3:
                text = f'{fval:.{decimals}E}'
            else:
                if decimals:
                    text = f'{fval:.{decimals}g}'
                elif math.isfinite(fval) and abs(fval) < 1e15 and fval == int(fval):
                    text = str(int(fval))
                else:
                    text = self._format_float_display(fval)
            if width > 0 and len(text) < width:
                text = text.rjust(width)
            elif width > 0 and len(text) > width:
                text = text[:width]
            return text
        if not math.isfinite(fval):
            return str(fval).upper()
        # Exact small integers only — never int() a huge float64 (false digits).
        if abs(fval) < 1e15 and fval == int(fval):
            return str(int(fval))
        return self._format_float_display(fval)

    def _format_float_display(self, value: float) -> str:
        """BBC-style float text: scientific for large/small magnitudes."""
        if not math.isfinite(value):
            return str(value).upper()
        # Prefer E notation outside ordinary range (matches BBC G/E defaults).
        if abs(value) >= 1e10 or (value != 0.0 and abs(value) < 1e-2):
            text = f'{value:.6E}'
            # Normalize +0 → bare E like many BASICs: 1.23E+10 → 1.23E10 optional;
            # keep Python-style E+ for clarity unless bare E preferred.
            return text
        return str(value)

    def _split_implicit_print_items(self, item: str) -> List[str]:
        """MBASIC implicit PRINT items: TAB/SPC glued without ; or ,.

        ``SPC(n)"Hi"``, ``TAB(6)"x"``, and ``"BANKER"TAB(20)"PLAYER"`` /
        ``C$(3)TAB(20)C$(1)`` (bacarrat.bas) are one PRINT argument until split.
        """
        stripped = item.strip()
        if not stripped:
            return []
        if not re.search(
            r'(?<![A-Za-z0-9_])(?:SPC|TAB)\s*\(',
            stripped,
            re.IGNORECASE,
        ):
            return [stripped]
        parts: List[str] = []
        index = 0
        start = 0
        in_string = False
        length = len(stripped)
        while index < length:
            ch = stripped[index]
            if ch == '"':
                in_string = not in_string
                index += 1
                continue
            if not in_string:
                match = re.match(
                    r'(?:SPC|TAB)\s*\(',
                    stripped[index:],
                    re.IGNORECASE,
                )
                prev = stripped[index - 1] if index else ''
                if match and (index == 0 or not (prev.isalnum() or prev == '_')):
                    prior = stripped[start:index].strip()
                    if prior:
                        parts.append(prior)
                    open_idx = index + match.end() - 1
                    try:
                        close_idx = self._match_paren(stripped, open_idx)
                    except ValueError:
                        parts.append(stripped[index:])
                        return parts
                    parts.append(stripped[index:close_idx + 1])
                    index = close_idx + 1
                    start = index
                    continue
            index += 1
        tail = stripped[start:].strip()
        if tail:
            parts.append(tail)
        return parts or [stripped]

    def _split_print_items(self, content: str) -> List[Tuple[str, str]]:
        items: List[Tuple[str, str]] = []
        current: List[str] = []
        depth = 0
        in_string = False
        for ch in content:
            if ch == '"':
                in_string = not in_string
                current.append(ch)
            elif ch == '(' and not in_string:
                depth += 1
                current.append(ch)
            elif ch == ')' and not in_string:
                depth -= 1
                current.append(ch)
            # BBC: , zone; ; pack; ' force newline between items
            elif ch in ",;'" and not in_string and depth == 0:
                item = ''.join(current).strip()
                if item:
                    items.append((item, ch))
                elif ch in (',', "'"):
                    # bare "," pads; bare "'" is a lone newline item
                    items.append(('', ch))
                current = []
            else:
                current.append(ch)
        item = ''.join(current).strip()
        if item:
            items.append((item, ''))
        return self._expand_implicit_print_items(items)

    def _strip_bbc_print_newline_suffix(self, content: str) -> Tuple[str, bool]:
        """BBC trailing apostrophe suppresses PRINT newline (e.g. TEXT'' )."""
        stripped = content.rstrip()
        suppress = False
        while stripped.endswith("'"):
            stripped = stripped[:-1].rstrip()
            suppress = True
        return stripped, suppress

    def _decode_print_string_item(self, item: str) -> str:
        return self._decode_bbc_adjacent_string_literals(item.strip())

    def _is_string_print_item(self, item: str) -> bool:
        item = item.strip()
        if item.startswith('"') or '"' in item:
            # Support BBC-style juxtaposition: 1"foo""bar"X$  or  "a" "b" total
            # even if item starts with number/var before first "
            return True
        return '$' in item

    def _print_item_has_string_concat(self, item: str) -> bool:
        in_string = False
        for ch in item:
            if ch == '"':
                in_string = not in_string
            elif ch == '+' and not in_string:
                return True
        return False

    def _print_pad_to_next_field(self, force_advance: bool = False) -> str:
        cols = self._text_cols()
        prefix = ''
        if self.print_column >= cols:
            prefix = '\n'
            self._print_finish_line()
        field_width = self.print_field_width
        # 0 = tight comma: one space (not classic fixed zone). Useful in
        # resizable terminals where zone 10 looks sparse or wraps oddly.
        if field_width <= 0:
            if force_advance or self.print_column > 0:
                self.print_column += 1
                self.text_col += 1
                return prefix + ' '
            return prefix
        if force_advance:
            remainder = self.print_column % field_width
            pad = field_width - remainder
            if pad == 0:
                pad = field_width
        else:
            pad = (-self.print_column) % field_width

        if self.print_column + pad >= cols:
            prefix += '\n'
            self._print_finish_line()
            pad = field_width if force_advance else 0

        self.print_column += pad
        self.text_col += pad
        return prefix + (' ' * pad)

    def _print_visible_width(self, text: str) -> int:
        """Count printable columns only (skip ANSI CSI and BBC VDU 17 colour pairs).

        Hanoi discs embed ``CHR$17+CHR$(128+n)+…+CHR$17+CHR$128``. Counting those
        bytes as columns made PRINT wrap near col 80 mid-sequence, so the trailing
        ``CHR$128`` was written as a glyph and TAKE could not erase it (floating
        green remnants on pygame and terminal).
        """
        width = 0
        index = 0
        length = len(text)
        while index < length:
            ch = text[index]
            if ch == self._esc and index + 1 < length and text[index + 1] == '[':
                end = text.find('m', index + 2)
                if end == -1:
                    index += 1
                    continue
                index = end + 1
                continue
            # BBC VDU 17 / COLOUR: control byte + colour parameter (not a cell).
            if ord(ch) == 17:
                index += 2 if index + 1 < length else 1
                continue
            if ch == '\n':
                index += 1
                continue
            width += 1
            index += 1
        return width

    def _print_emit(self, text: str) -> str:
        cols = self._text_cols()
        non_wrapping = len(text) > cols and bool(
            re.fullmatch(r'[-+]?[\dA-Fa-f.]+', text)
        )
        parts: List[str] = []
        index = 0
        length = len(text)
        while index < length:
            if text[index] == self._esc and index + 1 < length and text[index + 1] == '[':
                end = text.find('m', index + 2)
                if end == -1:
                    parts.append(text[index])
                    index += 1
                    continue
                parts.append(text[index:end + 1])
                index = end + 1
                continue
            ch = text[index]
            # Pass VDU 17 + colour through without advancing print_column / wrapping.
            if ord(ch) == 17:
                parts.append(ch)
                index += 1
                if index < length:
                    parts.append(text[index])
                    index += 1
                continue
            if ch == '\n':
                parts.append(ch)
                self._print_finish_line()
                index += 1
                continue
            if not non_wrapping and self.print_column >= cols:
                parts.append('\n')
                self._print_finish_line()
            parts.append(ch)
            self.print_column += 1
            self.text_col += 1
            index += 1
        return ''.join(parts)

    def _print_emit_number_field(self, text: str) -> str:
        field_width = self.print_field_width
        if field_width <= 0:
            # Tight mode: no right-justified zone; print as-is.
            return self._print_emit(text)
        remaining = field_width - (self.print_column % field_width)
        if remaining <= 0:
            remaining = field_width
        if len(text) >= remaining:
            return self._print_emit(text)
        padded = ' ' * (remaining - len(text)) + text
        return self._print_emit(padded)

    def _try_render_print_special(self, item: str) -> Optional[str]:
        item = item.strip()
        up = item.upper()
        if 'TAB' not in up and 'SPC' not in up:
            return None
        spc_match = re.match(r'^SPC\s*\((.+)\)$', item, re.IGNORECASE)
        if spc_match:
            count = max(0, int(self._eval_numeric(spc_match.group(1))))
            return ' ' * count
        tab_match = re.match(r'^TAB\s*\((.+)\)$', item, re.IGNORECASE)
        if tab_match:
            args = self._split_args(tab_match.group(1))
            if len(args) >= 2:
                col = int(self._eval_numeric(args[0]))
                row = int(self._eval_numeric(args[1]))
                return self._ansi_goto(row, col)
            column = int(self._eval_numeric(args[0]))
            target = max(0, column - 1)
            self._ensure_display()
            if self._display_enabled():
                if self.print_column > target:
                    self._print_finish_line()
                    self._display.newline()
                self.print_column = target
                self.text_col = target
                self._display.goto(self.text_row, target)
                return ''
            parts: List[str] = []
            if self.print_column > target:
                parts.append('\n')
                self._print_finish_line()
            pad = max(0, target - self.print_column)
            self.print_column += pad
            self.text_col += pad
            parts.append(' ' * pad)
            return ''.join(parts)
        return None

    def _render_print_using(self, format_expr: str, value_exprs: List[str]) -> str:
        format_str = self._eval_string_expr(format_expr.strip())
        if not format_str:
            raise ValueError('empty PRINT USING format')
        values = self._eval_print_using_values(value_exprs)
        return UsingFormatter(format_str).format_values(values)

    def _format_write_token(self, expr: str) -> str:
        expr = expr.strip()
        if not expr:
            return ''
        if len(expr) >= 2 and expr[0] == '"' and expr[-1] == '"':
            return json.dumps(self._decode_string_literal(expr))
        if self._is_string_print_item(expr):
            try:
                return json.dumps(self._eval_string_expr(expr))
            except Exception:
                pass
        value = self.eval_expr(expr)
        if isinstance(value, float):
            if math.isfinite(value) and abs(value) < 1e15 and value == int(value):
                return str(int(value))
            return self._format_number(value)
        if isinstance(value, int) and not isinstance(value, bool):
            return self._format_stored_int(value)
        return str(value)

    def _render_write_content(self, content: str) -> str:
        return ','.join(
            self._format_write_token(part)
            for part in self._split_args(content)
            if part.strip()
        )

    def _render_print_content(
        self,
        content: str,
        trailing_sep: str,
        print_column: int,
    ) -> Tuple[str, bool, int]:
        saved_column = self.print_column
        self.print_column = print_column
        try:
            output: List[str] = []
            items = self._split_print_items(content)
            has_comma = any(sep == ',' for _, sep in items) or trailing_sep == ','
            has_string_item = any(
                self._is_string_print_item(item) for item, _ in items
            )
            hex_mode = False
            for index, (item, sep) in enumerate(items):
                prev_sep = items[index - 1][1] if index > 0 else ''
                if index > 0 and prev_sep == ',':
                    output.append(self._print_pad_to_next_field())
                # Note: apostrophe separator newline is emitted when *leaving*
                # an item (sep == "'" below). Do not also insert one here —
                # that produced blank lines for PRINT "A'"B" → A\\n\\nB.

                if not item.strip():
                    if sep == ',':
                        output.append(self._print_pad_to_next_field(force_advance=True))
                    elif sep == "'":
                        # PRINT '  alone — newline (may be first item)
                        output.append('\n')
                        self.print_column = 0
                    continue

                item_strip = item.strip()
                # BBC PRINT ~n — hex for this and following numeric items.
                if item_strip.startswith('~'):
                    hex_mode = True
                    item_strip = item_strip.lstrip('~').strip()
                    item = item_strip
                    if not item:
                        continue

                special = self._try_render_print_special(item)
                if special is not None:
                    text = special
                else:
                    if self._is_string_print_item(item_strip):
                        try:
                            text = self._eval_string_expr(item_strip)
                        except Exception:
                            text = self.eval_print_value(item)
                    elif hex_mode:
                        text = self._bbc_hex_string(self._eval_numeric(item_strip))
                    else:
                        text = self.eval_print_value(item)

                use_number_field = (
                    has_comma
                    and not has_string_item
                    and not self._is_string_print_item(item)
                    and (index == 0 or prev_sep == ',')
                )
                if use_number_field:
                    output.append(self._print_emit_number_field(text))
                else:
                    output.append(self._print_emit(text))

                if sep == "'":
                    output.append('\n')
                    self.print_column = 0

            suppress_newline = bool(trailing_sep) and trailing_sep != "'"
            return ''.join(output), not suppress_newline, self.print_column
        finally:
            self.print_column = saved_column

    def _alloc_file_channel(self) -> int:
        while self._next_file_channel in self.file_channels:
            self._next_file_channel += 1
        channel = self._next_file_channel
        self._next_file_channel += 1
        return channel

    def _close_file_channels(self) -> None:
        for channel in list(self.file_channels.values()):
            try:
                channel.handle.close()
            except OSError:
                pass
        self.file_channels.clear()
        self.field_buffers.clear()

    def _close_file_channel(self, channel_num: int) -> bool:
        file_channel = self.file_channels.pop(channel_num, None)
        if file_channel is None:
            return False
        try:
            file_channel.handle.close()
        except OSError:
            return False
        self.field_buffers.pop(channel_num, None)
        return True

    def _read_get_char(self) -> int:
        """BBC GET: block until a key is pressed."""
        self._flush_program_output()
        if self._display_enabled():
            self._display.present(force=True)   # <-- ADD THIS LINE
            pygame_mod = getattr(self._display, '_pygame', None)
            if pygame_mod is not None and pygame_mod.get_init():
                while True:
                    if not self._display.poll():
                        self._invoke_on_close_and_exit()
                    pygame_mod.event.pump()
                    for event in pygame_mod.event.get():
                        if event.type == pygame_mod.KEYDOWN:
                            if event.key == pygame_mod.K_ESCAPE:
                                return 27
                            try:
                                from ..display import pygame_keydown_char
                                ch = pygame_keydown_char(pygame_mod, event)
                            except Exception:
                                ch = None
                            if ch is not None:
                                return ord(ch)
                    time.sleep(0.01)
        if sys.platform == 'win32':
            try:
                import msvcrt
                while True:
                    if self._display_enabled() and not self._display.poll():
                        self._invoke_on_close_and_exit()
                    if msvcrt.kbhit():
                        return self._decode_console_key(msvcrt.getch())
                    time.sleep(0.01)
            except ImportError:
                pass
        elif sys.stdin.isatty():
            import select
            import tty
            import termios
            fd = sys.stdin.fileno()
            old = termios.tcgetattr(fd)
            try:
                tty.setcbreak(fd)
                while True:
                    if self._display_enabled() and not self._display.poll():
                        self._invoke_on_close_and_exit()
                    readable, _, _ = select.select([sys.stdin], [], [], 0.05)
                    if readable:
                        ch = sys.stdin.read(1)
                        return ord(ch) if ch else 0
            finally:
                termios.tcsetattr(fd, termios.TCSADRAIN, old)
        return 0

    def _open_mbasic_file(
        self,
        mode: str,
        file_num: int,
        filename: str,
        record_length: Optional[int] = None,
    ) -> bool:
        if file_num < 1 or file_num > 15:
            self._emit_error(f'? Bad file number: {file_num} (use 1-15)')
            return False
        if file_num in self.file_channels:
            self._emit_error(f'? File already open: #{file_num}')
            return False
        if not isinstance(filename, str):
            self._emit_error('? OPEN error: filename must be a string')
            return False
        try:
            resolved = self.resolve_path(filename)
            mode = mode.upper()
            if mode == 'I':
                handle = open(resolved, 'r', encoding='utf-8', newline='')
                self.file_channels[file_num] = FileChannel(
                    handle=handle, mode='r', filename=filename,
                )
            elif mode == 'O':
                handle = open(resolved, 'w', encoding='utf-8', newline='')
                self.file_channels[file_num] = FileChannel(
                    handle=handle, mode='w', filename=filename,
                )
            elif mode == 'A':
                handle = open(resolved, 'a', encoding='utf-8', newline='')
                self.file_channels[file_num] = FileChannel(
                    handle=handle, mode='w', filename=filename,
                )
            elif mode == 'R':
                try:
                    handle = open(resolved, 'r+b')
                except FileNotFoundError:
                    handle = open(resolved, 'w+b')
                self.file_channels[file_num] = FileChannel(
                    handle=handle, mode='R', filename=filename,
                )
                if record_length and record_length > 0:
                    self.field_buffers[file_num] = FieldBuffer(
                        buffer=bytearray(record_length),
                        fields={},
                    )
            else:
                self._emit_error(f'? OPEN error: unknown mode {mode!r}')
                return False
            return True
        except OSError as exc:
            self._emit_error(self._error_message(f'? OPEN error ({filename})', exc))
            return False

    def _mark_file_channel_eof(self, file_channel: FileChannel) -> None:
        file_channel.eof = True

    def _get_file_channel(self, channel: int) -> Optional[FileChannel]:
        return self.file_channels.get(channel)

    def _open_file_channel(self, path: str, mode: str) -> float:
        try:
            resolved = self.resolve_path(path)
            # Empty files are valid (EOF# true immediately). Do not reject size 0 —
            # animal PROCread and tests rely on OPENIN succeeding so EOF# can run.
            handle = open(resolved, mode, encoding='utf-8', newline='')
            channel_id = self._alloc_file_channel()
            self.file_channels[channel_id] = FileChannel(
                handle=handle,
                mode=mode,
                filename=resolved,
            )
            return float(channel_id)
        except OSError:
            return 0.0

    def _split_channel_prefix(self, rest: str) -> Tuple[Optional[str], str]:
        return self._split_first_at_depth(rest, ',')

    def _write_file_byte(self, channel: FileChannel, value: object) -> None:
        """BBC BPUT#: write the low 8 bits as one raw byte."""
        byte = int(self._coerce_int_storage(value)) & 0xFF
        handle = channel.handle
        raw = getattr(handle, 'buffer', None)
        if raw is not None:
            handle.flush()
            raw.write(bytes([byte]))
            return
        mode = getattr(handle, 'mode', '') or ''
        if 'b' in mode:
            handle.write(bytes([byte]))
            return
        handle.write(chr(byte))

    def _write_file_text(self, channel: FileChannel, text: str, newline: bool) -> None:
        channel.handle.write(text)
        if newline:
            channel.handle.write('\n')
            channel.print_column = 0
        else:
            channel.print_column += len(text)

    def _read_file_char(self, channel: FileChannel) -> Optional[str]:
        ch = channel.handle.read(1)
        if not ch:
            return None
        return ch

    def _read_file_value(self, channel: FileChannel, kind: VarKind) -> Optional[str]:
        if kind == 'str':
            chars: List[str] = []
            while True:
                ch = self._read_file_char(channel)
                if ch is None:
                    if not chars:
                        return None
                    break
                if ch in '\r\n':
                    if chars:
                        break
                    continue
                chars.append(ch)
            return ''.join(chars)

        token: List[str] = []
        while True:
            ch = self._read_file_char(channel)
            if ch is None:
                break
            if ch in '\r\n':
                if token:
                    break
                continue
            if ch in ' \t,' and token:
                channel.handle.seek(channel.handle.tell() - 1)
                break
            if ch in ' \t,':
                continue
            token.append(ch)
        if not token:
            return None
        return ''.join(token)

    def _read_file_line(self, channel: FileChannel) -> Optional[str]:
        chars: List[str] = []
        saw_data = False
        while True:
            ch = self._read_file_char(channel)
            if ch is None:
                if not saw_data:
                    return None
                break
            saw_data = True
            if ch == '\r':
                continue
            if ch == '\n':
                break
            chars.append(ch)
        return ''.join(chars)

    def _split_input_vars(self, content: str) -> List[str]:
        return self._split_at_depth(content, ',', skip_empty=True)

    def _is_input_lvalue(self, item: str) -> bool:
        item = item.strip()
        if not item or item[0] == '"':
            return False
        if self._parse_array_lvalue(item) is not None:
            return True
        try:
            self._parse_var_token(item)
            return True
        except ValueError:
            return False

    def _join_print_items(self, items: List[Tuple[str, str]]) -> str:
        parts: List[str] = []
        for item, sep in items:
            parts.append(item)
            if sep:
                parts.append(sep)
        return ''.join(parts)

    def _emit_input_prompt(self, content: str) -> None:
        self._print_flush_buffer()
        if self.print_column > 0:
            self._print_program_text('\n', newline=True)
            self.print_column = 0
        text, _, self.print_column = self._render_print_content(
            content,
            '',
            self.print_column,
        )
        self._print_program_text(text, newline=False)
        self._flush_program_output()

    def _split_input_line_values(self, line: str) -> List[str]:
        return self._split_at_depth(line, ',')

    def _read_lvalue(self, token: str) -> Tuple[str, str, VarKind, Optional[List[int]], object]:
        parsed = self._parse_array_lvalue(token)
        if parsed is not None:
            base, kind, indices_expr = parsed
            indices = self._eval_array_indices(indices_expr)
            return (
                'array',
                base,
                kind,
                indices,
                self._array_get(base, kind, indices),
            )
        base, kind = self._parse_var_token(token)
        if kind == 'str':
            return ('var', base, kind, None, self.str_variables.get(base, ''))
        if kind == 'int':
            return ('var', base, kind, None, self.int_variables.get(base, 0))
        return ('var', base, kind, None, self.variables.get(base, 0.0))

    def _write_lvalue(
        self,
        loc: Tuple[str, str, VarKind, Optional[List[int]], object],
        value: object,
    ) -> None:
        kind = loc[0]
        if kind == 'array':
            _, base, var_kind, indices, _ = loc
            if indices is None:
                raise ValueError('invalid array lvalue')
            self._array_set(base, var_kind, indices, value)
            return
        _, base, var_kind, _, _ = loc
        if var_kind == 'str':
            self.str_variables[base] = str(value)
            return
        if var_kind == 'int':
            self._register_numeric_var(base, 'int')
            self.int_variables[base] = self._coerce_int_storage(value)
            return
        self._register_numeric_var(base, 'float')
        self.variables[base] = float(value)

    def format_list_line(self, statement: str) -> str:
        """LIST/SAVE line text via the single format/save_case authority."""
        from mini_basic.format.save_case import format_program_line, resolve_list_fold

        return format_program_line(statement, resolve_list_fold(self._detokenize_fold()))

    def _format_line_number(
        self,
        line_num: int,
        show_number: bool,
        *,
        align: bool = True,
    ) -> str:
        """Format a LIST/SAVE line-number prefix.

        When ``show_number`` is false but ``align`` is true (LIST REFS), emit a
        blank field so statement text still lines up. When neither (SAVE PRETTY
        unnumbered), emit nothing.
        """
        if show_number:
            return f'{line_num:>6} '
        return '       ' if align else ''

    def list_program(self, command: Optional[ListCommand] = None):
        if command is None:
            command = ListCommand()
        elif isinstance(command, str):
            command = ListCommand(mode=command.lower())
        if command.mode in ('pretty', 'refs'):
            # Recompute structure first so DEF FN / DEF PROC bodies indent
            # under their headers on this listing (not only after the first LIST).
            self._apply_structural_indents()
        for line in self._program_display_lines(
            command.mode,
            include_line_numbers=True,
            start_line=command.start_line,
            end_line=command.end_line,
            case_fold=self._detokenize_fold(),
        ):
            print(line)

    def list_dir(self, pattern: Optional[str] = None) -> None:
        """List a directory (DOS/BBC-style).

        * ``DIR`` — current working directory
        * ``DIR test`` / ``DIR test\\`` — contents of folder ``test`` (not just the name)
        * ``DIR *.bas`` — name filter in the current directory
        * ``DIR test\\*.py`` — name filter inside ``test``
        """
        search_dir = self.working_dir
        name_filter: Optional[str] = None

        if pattern:
            raw = pattern.strip().strip('"\'')
            if raw:
                # Normalise path separators; keep trailing-sep info before strip.
                norm = raw.replace('/', os.sep)
                ends_as_dir = norm.endswith(os.sep) or (
                    os.altsep is not None and norm.endswith(os.altsep)
                )
                stripped = norm.rstrip('/\\')
                has_wild = any(ch in stripped for ch in '*?')

                if has_wild:
                    parent, base = os.path.split(stripped)
                    if parent:
                        search_dir = self.resolve_path(parent)
                    name_filter = base or None
                else:
                    candidate = self.resolve_path(stripped) if stripped else self.working_dir
                    if os.path.isdir(candidate):
                        search_dir = candidate
                    elif ends_as_dir:
                        self._emit_error(f'? Directory not found: {pattern}')
                        return
                    elif os.path.isfile(candidate):
                        print(os.path.dirname(candidate) or search_dir)
                        print(f'         {os.path.basename(candidate)}')
                        return
                    else:
                        # Bare token with no matching path: filter cwd basenames
                        # (e.g. DIR hello when no such file — empty list).
                        name_filter = stripped

        print(search_dir)
        try:
            entries = os.listdir(search_dir)
        except OSError:
            self._emit_error('? Directory not accessible')
            return
        if name_filter:
            entries = [
                name
                for name in entries
                if fnmatch.fnmatch(name.lower(), name_filter.lower())
            ]
        entries.sort(
            key=lambda name: (
                not os.path.isdir(os.path.join(search_dir, name)),
                name.lower(),
            )
        )
        for name in entries:
            full_path = os.path.join(search_dir, name)
            if os.path.isdir(full_path):
                print(f'<DIR>    {name}')
            else:
                print(f'         {name}')

    def save(self, filename, mode: str = 'standard'):
        """Write the program to disk.

        * ``standard`` / ``numbered`` — numbered lines as stored (``line_indent``)
        * ``pretty`` — structural indent, unnumbered (reloadable as structured source)
        * ``refs`` — same presentation as LIST REFS (GOTO targets numbered, DEF gaps)

        When *mode* is the default ``standard`` and the program was **loaded from
        unnumbered source**, SAVE uses **pretty** automatically so a LOAD → EDIT →
        SAVE round-trip keeps the file unnumbered (memory stays numbered for EDIT).
        Use ``SAVE NUMBERED`` to force classic line numbers.
        """
        try:
            path = self.resolve_path(filename)
            case_fold = self._detokenize_fold()
            mode_key = (mode or 'standard').strip().lower()
            force_numbered = mode_key in ('numbered', 'lines')
            if force_numbered:
                mode_key = 'standard'
            elif mode_key in ('ref',):
                mode_key = 'refs'
            auto_pretty = False
            # Bare SAVE (standard) after unnumbered LOAD → pretty; SAVE NUMBERED forces lines.
            if (
                mode_key == 'standard'
                and not force_numbered
                and self._program_source_numbered is False
            ):
                mode_key = 'pretty'
                auto_pretty = True
            if mode_key in ('pretty', 'refs'):
                self._apply_structural_indents()

            with open(path, 'w', encoding='utf-8') as f:
                # Portable dialect marker for non-mini (other BASICs can load the file).
                # Prefer "N REM dialect: bbc" (N>=1), not unnumbered "'" or line 0.
                from ..dialect_hint import format_save_dialect_hint, program_has_dialect_hint

                if (
                    self.config.dialect != 'mini'
                    and not program_has_dialect_hint(self.program)
                ):
                    numbered_hint = mode_key not in ('pretty',)
                    hint_line = format_save_dialect_hint(
                        self.config.dialect,
                        program_line_numbers=self.program.keys(),
                        numbered=numbered_hint,
                    )
                    if hint_line:
                        f.write(f'{hint_line}\n')

                if mode_key == 'pretty':
                    for line in self._program_display_lines(
                        'pretty',
                        include_line_numbers=False,
                        case_fold=case_fold,
                    ):
                        f.write(f'{line}\n')
                elif mode_key in ('refs', 'ref'):
                    # Match LIST REFS: numbers only on jump targets; blank line before DEF.
                    for line in self._program_display_lines(
                        'refs',
                        include_line_numbers=True,
                        case_fold=case_fold,
                    ):
                        f.write(f'{line}\n')
                else:
                    for num in sorted(self.program):
                        stmt_indent = ' ' * self.line_indent.get(num, 0)
                        f.write(
                            f'{self._format_line_number(num, True)}'
                            f'{stmt_indent}{self.format_list_line(self.program[num])}\n'
                        )

            self.loaded_filename = filename
            if auto_pretty:
                print(f'Saved: {path}  (pretty: loaded unnumbered)')
            else:
                print(f'Saved: {path}')
        except Exception as exc:
            self._emit_error(f'Save failed: {type(exc).__name__}: {exc}')

    def _kill_file(self, rest: str) -> None:
        """MS BASIC KILL — delete a file in the working directory."""
        filename = self._eval_string_arg(rest)
        path = self.resolve_path(filename)
        if not os.path.isfile(path):
            raise ValueError(f'file not found ({filename})')
        os.remove(path)

    def load(self, filename, *, announce: bool = True) -> bool:
        """Load a BASIC program from disk.

        Returns True on success. On failure prints a specific reason and returns False.
        Bare names without an extension try ``.bas`` then ``.bbc`` (see
        ``resolve_load_path``).
        """
        try:
            path = self.resolve_load_path(filename)
        except ValueError as exc:
            detail = str(exc).strip()
            if detail:
                self._emit_error(f'? LOAD filename ({detail})')
            else:
                self._emit_error('? LOAD filename')
            return False
        if not os.path.exists(path):
            # Prefer a clear message when bare name missed all candidates.
            try:
                bare = self.resolve_path(filename)
            except ValueError:
                bare = path
            _root, ext = os.path.splitext(bare)
            if not ext and path == bare:
                self._emit_error(
                    f'File not found: {path} (also tried .bas / .bbc)',
                )
            else:
                self._emit_error(f'File not found: {path}')
            return False
        if not os.path.isfile(path):
            self._emit_error(f'Not a file: {path}')
            return False
        raw_lines: List[str]
        try:
            with open(path, 'rb') as f:
                data = f.read()
        except OSError as exc:
            self._emit_error(
                f'Load failed: cannot read {path} ({type(exc).__name__}: {exc})'
            )
            return False
        except Exception as exc:
            self._emit_error(
                f'Load failed: cannot read {path} ({type(exc).__name__}: {exc})'
            )
            return False
        try:
            from ..bbc_detokenize import bbc_binary_to_source, detect_bbc_binary_format

            if detect_bbc_binary_format(data):
                raw_lines = [f'{line}\n' for line in bbc_binary_to_source(data)]
            else:
                raw_lines = data.decode('utf-8').splitlines(keepends=True)
        except UnicodeDecodeError as exc:
            self._emit_error(
                f'Load failed: {path} is not UTF-8 text or a tokenized BBC BASIC program '
                f'({exc})'
            )
            return False
        except ImportError as exc:
            self._emit_error(
                f'Load failed: cannot import bbc_detokenize while reading {path} '
                f'({exc}). Reinstall or use a full package tree.'
            )
            return False
        except Exception as exc:
            self._emit_error(
                f'Load failed: cannot decode {path} '
                f'({type(exc).__name__}: {exc})'
            )
            return False

        raw_lines, hint = split_dialect_hints(raw_lines)
        if hint is not None:
            self._apply_dialect_hint(hint, announce=announce)

        parsed = self._parse_program_file(raw_lines)
        if parsed is None:
            self._emit_error(f'Load failed: could not parse program text from {path}')
            return False
        parsed_lines, source_was_numbered = parsed
        if not parsed_lines:
            self._emit_error(f'Load failed: no program lines found in {path}')
            return False
        if not self._validate_program_dialect(
            parsed_lines, source_was_numbered, announce=announce,
        ):
            # Validator already printed dialect details when announce is True.
            if announce:
                print(f'Load aborted: dialect check failed for {path}', file=self._get_error_stream())
            return False

        self.new(announce=announce)
        self._program_source_numbered = source_was_numbered
        for line_num, statement, indent in parsed_lines:
            self.set_program_line(line_num, statement, indent)
        # SAVE without a name reuses this string. Keep a relative LOAD
        # argument (hello.bas) so working_dir still applies; only store the
        # resolved path when the user passed an absolute path.
        try:
            requested = _parse_path_arg(filename)
        except ValueError:
            requested = filename
        if requested and not os.path.isabs(requested):
            _root, ext = os.path.splitext(requested)
            if not ext:
                _p, resolved_ext = os.path.splitext(path)
                if resolved_ext:
                    requested = requested + resolved_ext
            self.loaded_filename = requested
        else:
            self.loaded_filename = path
        self._sync_display_caption(os.path.basename(path))
        if announce:
            print(f'Loaded: {path}', file=self._get_error_stream())
        self._apply_dialect_hints_from_parsed_lines(parsed_lines, announce=announce)
        already_gfx = self._display_backend_name() == 'pygame'
        self._maybe_auto_enable_pygame_display(parsed_lines, announce=announce)
        if (
            announce
            and already_gfx
            and self._program_statements_use_graphics(parsed_lines)
        ):
            print(
                f'Graphics: {os.path.basename(path)} (pygame)',
                file=self._get_error_stream(),
            )
        return True

