"""BASICInterpreter mixin: program.

Program storage, labels, line parse, and preprocess.

Auto-generated by tools/split_runtime_mixins.py — do not hand-edit bulk.
"""
# ruff: noqa: F401,F403,F405,E402,W291,W293
# Imports mirrored from monorepo runtime for method bodies.
import fnmatch
import json
import math
import random
import re
import os
import struct
import sys
import time

from ..config import DEFAULT_CONFIG, InterpreterConfig, SYSTEM_VAR_SPEC
from ..dialect_hint import DialectHint, parse_comment_dialect_line, split_dialect_hints
from ..constants import (
    CLI_EXIT_WORDS as _CLI_EXIT_WORDS,
    EXIT_HOLD_CONSOLE,
    EXPR_RESERVED_WORDS as _EXPR_RESERVED_WORDS,
    NUMERIC_BUILTIN_FUNCS as _NUMERIC_BUILTIN_FUNCS,
    NUMERIC_BUILTIN_FUNC_RE as _NUMERIC_BUILTIN_FUNC_RE,
    SAFE_EVAL_GLOBALS as _SAFE_EVAL_GLOBALS,
)
from ..expr.compile import CompiledExpr, int_slot
from ..expr.patterns import (
    RE_ARRAY_HEAD as _RE_ARRAY_HEAD,
    RE_COND_EQ as _RE_COND_EQ,
    RE_COND_NE as _RE_COND_NE,
    RE_DYNAMIC_CALL_REMAINS as _RE_DYNAMIC_CALL_REMAINS,
    RE_FILE_FUNC as _RE_FILE_FUNC,
    RE_FILE_FUNC_BBC as _RE_FILE_FUNC_BBC,
    RE_FN_CALL as _RE_FN_CALL,
    RE_FUNC_CALL as _RE_FUNC_CALL,
    RE_HAS_LETTER as _RE_HAS_LETTER,
    RE_INKEY_CALL as _RE_INKEY_CALL,
    RE_INT_DIV as _RE_INT_DIV,
    RE_MOD as _RE_MOD,
    RE_NUMERIC_FUNC_CALL as _RE_NUMERIC_FUNC_CALL,
    RE_TIME as _RE_TIME,
    RE_VAR_BASE_FULL as _RE_VAR_BASE_FULL,
    VAR_BASE_PATTERN as _VAR_BASE_PATTERN,
)

from ..format import UsingFormatter
from ..format.save_case import (
    Fold as _SaveFold,
    fold_from_save_case as _fold_from_save_case,
    format_program_line as _format_program_line_save_case,
    format_statement_part as _format_statement_part_save_case,
)
from ..repl.completion import configure_readline as _configure_repl_readline
from ..repl.help_browser import run_help_browser as _run_help_browser
from ..util import (
    basic_truth as _basic_truth,
    hard_exit as _hard_exit,
    near_equal as _near_equal,
    near_equal_sig as _near_equal_sig,
    probe_float_platform as _probe_float_platform,
)
from ..type_system import (
    ArrayStorage,
    BasicRuntimeError,
    ChainTransfer,
    DataItem,
    Dialect,
    FieldBuffer,
    FileChannel,
    FnReturn,
    CaseBlockLayout,
    CaseFrame,
    IfBlockLayout,
    IfFrame,
    ListCommand,
    LoopFrame,
    ProcReturn,
    ProgramExit,
    UserFunction,
    UserProcedure,
    VarKind,
)
from typing import Callable, Dict, List, Optional, Set, TextIO, Tuple

_SYSTEM_VAR_SPEC = SYSTEM_VAR_SPEC

       
# BBC Micro MODE specs (text grid, graphics resolution, PAR) — see bbc_modes.py.
from mini_basic.bbc_modes import bbc_mode_spec

from .helpers import (
    _get_readline_module,
    _windows_arrow_action,
    _windows_apply_arrow,
    _windows_editing_input,
    _prompt_editing_input,
    _parse_path_arg,
    _apply_pygame_display_defaults,
)

class RuntimeProgramMixin:
    """Mixin providing program-related BASICInterpreter methods."""

    @property
    def program_arg_count(self) -> int:
        return len(self.program_args)

    def _program_arg_string(self, index: float) -> str:
        slot = int(index) - 1
        if slot < 0 or slot >= len(self.program_args):
            return ''
        return self.program_args[slot]

    def _program_arg_number(self, index: float) -> float:
        text = self._program_arg_string(index).strip()
        if not text:
            return 0.0
        try:
            return float(text.replace(',', '.'))
        except ValueError:
            return 0.0

    def _get_program_stdout(self) -> TextIO:
        return self._program_stdout if self._program_stdout is not None else sys.stdout

    def _get_error_stream(self) -> TextIO:
        """Stream for diagnostics; optional override for tests."""
        err = getattr(self, '_program_stderr', None)
        return err if err is not None else sys.stderr

    @staticmethod
    def _format_exc_detail(exc: Optional[BaseException]) -> str:
        if exc is None:
            return ''
        detail = str(exc).strip()
        return detail if detail else type(exc).__name__

    def _error_message(self, prefix: str, exc: Optional[BaseException] = None) -> str:
        """Build ``? FOO`` or ``? FOO: detail`` from an optional exception."""
        detail = self._format_exc_detail(exc)
        if detail and detail not in prefix:
            return f'{prefix}: {detail}'
        return prefix

    def _emit_error(self, message: str) -> None:
        """User-facing diagnostic (? errors, dialect warnings).

        Always writes to stderr (redirect: ``2>file``). When
        ``config.errors_dual_stdout`` is True, also writes to program stdout
        so tests using ``redirect_stdout`` or ``_program_stdout`` still see it.
        """
        text = message if message.endswith('\n') else f'{message}\n'
        try:
            err = self._get_error_stream()
            err.write(text)
            err.flush()
        except Exception:
            pass
        if getattr(self.config, 'errors_dual_stdout', False):
            try:
                out = self._get_program_stdout()
                # Avoid double-write if someone pointed stderr at the same stream.
                if out is not self._get_error_stream():
                    out.write(text)
                    out.flush()
            except Exception:
                pass

    def _parse_vdu_operands(self, rest: str) -> List[int]:
        values: List[int] = []
        for part in self._split_at_depth(rest, ',', skip_empty=True):
            part = part.strip()
            if not part:
                continue
            if ';' in part:
                for word in part.split(';'):
                    word = word.strip()
                    if not word:
                        continue
                    number = int(self._eval_numeric(word))
                    values.append(number & 0xFF)
                    values.append((number >> 8) & 0xFF)
            else:
                number = int(self._eval_numeric(part))
                if number > 255:
                    values.append(number & 0xFF)
                    values.append((number >> 8) & 0xFF)
                else:
                    values.append(number & 0xFF)
        return values

    def _indent_width(self, text: str) -> int:
        return len(text.replace('\t', '    '))

    def _preserve_or_parse_indent(
        self,
        line_num: int,
        statement: str,
        *,
        fallback_line: Optional[int] = None,
    ) -> Tuple[int, str]:
        leading, body = self._split_statement_indent(statement)
        if leading > 0:
            return leading, body
        prior = self.line_indent.get(line_num)
        if prior is None and fallback_line is not None:
            prior = self.line_indent.get(fallback_line, 0)
        return prior or 0, body

    def _parse_line_number(self, line: str) -> Optional[Tuple[int, str, int]]:
        """Parse a numbered line; statement indent follows the line number (RISC OS style)."""
        raw = line.rstrip('\n')
        match = re.match(r'^[ \t]*(\d+)(.*)$', raw)
        if not match:
            return None
        line_num = int(match.group(1))
        indent, statement = self._split_statement_indent(match.group(2))
        if indent > 0:
            indent -= 1
        if not statement:
            return None
        return line_num, statement, indent

    def _parse_bare_line_number(self, line: str) -> Optional[int]:
        """Parse a line-number-only REPL entry (BBC deletes that program line)."""
        match = re.match(r'^[ \t]*(\d+)[ \t]*$', line.rstrip('\n'))
        if not match:
            return None
        return int(match.group(1))

    def set_program_line(self, line_num: int, statement: str, indent: int = 0):
        if self._program_source_numbered is None:
            self._program_source_numbered = True
        # Drop accidental C0 controls (e.g. Ctrl+S = U+0013 from console EDIT)
        # that break Python compile() on expressions like TIME >= 100.
        from .helpers import _sanitize_basic_source
        statement = _sanitize_basic_source(statement)
        # Normalize: glue type suffixes to var names.
        # Only glue $, !, # (rarely operators). Leave % alone because it is also the modulo operator.
        statement = re.sub(r'(\w)\s+([!$#]+)', r'\1\2', statement)
        statement = re.sub(r'([!$#]+)\s+(\w)', r'\1\2', statement)
        self.program[line_num] = statement
        if indent > 0:
            self.line_indent[line_num] = indent
        elif line_num in self.line_indent:
            del self.line_indent[line_num]
        self._rebuild_labels()
        self._invalidate_program_caches()
        self._definitions_dirty = True
        self._clear_stop_state()

    def delete_program_line(self, line_num: int):
        self.program.pop(line_num, None)
        self.line_indent.pop(line_num, None)
        self._rebuild_labels()
        self._invalidate_program_caches()
        self._definitions_dirty = True
        self._clear_stop_state()

    def renumber_program(self, start: int = 10, step: int = 10) -> None:
        if not self.program:
            return
        if step <= 0:
            raise ValueError('invalid RENUMBER step')
        old_lines = sorted(self.program)
        mapping: Dict[int, int] = {}
        new_num = start
        for old in old_lines:
            mapping[old] = new_num
            new_num += step

        new_program: Dict[int, str] = {}
        new_indent: Dict[int, int] = {}
        for old in old_lines:
            new_line = mapping[old]
            new_program[new_line] = self._renumber_statement(self.program[old], mapping)
            if old in self.line_indent:
                new_indent[new_line] = self.line_indent[old]

        self.program = new_program
        self.line_indent = new_indent
        self._rebuild_labels()
        self._invalidate_program_caches()
        self._clear_stop_state()

    def _invalidate_program_caches(self) -> None:
        self._if_layout_cache.clear()

    def _current_program_lines(self) -> List[Tuple[int, str, int]]:
        return [
            (line_num, self.program[line_num], self.line_indent.get(line_num, 0))
            for line_num in sorted(self.program)
        ]

    def _program_source_was_numbered(self) -> bool:
        if self._program_source_numbered is not None:
            return self._program_source_numbered
        return True

    def _parse_line_statements(self, line: str) -> List[Tuple[Optional[str], str]]:
        statements: List[Tuple[Optional[str], str]] = []
        for part in self._split_colon_statements(line):
            label, text = self._extract_label_prefix(part)
            if text and text != ';':
                statements.append((label, text))
        return statements

    def _prepare_run(self) -> None:
        self._run_line_nums = sorted(self.program.keys())
        self._run_line_index = {num: idx for idx, num in enumerate(self._run_line_nums)}
        self._run_stmts = {}
        self._run_for_next = {}
        self._run_while_wend = {}
        self._run_repeat_until = {}
        if self.config.use_run_caches:
            self._run_stmts = {
                line_num: self._parse_line_statements(text)
                for line_num, text in self.program.items()
            }
            for line_num in self._run_line_nums:
                for stmt_idx, (_, text) in enumerate(self._run_stmts[line_num]):
                    cmd, rest = self._parse_command(text)
                    if cmd == 'FOR':
                        match = self._match_for_clause(rest)
                        if match:
                            loop_var, _ = self._parse_var_token(match.group(1) + match.group(2))
                            next_stmt = self._find_matching_next_stmt_index(
                                loop_var,
                                self._run_stmts[line_num],
                                stmt_idx + 1,
                            )
                            if next_stmt >= 0:
                                self._run_for_next[(line_num, loop_var)] = line_num
                            else:
                                self._run_for_next[(line_num, loop_var)] = self._find_matching_next(
                                    loop_var, line_num, self._run_line_nums
                                )
                    elif cmd == 'WHILE':
                        self._run_while_wend[line_num] = self._find_matching_wend(
                            line_num, self._run_line_nums
                        )
                    elif cmd == 'REPEAT':
                        until_line, until_cond = self._find_matching_until(
                            line_num, self._run_line_nums
                        )
                        if until_line != -1:
                            self._run_repeat_until[line_num] = (until_line, until_cond)
        self._var_subst_int_entries = []
        self._var_subst_float_entries = []
        self._compiled_expr_cache = {}
        self._parse_command_cache = {}          # <-- add this line
        if self.config.use_compiled_exprs:
            self._warm_compiled_exprs()
        self._build_data_table()
        self._build_user_functions()
        self._build_user_procedures()
        self._definitions_dirty = False

    def _prepare_expr_for_compile(
        self,
        expr: str,
        is_condition: bool,
        *,
        allow_bitwise: bool = False,
    ) -> Tuple[str, bool, Tuple[str, ...], Tuple[str, ...], Tuple[str, ...]]:
        if self._RE_FN_CALL.search(expr):
            raise ValueError('dynamic call in expression')
        if self._RE_FUNC_CALL.search(expr):
            raise ValueError('dynamic builtin in expression')
        if self._RE_NUMERIC_FUNC_CALL.search(expr):
            raise ValueError('dynamic numeric builtin in expression')
        if self._RE_FILE_FUNC.search(expr) or self._RE_FILE_FUNC_BBC.search(expr):
            raise ValueError('dynamic file function in expression')
        if self._expr_has_boolean_syntax(expr):
            if not (allow_bitwise and self._expr_is_pure_bitwise(expr)):
                raise ValueError('boolean expression')
        if is_condition:
            expr = self._normalize_condition(expr)
        # TRUE/FALSE must become -1/0 before compile(); else Python NameError.
        expr = self._substitute_boolean_literals(expr)
        expr = self._substitute_bbc_hex_literals(expr)
        expr = self._substitute_bbc_numeric_constants(expr)
        expr = self._substitute_bbc_memory_vars(expr)
        if re.search(r'(?<![A-Za-z0-9_])@%\b', expr):
            expr = re.sub(
                r'(?<![A-Za-z0-9_])@%\b',
                str(self.bbc_at_percent),
                expr,
            )
        # Bitwise words → Python operators before int-slot rewrite.
        expr = self._normalize_operators(expr)
        needs_time = bool(self._RE_TIME.search(expr))
        if needs_time:
            expr = self._RE_TIME.sub('__basic_time__', expr)
        expr, int_vars = self._replace_int_vars_for_compile(expr)
        expr = self._canonicalize_expr_identifiers(expr)
        system_vars = self._system_vars_in_expr(expr)
        float_vars = self._extract_float_vars_for_compile(expr)
        return expr, needs_time, float_vars, int_vars, system_vars

    def _prepare_simple_comparison_for_compile(
        self, expr: str,
    ) -> Tuple[str, bool, Tuple[str, ...], Tuple[str, ...], Tuple[str, ...]]:
        expr = expr.strip()
        index = self._boolean_skip_ws(expr, 0)
        left_end = self._boolean_find_arith_end(expr, index)
        left_fragment = expr[index:left_end].strip()
        if not left_fragment:
            raise ValueError('expected expression')
        index = left_end
        index = self._boolean_skip_ws(expr, index)
        op = self._boolean_relop_at(expr, index)
        if op is None:
            raise ValueError('expected comparison operator')
        py_op = {'=': '==', '==': '==', '<>': '!=', '!=': '!='}.get(op, op)
        index += len(op)
        right_end = self._boolean_find_arith_end(expr, index)
        right_fragment = expr[index:right_end].strip()
        if not right_fragment:
            raise ValueError('expected expression')
        if self._boolean_skip_ws(expr, right_end) < len(expr):
            raise ValueError('trailing syntax')
        if (
            self._fragment_is_string_expr(left_fragment)
            or self._fragment_is_string_expr(right_fragment)
        ):
            raise ValueError('string comparison')
        left_py, needs_time_l, float_l, int_l, sys_l = self._prepare_expr_for_compile(
            left_fragment,
            False,
        )
        right_py, needs_time_r, float_r, int_r, sys_r = self._prepare_expr_for_compile(
            right_fragment,
            False,
        )
        return (
            f'({left_py}) {py_op} ({right_py})',
            needs_time_l or needs_time_r,
            tuple(dict.fromkeys(float_l + float_r)),
            tuple(dict.fromkeys(int_l + int_r)),
            tuple(dict.fromkeys(sys_l + sys_r)),
        )

    def _extract_label_prefix(self, part: str) -> Tuple[Optional[str], str]:
        match = re.match(rf'^({self._VAR_BASE_PATTERN}):\s*(.*)$', part.strip())
        if match and not self._is_statement_keyword(match.group(1)):
            return self._normalize_identifier(match.group(1)), match.group(2).strip()
        return None, part.strip()

    def _rebuild_labels(self):
        self.labels.clear()
        for line_num in sorted(self.program):
            parts = self._split_colon_statements(self.program[line_num])
            if not parts:
                continue
            label, _ = self._extract_label_prefix(parts[0])
            if label:
                self.labels[label] = line_num

    def _program_statements_use_graphics(
        self,
        parsed_lines: List[Tuple[int, str, int]],
    ) -> bool:
        for _, statement, _ in parsed_lines:
            for part in self._split_colon_statements(statement):
                _, text = self._extract_label_prefix(part)
                if not text:
                    continue
                cmd, _ = self._parse_command(text)
                if cmd in self._GRAPHICS_CMDS:
                    return True
                # For bbc dialect, CLS / MODE / VDU / CLG / COLOUR etc. auto-enable pygame
                # (to support BBC screen programs). Pure PRINT-only text programs stay terminal.
                if self.config.dialect == 'bbc' and cmd in self._BBC_DISPLAY_CMDS:
                    return True
        return False

    def _maybe_auto_enable_pygame_from_program(self, *, announce: bool = True) -> None:
        """RUN: enable pygame when the loaded/typed program needs a display."""
        if not self.program:
            return
        parsed_lines = [
            (line_num, statement, self.line_indent.get(line_num, 0))
            for line_num, statement in sorted(self.program.items())
        ]
        self._maybe_auto_enable_pygame_display(parsed_lines, announce=announce)

    def _scan_statement_dialect_violations(self, statement: str) -> List[str]:
        violations: List[str] = []
        for part in self._split_colon_statements(statement):
            _, text = self._extract_label_prefix(part)
            if not text:
                continue
            stripped = text.strip()
            if self._RE_ON_ERROR.match(stripped):
                if not self._dialect_allows('on_error_goto'):
                    violations.append('on_error_goto')
                continue
            on_match = self._RE_ON_GOTO_GOSUB.match(stripped)
            if on_match:
                if not self._dialect_allows('on_goto_gosub'):
                    violations.append('on_goto_gosub')
                continue
            cmd, rest = self._parse_command(text)
            if cmd in self._MITS_FORBIDDEN_CMDS and not self._dialect_allows(cmd):
                violations.append(cmd)
            if cmd in self._MINI_ONLY_CMDS and not self._dialect_allows(cmd):
                violations.append(cmd.lower())
            if cmd == 'DEF' and not re.search(r'\)\s*=', rest):
                if not self._dialect_allows('multiline_def'):
                    violations.append('multiline_def')
            if cmd == 'IF':
                if self._match_if_goto(rest) and not self._dialect_allows('if_goto'):
                    violations.append('if_goto')
                elif self._if_rest_uses_then_line_jump(rest):
                    violations.append('if_then_line')
            upper = text.upper()
            for func in self._MINI_ONLY_FUNCS:
                if re.search(rf'\b{re.escape(func)}\b', upper):
                    if not self._dialect_allows(func):
                        violations.append(func)
        return violations

    @classmethod
    def _normalize_hash_file_commands(cls, line: str) -> str:
        """BBC file I/O: PRINT #ch  INPUT #ch  CLOSE #ch  ->  PRINT#ch etc."""
        return cls._RE_HASH_FILE_CMD.sub(r'\1#', line.strip())

    @staticmethod
    def _normalize_bbc_dialect_line(line: str) -> str:
        """BBC BASIC for SDL 2.0 uses compound closers (ENDIF, ENDWHILE, …).

        Normalize SDL spellings to the internal forms mini_basic executes
        (WEND, EXIT FOR/WHILE/REPEAT). Do not map bare BREAK → EXIT FOR:
        that wrongly exits a FOR when the author meant to leave a WHILE.
        """
        # Pasted split forms still run in mini_basic; SDL TouchIDE expects one word.
        line = re.sub(r'\bEND\s+IF\b', 'ENDIF', line, flags=re.IGNORECASE)
        line = re.sub(r'\bEND\s+WHILE\b', 'ENDWHILE', line, flags=re.IGNORECASE)
        line = re.sub(r'\bEND\s+PROC\b', 'ENDPROC', line, flags=re.IGNORECASE)
        line = re.sub(r'\bEND\s+CASE\b', 'ENDCASE', line, flags=re.IGNORECASE)
        line = re.sub(r'\bEND\s+FN\b', 'END DEF', line, flags=re.IGNORECASE)
        line = re.sub(r'\bEND\s+DEF\b', 'END DEF', line, flags=re.IGNORECASE)
        # Internal loop end is WEND; ENDWHILE is the SDL-facing spelling.
        line = re.sub(r'\bENDWHILE\b', 'WEND', line, flags=re.IGNORECASE)
        # Crunched BBC: PRINTTAB(x) / PRINTSPC(n) → PRINT TAB(x) / PRINT SPC(n)
        # (hanoi PROCPUT uses PRINTTAB(...); glued form is not a valid keyword).
        line = re.sub(r'\bPRINTTAB\b', 'PRINT TAB', line, flags=re.IGNORECASE)
        line = re.sub(r'\bPRINTSPC\b', 'PRINT SPC', line, flags=re.IGNORECASE)
        line = re.sub(r'\bPRINTCHR\$\b', 'PRINT CHR$', line, flags=re.IGNORECASE)
        # DEFPROCname / DEFPROCname( → DEF PROC name
        line = re.sub(r'\bDEFPROC\b', 'DEF PROC', line, flags=re.IGNORECASE)
        line = re.sub(r'\bDEFPROC(?=[A-Za-z])', 'DEF PROC ', line, flags=re.IGNORECASE)
        # REPEATUNTILTIME… (welcome) — \b after REPEATUNTIL fails when TIME follows
        line = re.sub(
            r'\bREPEATUNTIL(?=[A-Za-z_])',
            'REPEAT UNTIL ',
            line,
            flags=re.IGNORECASE,
        )
        line = re.sub(r'\bREPEATUNTIL\b', 'REPEAT UNTIL', line, flags=re.IGNORECASE)
        line = re.sub(r'\bREPEAT(?=UNTIL)', 'REPEAT ', line, flags=re.IGNORECASE)
        line = re.sub(r'\bREPEAT\s+UNTIL\b', 'REPEAT UNTIL', line, flags=re.IGNORECASE)
        # UNTILTIME>… / UNTIL TIME
        line = re.sub(r'\bUNTIL(?=[A-Za-z_])', 'UNTIL ', line, flags=re.IGNORECASE)
        # 0TO20 / 0STEP2 — only after digit/%/) so TOTAL is not split
        line = re.sub(r'(?<=[0-9%)])TO(?=[0-9A-Za-z_(+-])', ' TO ', line, flags=re.IGNORECASE)
        line = re.sub(r'(?<=[0-9%)])STEP(?=[0-9A-Za-z_(+-])', ' STEP ', line, flags=re.IGNORECASE)
        # Crunched keywords — only outside string literals (filters: "Original"
        # must not become ORIGIN al).
        def _glue_outside_strings(text: str) -> str:
            parts: List[str] = []
            i = 0
            n = len(text)
            while i < n:
                if text[i] == '"':
                    j = i + 1
                    while j < n:
                        if text[j] == '"':
                            if j + 1 < n and text[j + 1] == '"':
                                j += 2
                                continue
                            j += 1
                            break
                        j += 1
                    parts.append(text[i:j])
                    i = j
                    continue
                j = i
                while j < n and text[j] != '"':
                    j += 1
                chunk = text[i:j]
                # Digits/parens only — ORIGIN0, SOUND1 (never "Original")
                for kw in (
                    'ORIGIN', 'SOUND', 'ENVELOPE', 'CLG', 'CLS', 'RESTORE',
                    'UNTIL', 'COLOUR', 'COLOR',
                ):
                    chunk = re.sub(
                        rf'\b{kw}(?=[0-9(])',
                        rf'{kw} ',
                        chunk,
                        flags=re.IGNORECASE,
                    )
                # May glue onto idents: MODE5, MOVEI%, FORI%=, GCOL0, PLOT69
                for kw in (
                    'MODE', 'GCOL', 'VDU', 'PLOT', 'MOVE', 'DRAW',
                    'FOR', 'NEXT', 'PRINT', 'INPUT',
                ):
                    chunk = re.sub(
                        rf'\b{kw}(?=[0-9A-Za-z$%(])',
                        rf'{kw} ',
                        chunk,
                        flags=re.IGNORECASE,
                    )
                # PROC calls: PROCSWOOSH( — protect ENDPROC
                chunk = re.sub(
                    r'\bENDPROC\b', '\x00ENDPROC\x00', chunk, flags=re.IGNORECASE,
                )
                chunk = re.sub(
                    r'\bPROC(?=[A-Za-z])', 'PROC ', chunk, flags=re.IGNORECASE,
                )
                chunk = chunk.replace('\x00ENDPROC\x00', 'ENDPROC')
                chunk = re.sub(
                    r'\bINKEY(\d+)\b', r'INKEY(\1)', chunk, flags=re.IGNORECASE,
                )
                parts.append(chunk)
                i = j
            return ''.join(parts)

        return _glue_outside_strings(line)

    @staticmethod
    def _normalize_two_word_closers(line: str) -> str:
        """Accept END IF / END WHILE / END FN / END PROC as two-word aliases."""
        text = line.strip()
        core = re.split(r'\s+REM(?:\s|$)', text, maxsplit=1, flags=re.IGNORECASE)[0].rstrip()
        match = re.match(
            r'^END\s+(IF|WHILE|PROC|FN|DEF|CASE)\s*$',
            core,
            re.IGNORECASE,
        )
        if not match:
            return line
        aliases = {
            'IF': 'ENDIF',
            'WHILE': 'WEND',
            'PROC': 'ENDPROC',
            'FN': 'END DEF',
            'DEF': 'END DEF',
            'CASE': 'ENDCASE',
        }
        return aliases[match.group(1).upper()]

    def _parse_command(self, line: str) -> Tuple[str, str]:
        cache_key = line
        cached = self._parse_command_cache.get(cache_key)
        if cached is not None:
            return cached
        line = self._normalize_hash_file_commands(line.strip())
        line = re.sub(r'^CHAIN(?=["\w])', 'CHAIN ', line, flags=re.IGNORECASE)
        line = re.sub(r'\bCIRCLEFILL\b', 'CIRCLE FILL', line, flags=re.IGNORECASE)
        if self.config.dialect == 'bbc':
            line = self._normalize_bbc_dialect_line(line)
        else:
            line = re.sub(r'\bENDWHILE\b', 'WEND', line, flags=re.IGNORECASE)
            line = self._normalize_two_word_closers(line)
        line = self._expand_question_print(line)
        proc_match = self._RE_PROC_CALL.match(line)
        if proc_match:
            name = proc_match.group(1)
            args = proc_match.group(2)
            rest = name if args is None else f'{name}({args})'
            result = ('PROC', rest)
            self._parse_command_cache[cache_key] = result
            return result
        if self.config.dialect == 'bbc':
            match = self._RE_PARSE_CMD_BBC.match(line)
        else:
            match = self._RE_PARSE_CMD.match(line)
        if match:
            cmd_text = match.group(1)
            cmd_end = match.start(1) + len(cmd_text)
            if cmd_end < len(line):
                nextch = line[cmd_end]
                if nextch.isalnum() or nextch == '_':
                    glued = line[cmd_end:]
                    # Allow some crunched forms for classic string functions:
                    # PRINTCHR$(84) sometimes worked (the ( reveals the function call)
                    # but PRINTCHR$84 (no parens) almost always syntax error.
                    if re.match(r'(CHR\$|ASC|LEFT\$|RIGHT\$|MID\$|STR\$|INKEY\$)\(', glued, re.IGNORECASE):
                        pass  # crunched PRINTCHR$(84) tolerated in some 80s BASICs
                    elif re.match(r'(CHR\$|ASC|LEFT\$|RIGHT\$|MID\$|STR\$|INKEY\$)\s*\d', glued, re.IGNORECASE):
                        # bare numeric without () after $ , e.g. PRINTCHR$84 → error
                        if cmd_text not in self._GLUABLE_AFTER_KEYWORDS:
                            match = None
                    elif cmd_text.upper() in ('REM', 'DATA'):
                        # REM/DATA: rest of line is payload (REMM, REMARK, DATA1, …)
                        pass
                    elif cmd_text not in self._GLUABLE_AFTER_KEYWORDS and not cmd_text.endswith('#'):
                        # standard case: no space after PRINT etc. is error in most classic BASICs
                        # but do not invalidate PRINT#N, INPUT# etc. (the regex captures PRINT# as the cmd)
                        match = None
        if match:
            cmd = match.group(1).upper()
            if cmd == 'ELIF':
                cmd = 'ELSEIF'
            result = (cmd, match.group(2))
            self._parse_command_cache[cache_key] = result
            return result
        result = ('', line.strip())
        self._parse_command_cache[cache_key] = result
        return result

    def _parse_case_header(self, rest: str) -> str:
        match = re.match(r'^(.+?)\s+OF\s*$', rest.strip(), re.IGNORECASE)
        if not match:
            raise ValueError('CASE needs OF')
        return match.group(1).strip()

    def _parse_otherwise_spec(self, rest: str) -> Tuple[str, Optional[str]]:
        text = rest.strip()
        if_match = re.match(r'^IF\s+(.+?)\s+THEN\s*$', text, re.IGNORECASE)
        if if_match:
            return f'IF {if_match.group(1).strip()}', None
        head, tail = self._split_first_at_depth(text, ':')
        if head:
            return head, tail or None
        if text:
            return text, None
        return '', None

    def _parse_string_literal(self, expr: str) -> str:
        return self._decode_string_literal(expr)

    def _normalize_identifier(self, name: str) -> str:
        if not name:
            return name
        # Parse base name + optional type suffix ($ % ! #)
        m = re.match(rf'^({self._VAR_BASE_PATTERN})([%$!#]?)', name)
        if not m:
            return name
        base, suffix = m.groups()
        sig_len = self._var_significant_length()
        if self._identifiers_case_sensitive():
            norm_base = base
        else:
            norm_base = base.upper()
        if sig_len > 0 and len(norm_base) > sig_len:
            norm_base = norm_base[:sig_len]
        return norm_base + suffix

    def _normalize_for_rest(self, rest: str) -> str:
        """Space TO/STEP when glued (BBC style and quick typing: ``1TO100``, ``1toN``, ``N TO 10``).

        Never rewrite the loop variable (text before the first ``=``), so names like
        ``to0`` / ``step3`` stay intact. In case-sensitive dialects, only uppercase
        ``TO`` / ``STEP`` are keywords — lowercase ``to`` / ``to0`` are identifiers.
        """
        text = rest.strip()
        eq = text.find('=')
        if eq >= 0:
            head, tail = text[: eq + 1], text[eq + 1 :]
        else:
            head, tail = '', text

        case_sensitive = False
        try:
            case_sensitive = bool(self._identifiers_case_sensitive())
        except Exception:
            case_sensitive = False

        if case_sensitive:
            # Keywords only in uppercase; leave lowercase identifiers (to, to0, step3).
            tail = re.sub(r'(?<=[0-9)])(TO|STEP)', r' \1 ', tail)
            tail = re.sub(r'(?<![A-Za-z0-9_])(TO|STEP)(?=[0-9(])', r' \1 ', tail)
            tail = re.sub(r'(?<![A-Za-z0-9_])(TO|STEP)(?![A-Za-z0-9_])', r' \1 ', tail)
            tail = re.sub(r'(?<=[0-9])\s*(TO|STEP)\s*(?=-?[0-9])', r' \1 ', tail)
        else:
            # Fold mode: never rewrite variable head; only unglue in the range tail.
            flags = re.IGNORECASE
            tail = re.sub(r'(?<=[0-9)])(TO|STEP)', r' \1 ', tail, flags=flags)
            # ``TO10`` / ``TO(`` after space or operator — not mid-name like ``total``.
            tail = re.sub(
                r'(?<=[\s=+\-*/,(])(TO|STEP)(?=[0-9(])',
                r' \1 ',
                tail,
                flags=flags,
            )
            tail = re.sub(r'\b(TO|STEP)\b', r' \1 ', tail, flags=flags)
            tail = re.sub(
                r'(?<=[0-9])\s*(TO|STEP)\s*(?=-?[0-9])',
                r' \1 ',
                tail,
                flags=flags,
            )

        text = head + tail
        return re.sub(r'\s+', ' ', text).strip()

    def _parse_var_token(self, token: str) -> Tuple[str, VarKind]:
        token = token.strip()
        # tolerate whitespace before type suffix, e.g. "n %" or "s $"
        token = re.sub(r'\s+([%$!#]+)$', r'\1', token)
        # Support BBCSDL record structure variables: obj.member% , obj.sub.name$ , obj.x etc.
        # Use full dotted+suffix as the storage key for uniqueness (x vs x% on same struct).
        if '.' in token and not token.startswith('.'):
            # Match optional suffix only at end; member names can have the suffix attached after dot.
            m = re.match(r'^(.+?)(%%|%|\$\$|\$|!|#)?$', token)
            if m:
                dotted = m.group(1)
                suf = m.group(2) or ''
                if '.' in dotted:
                    full_key = dotted + suf
                    if suf in ('$$', '$'):
                        return full_key, 'str'
                    if suf in ('%%', '%'):
                        return full_key, 'int'
                    if suf in ('!', '#'):
                        return full_key, 'float'
                    # bare last member (no suffix) -> float by default
                    return full_key, 'float'
        if token.endswith('$$'):
            return self._validate_var_base(token[:-2]), 'str'
        if token.endswith('$'):
            return self._validate_var_base(token[:-1]), 'str'
        # BBCSDL / BB4W: %% = 64-bit integer (distinct from 32-bit %).
        # Storage key keeps the suffix so a% and a%% do not collide.
        if token.endswith('%%'):
            return self._validate_var_base(token[:-2]) + '%%', 'int'
        if token.endswith('%'):
            return self._validate_var_base(token[:-1]), 'int'
        # BBCSDL byte scalar/array type suffix
        if token.endswith('&'):
            return self._validate_var_base(token[:-1]), 'int'
        if token.endswith('!') or token.endswith('#'):
            return self._validate_var_base(token[:-1]), 'float'
        base = self._validate_var_base(token)
        return base, self.default_var_types.get(base[0].upper(), 'float')

    def _parse_param_token(self, token: str) -> Tuple[str, VarKind, bool]:
        token = token.strip()
        match = re.match(
            rf'^({self._VAR_BASE_PATTERN})(%%|%|\$|!|#|&)?\s*\(\s*\)\s*$',
            token,
            flags=re.IGNORECASE,
        )
        if match:
            base = self._validate_var_base(match.group(1))
            return base, self._array_kind_from_suffix(match.group(2) or ''), True
        name, kind = self._parse_var_token(token)
        return name, kind, False

    def _parse_array_ref(self, token: str) -> Tuple[str, VarKind]:
        token = token.strip()
        match = re.match(
            rf'^({self._VAR_BASE_PATTERN})(%%|%|\$|!|#|&)?\s*\(\s*\)\s*$',
            token,
            flags=re.IGNORECASE,
        )
        if not match:
            raise ValueError('expected array reference')
        base = self._validate_var_base(match.group(1))
        return base, self._array_kind_from_suffix(match.group(2))

    def _parse_array_lvalue(self, token: str) -> Optional[Tuple[str, VarKind, str]]:
        token = token.strip()
        match = re.match(
            rf'^({self._VAR_BASE_PATTERN})([%$!#&]?)\s*\((.*)\)\s*$',
            token,
        )
        if not match:
            return None
        base = self._validate_var_base(match.group(1))
        suffix = match.group(2)
        kind: VarKind = 'float'
        if suffix == '$':
            kind = 'str'
        elif suffix in ('%', '&'):
            kind = 'int'
        return base, kind, match.group(3).strip()

    def _parse_data_item(self, token: str) -> DataItem:
        # BBC DATA keeps trailing spaces in unquoted strings (e.g. article "a ").
        token = token.lstrip()
        if not token:
            return DataItem('str', '')
        if token[0] == '"':
            return DataItem('str', self._decode_string_literal(token))
        if re.fullmatch(r'[-+]?\d+\.?\d*', token):
            return DataItem('float', float(token))
        if token.startswith('&'):
            return DataItem('float', float(int(token[1:], 16)))
        if token.startswith('%') and len(token) > 1 and set(token[1:]) <= {'0', '1'}:
            return DataItem('float', float(int(token[1:], 2)))
        if '\\' in token:
            return DataItem('str', token)
        normalized = self._normalize_operators(token)
        try:
            return DataItem('float', float(eval(normalized, _SAFE_EVAL_GLOBALS, {})))
        except Exception:
            return DataItem('str', token)

    def _build_data_table(self) -> None:
        self.data_items = []
        self.data_line_starts = {}
        self._data_lines_ordered = []
        self._data_locations = []
        for line_num in self._run_line_nums:
            stmt_parts = self._run_stmts.get(line_num)
            if stmt_parts is None:
                stmt_parts = self._parse_line_statements(self.program[line_num])
            for stmt_index, (_, text) in enumerate(stmt_parts):
                cmd, rest = self._parse_command(text)
                if cmd != 'DATA':
                    continue
                pointer = len(self.data_items)
                self.data_line_starts[line_num] = pointer
                self._data_lines_ordered.append(line_num)
                self._data_locations.append((line_num, stmt_index, pointer))
                for item in self._split_at_depth(rest, ',', preserve_trailing=True):
                    self.data_items.append(self._parse_data_item(item))

    def _scan_user_functions(
        self,
        line_nums: List[int],
    ) -> Tuple[Dict[str, UserFunction], Set[int]]:
        functions: Dict[str, UserFunction] = {}
        skip_lines: Set[int] = set()
        idx = 0
        while idx < len(line_nums):
            line_num = line_nums[idx]
            stmt_parts = self._run_stmts.get(line_num)
            if stmt_parts is None:
                stmt_parts = self._parse_line_statements(self.program[line_num])
            handled = False
            for _, text in stmt_parts:
                cmd, rest = self._parse_command(text)
                if cmd != 'DEF':
                    continue
                rest_strip = rest.strip()
                # DEFINT/DEFSNG/DEFDBL/DEFSTR — type defaults, not DEF FN.
                if re.match(r'^(INT|SNG|DBL|STR)\b', rest_strip, re.IGNORECASE):
                    break
                # Skip DEF PROC (including same-line body: DEF PROCx(...) IF … ENDPROC).
                if self._RE_DEF_PROC.match(rest_strip):
                    break
                try:
                    self._parse_def_proc_header(rest_strip)
                    break
                except ValueError:
                    pass
                if re.search(r'\)\s*=', rest):
                    try:
                        fn = self._parse_def_fn_rest(rest)
                        functions[fn.name] = fn
                    except Exception as exc:
                        self._emit_error(
                            self._error_message(
                                f'? DEF FN error at line {line_num}', exc
                            )
                        )
                    break
                try:
                    fn = self._parse_def_fn_header(rest)
                except Exception as exc:
                    self._emit_error(
                        self._error_message(
                            f'? DEF FN header error at line {line_num}', exc
                        )
                    )
                    break
                end_line = self._find_matching_end_def(line_num, line_nums)
                if end_line is None:
                    equals_return = self._find_def_fn_equals_return(line_num, line_nums)
                    if equals_return is not None:
                        equals_line, expr = equals_return
                        fn.body = expr
                        self._maybe_infer_fn_return_kind(fn, rest, expr)
                        functions[fn.name] = fn
                        end_idx = self._line_index(equals_line, line_nums)
                        for skip_idx in range(idx, end_idx + 1):
                            skip_lines.add(line_nums[skip_idx])
                        idx = end_idx
                        handled = True
                        break
                    acorn_body = self._find_def_fn_acorn_multiline_body(
                        line_num,
                        line_nums,
                    )
                    if acorn_body is not None:
                        fn.body_start, fn.body_end = acorn_body
                        fn.multiline = True
                        return_expr = self._find_last_fn_body_return_expr(
                            fn.body_start,
                            fn.body_end,
                            line_nums,
                        )
                        self._maybe_infer_fn_return_kind(fn, rest, return_expr)
                        functions[fn.name] = fn
                        end_idx = max(
                            body_idx
                            for body_idx, body_line in enumerate(line_nums)
                            if fn.body_start <= body_line < fn.body_end
                        )
                        for skip_idx in range(idx, end_idx + 1):
                            skip_lines.add(line_nums[skip_idx])
                        idx = end_idx
                        handled = True
                        break
                    self._hint_def_fn_close_keyword(line_num, line_nums)
                    break
                if idx + 1 >= len(line_nums):
                    break
                end_idx = self._line_index(end_line, line_nums)
                fn.multiline = True
                fn.body_start = line_nums[idx + 1]
                fn.body_end = end_line
                return_expr = self._find_last_fn_body_return_expr(
                    fn.body_start,
                    fn.body_end,
                    line_nums,
                )
                self._maybe_infer_fn_return_kind(fn, rest, return_expr)
                functions[fn.name] = fn
                for skip_idx in range(idx, end_idx + 1):
                    skip_lines.add(line_nums[skip_idx])
                idx = end_idx
                handled = True
                break
            if not handled:
                idx += 1
        return functions, skip_lines

    def _scan_user_procedures(
        self,
        line_nums: List[int],
    ) -> Tuple[Dict[str, UserProcedure], Set[int]]:
        procedures: Dict[str, UserProcedure] = {}
        skip_lines: Set[int] = set()
        idx = 0
        while idx < len(line_nums):
            line_num = line_nums[idx]
            stmt_parts = self._run_stmts.get(line_num)
            if stmt_parts is None:
                stmt_parts = self._parse_line_statements(self.program[line_num])
            handled = False
            for _, text in stmt_parts:
                cmd, rest = self._parse_command(text)
                if cmd != 'DEF':
                    continue
                try:
                    proc = self._parse_def_proc_header(rest)
                except Exception:
                    break
                end_line = self._find_matching_endproc(line_num, line_nums)
                # Single-line DEF PROC … ENDPROC (header_stmt may hold the body).
                if end_line == line_num or (
                    end_line is None
                    and re.search(r'\bENDPROC\b', rest, re.IGNORECASE)
                ):
                    proc.body_start = line_num
                    proc.body_end = line_num
                    # Body already in header_stmt; no multi-line range.
                    if not proc.header_stmt and re.search(
                        r'\)\s*(.+)$', rest.strip()
                    ):
                        pass
                    procedures[proc.name] = proc
                    skip_lines.add(line_num)
                    handled = True
                    break
                if end_line is None or idx + 1 >= len(line_nums):
                    break
                end_idx = self._line_index(end_line, line_nums)
                proc.body_start = line_nums[idx + 1]
                proc.body_end = end_line
                procedures[proc.name] = proc
                for skip_idx in range(idx, end_idx + 1):
                    skip_lines.add(line_nums[skip_idx])
                idx = end_idx
                handled = True
                break
            if not handled:
                idx += 1
        return procedures, skip_lines

    def _refresh_user_definitions_from_program(self) -> None:
        line_nums = sorted(self.program.keys())
        if not line_nums:
            # Empty program: keep immediate DEF FN/PROC from REPL (do not wipe).
            self._definitions_dirty = False
            return
        procedures, _ = self._scan_user_procedures(line_nums)
        self.user_procedures = procedures
        functions, _ = self._scan_user_functions(line_nums)
        self.user_functions = functions
        self._definitions_dirty = False

    def _build_user_functions(self) -> None:
        self.user_functions = {}
        self._fn_skip_lines = set()
        # Always scan the full program for DEF FN, even if they appear after END
        # or in parts not in current run_line_nums (BBCSDL style: defs after END are ok)
        full_line_nums = sorted(self.program.keys())
        functions, skip_lines = self._scan_user_functions(full_line_nums)
        self.user_functions = functions
        self._finalize_fn_return_kinds()
        self._warn_def_fn_missing_returns()
        self._fn_skip_lines = skip_lines
        if self._fn_skip_lines:
            self._run_line_nums = [
                num for num in self._run_line_nums if num not in self._fn_skip_lines
            ]
            self._run_line_index = {
                num: index for index, num in enumerate(self._run_line_nums)
            }

    def _build_user_procedures(self) -> None:
        # Always scan full program for PROC defs too
        full_line_nums = sorted(self.program.keys())
        procedures, skip_lines = self._scan_user_procedures(full_line_nums)
        self.user_procedures = procedures
        self._proc_skip_lines = skip_lines
        if self._proc_skip_lines:
            self._run_line_nums = [
                num for num in self._run_line_nums if num not in self._proc_skip_lines
            ]
            self._run_line_index = {
                num: index for index, num in enumerate(self._run_line_nums)
            }

    def _parse_proc_call(self, rest: str) -> Tuple[str, List[str]]:
        match = re.match(
            rf'^({self._VAR_BASE_PATTERN})\s*(?:\((.*)\))?$',
            rest.strip(),
            flags=re.IGNORECASE,
        )
        if not match:
            raise ValueError('invalid PROC call')
        name = self._normalize_identifier(match.group(1))
        args_text = match.group(2)
        args = self._split_args(args_text) if args_text and args_text.strip() else []
        return name, args

    def _prepare_return_expr_no_fn(self, expr: str) -> str:
        expr = self._expand_inkey_calls(expr)
        expr = self._expand_numeric_builtin_calls(expr)
        expr = self._expand_builtin_calls(expr)
        expr = self._expand_file_calls(expr)
        expr = self._substitute_variables(expr)
        if not self._RE_FN_CALL.search(expr):
            expr = self._substitute_array_references(expr)
        return expr

    def _parse_hash_channel_arg(self, expr: str, start: int) -> Tuple[Optional[str], int]:
        pos = start
        while pos < len(expr) and expr[pos].isspace():
            pos += 1
        if pos >= len(expr):
            return None, start
        if expr[pos] == '(':
            end = self._match_paren(expr, pos)
            return expr[pos + 1:end], end + 1
        var_match = re.match(
            rf'^({self._VAR_BASE_PATTERN})([%$!#]?)',
            expr[pos:],
            self._identifier_re_flags(),
        )
        if var_match:
            return var_match.group(1) + var_match.group(2), pos + var_match.end()
        num_match = re.match(r'^-?\d+\.?\d*', expr[pos:])
        if num_match:
            return num_match.group(0), pos + num_match.end()
        return None, start

    def _parse_array_subscript_ranges(self, indices_expr: str) -> List[Tuple[int, int]]:
        ranges: List[Tuple[int, int]] = []
        for part in self._split_args(indices_expr):
            to_match = re.match(
                r'^(.+?)\s*TO\s*(.+)$',
                part.strip(),
                flags=re.IGNORECASE,
            )
            if to_match:
                start = int(self._eval_numeric(to_match.group(1)))
                end = int(self._eval_numeric(to_match.group(2)))
                if end < start:
                    start, end = end, start
                ranges.append((start, end))
            else:
                index = int(self._eval_numeric(part.strip()))
                ranges.append((index, index))
        return ranges

    def _normalize_operators(self, expr: str) -> str:
        if self._RE_BAD_PERCENT_MOD.search(expr):
            raise ValueError(
                "'%' is reserved for integer variable suffixes (A%) and binary literals (%1010); use MOD for modulo"
            )
        # Glued BBC operators after a number/paren or integer suffix:
        #   10MOD3, 18MOD 12 (Clock HOUR24%MOD after sub), (1+2)DIV5
        #   0AND1 / 0DIV2 after A%→0 substitution (welcome K%=68+(A%AND1))
        #   (500+32-0)DIVM8 — \b after DIV fails (M continues the word); use
        #   lookahead for digit/ident/paren instead of trailing \b.
        # Require lookbehind digit/paren so AMOD / XMOD stay identifiers.
        expr = re.sub(
               r'(?:(?<![A-Za-z0-9_])(\d+)|(\)))(MOD|DIV|AND|OR|EOR|XOR)(?=\s|[0-9A-Za-z_(]|$)',
               lambda m: (m.group(1) or m.group(2)) + ' ' + m.group(3) + ' ',
               expr,
               flags=re.IGNORECASE,
        )
        # Welcome / Clock: A%AND1, A%DIV2, HOUR24%MOD 12 before var substitution
        # (no \b after AND — digit continues the word in Python \w)
        expr = re.sub(
            r'%(?=(?:AND|OR|EOR|XOR|DIV|MOD)(?![A-Za-z_]))',
            '% ',
            expr,
            flags=re.IGNORECASE,
        )
        # AND1 / DIV2 / MOD12 when op glued to a digit operand
        expr = re.sub(
            r'\b(AND|OR|EOR|XOR|DIV|MOD)(?=\d)',
            r'\1 ',
            expr,
            flags=re.IGNORECASE,
        )
        # INKEY1 in expressions (assignment D%=INKEY1)
        expr = re.sub(r'\bINKEY(\d+)\b', r'INKEY(\1)', expr, flags=re.IGNORECASE)
        expr = self._RE_MOD.sub('%', expr)
        expr = re.sub(r'\bDIV\b', '//', expr, flags=re.IGNORECASE)
        expr = self._RE_INT_DIV.sub('//', expr)
        expr = re.sub(r'\^', '**', expr)
        # Bitwise for numbers in BBC-style (AND/OR/XOR/NOT on ints); logical AND/OR for conditions handled in separate paths
        # Glued unary NOT (saucer: PLOT 69,NOTX,Y) must split before \bNOT\b → ~
        expr = re.sub(r'\bNOT(?=[A-Za-z_(])', 'NOT ', expr, flags=re.IGNORECASE)
        expr = re.sub(r'\bAND\b', '&', expr, flags=re.IGNORECASE)
        expr = re.sub(r'\bOR\b', '|', expr, flags=re.IGNORECASE)
        expr = re.sub(r'\bXOR\b', '^', expr, flags=re.IGNORECASE)
        expr = re.sub(r'\bNOT\b', '~', expr, flags=re.IGNORECASE)
        expr = re.sub(r'\bEOR\b', '^', expr, flags=re.IGNORECASE)
        return self._expand_shift_operators(expr)

    def _boolean_parse_arith(self, expr: str, index: int) -> Tuple[float, int]:
        index = self._boolean_skip_ws(expr, index)
        end = self._boolean_find_arith_end(expr, index)
        fragment = expr[index:end].strip()
        if not fragment:
            raise ValueError('expected expression')
        return self._eval_arith_core(fragment), end

    def _boolean_parse_comparison(self, expr: str, index: int) -> Tuple[float, int]:
        index = self._boolean_skip_ws(expr, index)

        if index < len(expr) and expr[index] == '(':
            end = self._match_paren(expr, index)
            if end >= 0:
                inner = expr[index + 1:end]
                # Is this whole parenthesized thing a boolean expression?
                if self._boolean_relop_at(inner, self._boolean_find_arith_end(inner, 0)) is not None:
                    value = self._eval_bbc_boolean_expr(inner)
                    return value, end + 1

        left_end = self._boolean_find_arith_end(expr, index)
        left_fragment = expr[index:left_end].strip()
        self.dprint("LEFT =", repr(left_fragment))
        self.dprint("NEXT =", repr(expr[left_end:left_end+10]))

        if not left_fragment:
            raise ValueError('expected expression')
        left_kind, left_value = self._eval_comparison_operand(left_fragment)
        index = left_end
        index = self._boolean_skip_ws(expr, index)
        op = self._boolean_relop_at(expr, index)
        if op is None:
            if left_kind == 'str':
                return (-1 if left_value else 0), index
            return left_value, index
        index += len(op)
        right_end = self._boolean_find_arith_end(expr, index)
        right_fragment = expr[index:right_end].strip()
        if not right_fragment:
            raise ValueError('expected expression')
        right_kind, right_value = self._eval_comparison_operand(right_fragment)
        index = right_end
        return self._compare_mixed_values(op, left_kind, left_value, right_kind, right_value), index

    def _boolean_parse_not(self, expr: str, index: int) -> Tuple[float, int]:
        index = self._boolean_skip_ws(expr, index)
        if self._boolean_keyword_at(expr, index, 'NOT'):
            index += 3
            value, index = self._boolean_parse_not(expr, index)
            return self._bbc_bitwise_not(value), index
        return self._boolean_parse_comparison(expr, index)

    def _boolean_parse_and(self, expr: str, index: int) -> Tuple[float, int]:
        left, index = self._boolean_parse_not(expr, index)
        self.dprint(f"AND: left={left} index={index}")
        while True:
            index = self._boolean_skip_ws(expr, index)
            if not self._boolean_keyword_at(expr, index, 'AND'):
                break
            index += 3
            right, index = self._boolean_parse_not(expr, index)
            left = float(int(left) & int(right))
        self.dprint(f"AND RHS starts at {index}: {expr[index:]!r}")
        return left, index

    def _boolean_parse_or(self, expr: str, index: int) -> Tuple[float, int]:
        left, index = self._boolean_parse_imp(expr, index)
        while True:
            index = self._boolean_skip_ws(expr, index)
            if not self._boolean_keyword_at(expr, index, 'OR'):
                break
            index += 3
            if left != 0:
                # short-circuit: skip right without evaluating
                index = self._boolean_skip_ws(expr, index)
                while self._boolean_keyword_at(expr, index, 'NOT'):
                    index += 3
                    index = self._boolean_skip_ws(expr, index)
                index = self._boolean_find_arith_end(expr, index)
                continue
            right, index = self._boolean_parse_imp(expr, index)
            left = left if left != 0 else right
        return left, index

    def _boolean_parse_imp(self, expr: str, index: int) -> Tuple[float, int]:
        left, index = self._boolean_parse_eqv(expr, index)
        while True:
            index = self._boolean_skip_ws(expr, index)
            if not self._boolean_keyword_at(expr, index, 'IMP'):
                break
            index += 3
            right, index = self._boolean_parse_eqv(expr, index)
            left = self._bbc_bitwise_imp(left, right)
        return left, index

    def _boolean_parse_eqv(self, expr: str, index: int) -> Tuple[float, int]:
        left, index = self._boolean_parse_xor(expr, index)
        while True:
            index = self._boolean_skip_ws(expr, index)
            if not self._boolean_keyword_at(expr, index, 'EQV'):
                break
            index += 3
            right, index = self._boolean_parse_xor(expr, index)
            left = self._bbc_bitwise_eqv(left, right)
        return left, index

    def _boolean_parse_xor(self, expr: str, index: int) -> Tuple[float, int]:
        left, index = self._boolean_parse_and(expr, index)
        while True:
            index = self._boolean_skip_ws(expr, index)
            xor_len: Optional[int] = None
            for word in ('XOR', 'EOR'):
                if self._boolean_keyword_at(expr, index, word):
                    xor_len = len(word)
                    break
            if xor_len is None:
                break
            index += xor_len
            right, index = self._boolean_parse_and(expr, index)
            left = self._bbc_bitwise_xor(left, right)
        return left, index

    def _boolean_parse_or_simple(self, expr: str, index: int) -> Tuple[float, int]:
        """OR/AND/NOT chain without XOR/EQV/IMP (hot path for comparisons)."""
        left, index = self._boolean_parse_and(expr, index)
        while True:
            index = self._boolean_skip_ws(expr, index)
            if not self._boolean_keyword_at(expr, index, 'OR'):
                break
            index += 3
            right, index = self._boolean_parse_and(expr, index)
            left = float(int(left) | int(right))
        return left, index

    def _normalize_condition(self, expr: str) -> str:
        expr = self._RE_COND_NE.sub('!=', expr)
        expr = self._RE_COND_EQ.sub(' == ', expr)
        # Keep AND/OR/NOT uppercase — the BBC boolean parser requires it
        expr = re.sub(r'\b(and)\b', ' AND ', expr, flags=re.IGNORECASE)
        expr = re.sub(r'\b(or)\b',  ' OR ',  expr, flags=re.IGNORECASE)
        expr = re.sub(r'\b(not)\b', ' NOT ', expr, flags=re.IGNORECASE)
        return expr

    def _parse_print_using_clause(self, rest: str) -> Optional[Tuple[str, List[str]]]:
        match = re.match(r'^USING\s+(.+)$', rest.strip(), re.IGNORECASE)
        if not match:
            return None
        format_part, values_part = self._split_at_first_semicolon(match.group(1).strip())
        if not format_part:
            return None
        return format_part, self._split_semicolon_exprs(values_part)

    def _parse_open_statement(self, line: str) -> Optional[Tuple[str, int, str, Optional[int]]]:
        match = re.match(
            r'^OPEN\s+"([^"]+)"\s*,\s*#?\s*(\d+)\s*,\s*(.+)$',
            line.strip(),
            re.IGNORECASE,
        )
        if match is None:
            return None
        mode = match.group(1).upper()
        file_num = int(match.group(2))
        tail = match.group(3).strip()
        record_length: Optional[int] = None
        filename_expr = tail
        depth = 0
        in_string = False
        split_at = -1
        for index, ch in enumerate(tail):
            if ch == '"':
                in_string = not in_string
            elif ch == '(' and not in_string:
                depth += 1
            elif ch == ')' and not in_string:
                depth -= 1
            elif ch == ',' and not in_string and depth == 0:
                split_at = index
                break
        if split_at >= 0:
            filename_expr = tail[:split_at].strip()
            record_length = int(self._eval_numeric(tail[split_at + 1:].strip()))
        if filename_expr.startswith('"') and filename_expr.endswith('"'):
            filename = self._decode_string_literal(filename_expr)
        else:
            filename = self._resolve_string_value(filename_expr)
        return mode, file_num, filename, record_length

    def _parse_field_statement(self, line: str) -> Optional[Tuple[int, List[Tuple[int, str]]]]:
        match = re.match(r'^FIELD\s+#?\s*(\d+)\s*,\s*(.+)$', line.strip(), re.IGNORECASE)
        if match is None:
            return None
        file_num = int(match.group(1))
        tail = match.group(2).strip()
        fields: List[Tuple[int, str]] = []
        for part in self._split_args(tail):
            field_match = re.match(
                rf'^(\d+)\s+AS\s+({self._VAR_BASE_PATTERN}\$?)\s*$',
                part.strip(),
                re.IGNORECASE,
            )
            if field_match is None:
                raise ValueError('invalid FIELD syntax')
            width = int(field_match.group(1))
            var_name = field_match.group(2)
            if not var_name.endswith('$'):
                var_name += '$'
            fields.append((width, var_name))
        return file_num, fields

    def _parse_channel_rest(self, rest: str) -> Tuple[Optional[int], str]:
        channel_expr, content = self._split_channel_prefix(rest.strip())
        if not channel_expr or content == '' and ',' not in rest:
            return None, rest.strip()
        channel = self._eval_channel_expr(channel_expr)
        if channel is None:
            return None, rest.strip()
        return channel, content

    def _parse_close_channel(self, rest: str) -> Optional[int]:
        return self._eval_channel_expr(rest)

    def _parse_input_statement(self, rest: str) -> Tuple[str, List[str]]:
        rest = rest.strip()
        if not rest:
            return '', []
        items = self._split_print_items(rest)
        if not items:
            return '', []
        # BBC: INPUT "prompt"var  (no comma/semicolon) — split string literal from lvalue.
        if len(items) == 1:
            glued = self._split_input_prompt_and_vars(items[0][0])
            if glued is not None:
                prompt, vars_ = glued
                return prompt, vars_
        var_start = self._find_input_var_start(items)
        if var_start >= len(items):
            # Retry: first item may be "prompt"var glued as one print item.
            if items:
                glued = self._split_input_prompt_and_vars(items[0][0])
                if glued is not None:
                    prompt, vars_ = glued
                    rest_vars = [item.strip() for item, _ in items[1:] if self._is_input_lvalue(item)]
                    return prompt, vars_ + rest_vars
            return '', []
        if var_start == 0:
            return '', [item.strip() for item, _ in items]
        # Keep separators so string vars in the prompt (PROMPT$; ": ") evaluate.
        prompt = self._join_print_items(items[:var_start]).rstrip(',').rstrip()
        return prompt, [item.strip() for item, _ in items[var_start:]]

    def _split_input_prompt_and_vars(self, text: str) -> Optional[Tuple[str, List[str]]]:
        """Split BBC ``\"prompt\"var`` / ``\"prompt\" var,x`` when print-split kept them glued."""
        text = text.strip()
        if not text or text[0] != '"':
            return None
        i = 1
        while i < len(text):
            if text[i] == '"':
                # doubled quote inside string
                if i + 1 < len(text) and text[i + 1] == '"':
                    i += 2
                    continue
                prompt = text[: i + 1]
                tail = text[i + 1 :].lstrip()
                if not tail:
                    return None
                # optional separators after prompt
                if tail[0] in ',;':
                    tail = tail[1:].lstrip()
                if not tail:
                    return None
                # remaining may be var or var,var2
                var_tokens = self._split_at_depth(tail, ',', skip_empty=True)
                if not var_tokens:
                    return None
                if not all(self._is_input_lvalue(v) for v in var_tokens):
                    return None
                return prompt, [v.strip() for v in var_tokens]
            i += 1
        return None

    def _iter_program_parts(self, line_nums: List[int], start_index: int = 0):
        for line_num in line_nums[start_index:]:
            for part in self._split_colon_statements(self.program[line_num]):
                _, text = self._extract_label_prefix(part)
                if text:
                    yield line_num, text

    def _normalize_loop_label(self, token: str) -> Optional[str]:
        token = token.strip()
        if not token:
            return None
        if not self._RE_VAR_BASE_FULL.fullmatch(token):
            return None
        if self._is_statement_keyword(token):
            return None
        return self._normalize_identifier(token)

    def _parse_break_continue_label(self, rest: str) -> Tuple[Optional[str], bool]:
        token = rest.strip()
        if not token:
            return None, True
        label = self._normalize_loop_label(token)
        return label, label is not None

    def _parse_assignment_statement(self, line: str) -> Tuple[str, str, str]:
        """Return (lvalue, operator, rhs) for =, +=, -=, *=, /= assignments."""

        self.dprint("PARSE ASSIGN:", repr(line))

        text = line.strip()
        if text.upper().startswith("LET"):
            text = text[3:].lstrip()

        match = self._COMPOUND_ASSIGN_RE.fullmatch(text)
        if match:
            return (
                match.group(1).strip(),
                match.group(2),
                match.group(3).strip(),
            )

        if "=" in text:
            var_part, expr = text.split("=", 1)
            rhs = expr.strip()
            self._validate_assignment_rhs(rhs)
            return var_part.strip(), "=", rhs

        raise ValueError("assignment expected")

    def _program_display_lines(
        self,
        mode: str = 'standard',
        include_line_numbers: bool = True,
        start_line: Optional[int] = None,
        end_line: Optional[int] = None,
        case_fold: Optional[_SaveFold] = None,
    ) -> List[str]:
        goto_targets = self._collect_goto_targets()
        loop_depths = self._compute_loop_depths() if mode in ('pretty', 'refs') else {}
        split_statements = mode in ('pretty', 'refs')
        def_header_lines: Set[int] = set()
        if mode == 'refs':
            def_header_lines, _, _ = self._collect_def_layout(sorted(self.program))
        lines: List[str] = []

        for line_num in sorted(self.program):
            if start_line is not None and line_num < start_line:
                continue
            if end_line is not None and line_num > end_line:
                continue
            raw_line = self.program[line_num]
            parts = self._split_colon_statements(raw_line)
            user_indent = self.line_indent.get(line_num, 0)
            show_number = True
            if mode == 'refs':
                show_number = line_num in goto_targets

            display_parts = parts if split_statements else [raw_line]

            for part_index, display_part in enumerate(display_parts):
                if split_statements:
                    if case_fold is not None:
                        formatted = (
                            _format_statement_part_save_case(display_part, case_fold)
                            if display_part.strip()
                            else ''
                        )
                    else:
                        label, body = self._extract_label_prefix(display_part)
                        formatted = self._format_statement_part(body) if body else ''
                        if label:
                            label_text = f'{label.upper()}:'
                            formatted = (
                                f'{label_text} {formatted}'.strip() if formatted else label_text
                            )
                else:
                    formatted = self.format_list_line(display_part)

                structural_indent = loop_depths.get(line_num, 0) * 4 if mode in ('pretty', 'refs') else 0
                if part_index > 0:
                    structural_indent += 4
                if mode in ('pretty', 'refs'):
                    # Always reindent from structure — never keep prior user indent.
                    indent_width = structural_indent
                else:
                    indent_width = user_indent
                stmt_indent = ' ' * indent_width
                # Pretty/refs formatting may still carry spaces from a part; strip
                # so structure indent is the only leading whitespace.
                if mode in ('pretty', 'refs') and formatted:
                    formatted = formatted.lstrip(' \t')
                number = self._format_line_number(
                    line_num,
                    include_line_numbers and show_number and part_index == 0,
                    # Pad for LIST REFS column alignment; omit for SAVE PRETTY (no numbers).
                    align=include_line_numbers and part_index == 0,
                )
                if formatted:
                    if (
                        mode == 'refs'
                        and part_index == 0
                        and line_num in def_header_lines
                        and lines
                        and lines[-1] != ''
                    ):
                        lines.append('')
                    lines.append(f'{number}{stmt_indent}{formatted}')
        return lines

    def _parse_unnumbered_line(self, line: str) -> Optional[Tuple[str, int]]:
        raw = line.rstrip('\n')
        if not raw.strip():
            return None
        match = re.match(r'^([ \t]*)(.+)$', raw)
        if not match:
            return None
        statement = match.group(2).rstrip()
        if not statement:
            return None
        return statement, self._indent_width(match.group(1))

    def _join_backslash_continuations(self, raw_lines) -> List[str]:
        """Join BBCSDL/C-style source lines continued with a trailing backslash.

        filters.txt style::

            lpf() = 0.07, 0.03, \\
            \\ 0.05, 0.06

        Also accepts a single trailing ``\\`` and a next line starting with ``\\``.
        """
        lines = list(raw_lines)
        if not lines:
            return lines
        out: List[str] = []
        i = 0
        while i < len(lines):
            # Preserve newline style of first segment when present.
            raw = lines[i]
            ends_nl = raw.endswith('\n') or raw.endswith('\r\n')
            s = raw.rstrip('\r\n')
            while True:
                stripped = s.rstrip()
                if not stripped.endswith('\\'):
                    break
                # Drop one trailing backslash (and spaces before it).
                s = stripped[:-1].rstrip()
                i += 1
                if i >= len(lines):
                    break
                nxt = lines[i].rstrip('\r\n').lstrip()
                if nxt.startswith('\\'):
                    nxt = nxt[1:].lstrip()
                s = f'{s} {nxt}' if s else nxt
            out.append(s + ('\n' if ends_nl else ''))
            i += 1
        return out

    def _parse_program_file(
        self,
        raw_lines,
    ) -> Optional[Tuple[List[Tuple[int, str, int]], bool]]:
        raw_lines = self._join_backslash_continuations(raw_lines)
        first_numbered_index: Optional[int] = None
        for index, line in enumerate(raw_lines):
            if self._parse_line_number(line):
                first_numbered_index = index
                break

        numbered: List[Tuple[int, str, int]] = []
        preamble: List[Tuple[str, int]] = []
        mixed_errors: List[Tuple[int, str]] = []

        for index, line in enumerate(raw_lines):
            parsed = self._parse_line_number(line)
            if parsed:
                numbered.append(parsed)
                continue
            parsed_unnumbered = self._parse_unnumbered_line(line)
            if not parsed_unnumbered:
                continue
            statement, indent = parsed_unnumbered
            if first_numbered_index is None or index < first_numbered_index:
                preamble.append((statement, indent))
                continue
            if indent > 0:
                try:
                    self._append_indented_continuation(numbered, statement, indent)
                except ValueError:
                    mixed_errors.append((index + 1, statement))
                continue
            mixed_errors.append((index + 1, statement))

        if mixed_errors:
            source_line, statement = mixed_errors[0]
            preview = self._preview_source_line(statement)
            print(
                f'? Mixed numbered and unnumbered lines at source line '
                f'{source_line}: {preview}',
            )
            print(
                '  (numbered programs may have unnumbered lines only before '
                'the first line number, or indented continuations)',
            )
            return None

        if numbered and preamble:
            # Keep comment preamble as separate lines (free numbers before first).
            # Only join *executable* preamble into line 0 (poem-style ON ERROR bootstrap).
            # Joining REM/' into one line 0 made LIST PRETTY smash headers and reformat
            # FG$/RESET$ as expressions (MB_COLOR.BAS).
            return self._merge_preamble_with_numbered(preamble, numbered), True

        if numbered:
            return numbered, True

        if not preamble:
            return [], False

        result: List[Tuple[int, str, int]] = []
        line_num = 10
        for statement, indent in preamble:
            result.append((line_num, statement, indent))
            line_num += 10
        return result, False

    @staticmethod
    def _is_comment_statement(statement: str) -> bool:
        s = statement.lstrip()
        if not s:
            return False
        if s.startswith("'"):
            return True
        return bool(re.match(r'^REM\b', s, re.IGNORECASE))

    def _merge_preamble_with_numbered(
        self,
        preamble: List[Tuple[str, int]],
        numbered: List[Tuple[int, str, int]],
    ) -> List[Tuple[int, str, int]]:
        """Attach leading unnumbered lines to free line numbers; bootstrap code on 0."""
        used = {n for n, _, _ in numbered}
        first = min(used) if used else 10
        free = [n for n in range(1, first) if n not in used]

        comments: List[Tuple[str, int]] = []
        code_parts: List[str] = []
        for stmt, indent in preamble:
            if self._is_comment_statement(stmt):
                comments.append((stmt, indent))
            else:
                code_parts.append(stmt)

        result: List[Tuple[int, str, int]] = []
        free_i = 0

        def _next_line_num() -> int:
            nonlocal free_i
            if free_i < len(free):
                n = free[free_i]
                free_i += 1
                return n
            # Prefer 0 once for overflow comments if still free, else after max used.
            if 0 not in used and all(r[0] != 0 for r in result):
                return 0
            n = max(used | {r[0] for r in result}, default=0) + 1
            while n in used or any(r[0] == n for r in result):
                n += 1
            return n

        for stmt, indent in comments:
            ln = _next_line_num()
            result.append((ln, stmt, indent))
            used.add(ln)

        if code_parts:
            bootstrap = ': '.join(code_parts)
            if 0 not in used:
                result.append((0, bootstrap, 0))
            else:
                ln = _next_line_num()
                result.append((ln, bootstrap, 0))

        result.extend(numbered)
        result.sort(key=lambda item: item[0])
        return result

    def _parse_auto_line(self, default_num: int, text: str) -> Tuple[int, str]:
        raw = text.rstrip('\n')
        numbered = re.match(r'^[ \t]*(\d+)(.*)$', raw)
        if numbered:
            return int(numbered.group(1)), numbered.group(2)
        return default_num, raw

    def edit_program(self):
        """Bare EDIT (no line number).

        mini_basic does not implement BBC BASIC's full-screen program editor.
        EDIT without a line is therefore not a multi-line "EDIT>" mode — that
        duplicated typing numbered lines at the main prompt and was confusing.

        Useful forms:
          EDIT n     prefilled single-line edit (cursor/word keys on Windows)
          AUTO [n]   sequential new lines with automatic numbers
          10 PRINT…  store/replace a line at the normal > prompt
          10         delete line 10 at the > prompt
          LIST       show the program
        """
        print('EDIT needs a line number (BBC full-screen EDIT is not available).')
        print('  EDIT n     edit one line (prefilled; empty Enter deletes)')
        print('  AUTO [n]   enter new lines with automatic numbers')
        print('  10 PRINT…  type numbered lines at the > prompt to store')
        print('  10         bare line number at > deletes that line')
        print('  LIST       show the program')
        print('  HELP PROGRAM   LOAD / SAVE / LIST / AUTO details')
        if self.program:
            print()
            self.list_program()

