"""Poll project status .txt sources and rebuild status.html only when they change.

Agents write CURRENT_TASK.txt / FEATURES_DONE.txt / etc. A scheduled poller
compares fingerprints; only then does it call update_project_status().

Heartbeat (less frequent) only checks that agents still touch those files.
"""
from __future__ import annotations

import hashlib
import json
import os
import time
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

_PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Source-of-truth text files. status.html is *derived* from these.
STATUS_SOURCE_FILES: Tuple[str, ...] = (
    # Agent / human authored — NOT generated by status rebuild itself.
    'CURRENT_TASK.txt',
    'FEATURES_DONE.txt',
    'CORPUS_AUDIT.txt',
    'CORPUS_RUNNABLE.txt',
    'USER_APPROVAL.txt',
    'USER_APPROVAL_AGENT.txt',
    'DEBUG_STEP.txt',
    'COMPARE_REPORT.txt',
    'WORK_LOG.txt',
    'FOLLOW_PROGRESS.txt',
    # Exclude (written during/as side effect of status/resource tools):
    #   status.html, STATUS.txt, PROGRESS.txt,
    #   AGENT_RESOURCE_ALERT.txt, RESOURCE_CHECK.txt
)

# Agent "alive" signals: if none of these change for STALE_AGENT_SECONDS,
# heartbeat adds a dashboard issue.
AGENT_TOUCH_FILES: Tuple[str, ...] = (
    'CURRENT_TASK.txt',
    'FEATURES_DONE.txt',
    'CORPUS_AUDIT.txt',
    'USER_APPROVAL.txt',
    'USER_APPROVAL_AGENT.txt',
    'DEBUG_STEP.txt',
    'WORK_LOG.txt',
)

_STAMP_PATH = _PROJECT_ROOT / '.status_sources_stamp.json'
_HEARTBEAT_META_PATH = _PROJECT_ROOT / '.status_heartbeat_meta.json'

# Default: warn if agent files untouched for 6 hours.
STALE_AGENT_SECONDS = int(os.environ.get('MINI_BASIC_STATUS_STALE_SEC', str(6 * 3600)))

# How often (seconds) the scheduled task should run a full *staleness* check
# even when sources are unchanged. Separate from per-minute polls if you keep
# a frequent poll schedule — see progress_heartbeat.py.
HEARTBEAT_STALE_CHECK_INTERVAL = int(
    os.environ.get('MINI_BASIC_STATUS_HEARTBEAT_SEC', str(30 * 60))
)


def project_root() -> Path:
    return _PROJECT_ROOT


def source_paths(names: Sequence[str] = STATUS_SOURCE_FILES) -> List[Path]:
    return [_PROJECT_ROOT / name for name in names]


def file_fingerprint(path: Path) -> Optional[Dict[str, Any]]:
    """Return mtime_ns + size + short content hash, or None if missing."""
    try:
        st = path.stat()
    except OSError:
        return None
    try:
        data = path.read_bytes()
    except OSError:
        data = b''
    digest = hashlib.sha256(data).hexdigest()[:16]
    return {
        'mtime_ns': st.st_mtime_ns,
        'size': st.st_size,
        'sha16': digest,
    }


def compute_sources_snapshot(
    names: Sequence[str] = STATUS_SOURCE_FILES,
) -> Dict[str, Any]:
    files: Dict[str, Any] = {}
    for name in names:
        path = _PROJECT_ROOT / name
        files[name] = file_fingerprint(path)
    return {
        'generated_at': time.time(),
        'files': files,
    }


def load_stamp() -> Optional[Dict[str, Any]]:
    try:
        return json.loads(_STAMP_PATH.read_text(encoding='utf-8'))
    except (OSError, json.JSONDecodeError, TypeError):
        return None


def save_stamp(snapshot: Dict[str, Any]) -> None:
    _STAMP_PATH.write_text(
        json.dumps(snapshot, indent=2, sort_keys=True) + '\n',
        encoding='utf-8',
        newline='\n',
    )


def _content_key(meta: Optional[Dict[str, Any]]) -> Tuple[Any, ...]:
    """Compare by content only (ignore mtime so OneDrive/touch does not thrash)."""
    if meta is None:
        return (None, None)
    return (meta.get('size'), meta.get('sha16'))


def sources_changed(
    snapshot: Optional[Dict[str, Any]] = None,
    previous: Optional[Dict[str, Any]] = None,
) -> bool:
    """True if tracked source *content* differs from last stamp."""
    if snapshot is None:
        snapshot = compute_sources_snapshot()
    if previous is None:
        previous = load_stamp()
    if previous is None:
        return True
    cur = snapshot.get('files') or {}
    old = previous.get('files') or {}
    names = set(cur) | set(old)
    for name in names:
        if _content_key(cur.get(name)) != _content_key(old.get(name)):
            return True
    return False


def newest_agent_mtime(names: Sequence[str] = AGENT_TOUCH_FILES) -> Optional[float]:
    """Unix mtime of the most recently modified agent-touch file, if any exist."""
    newest: Optional[float] = None
    for name in names:
        path = _PROJECT_ROOT / name
        try:
            m = path.stat().st_mtime
        except OSError:
            continue
        if newest is None or m > newest:
            newest = m
    return newest


def agent_files_stale(
    *,
    now: Optional[float] = None,
    max_age_sec: int = STALE_AGENT_SECONDS,
) -> Tuple[bool, str]:
    """Return (is_stale, human message)."""
    now = time.time() if now is None else now
    newest = newest_agent_mtime()
    if newest is None:
        return True, (
            f'No agent status .txt files found under { _PROJECT_ROOT.name } '
            f'(expected e.g. CURRENT_TASK.txt, FEATURES_DONE.txt)'
        )
    age = now - newest
    if age <= max_age_sec:
        mins = int(age // 60)
        return False, f'Agent status files OK (last touch {mins} min ago)'
    hours = age / 3600.0
    return True, (
        f'Agent status .txt files stale: last touch {hours:.1f}h ago '
        f'(limit {max_age_sec // 3600}h). Agents should update CURRENT_TASK.txt '
        f'/ FEATURES_DONE.txt after work.'
    )


def load_heartbeat_meta() -> Dict[str, Any]:
    try:
        return json.loads(_HEARTBEAT_META_PATH.read_text(encoding='utf-8'))
    except (OSError, json.JSONDecodeError, TypeError):
        return {}


def save_heartbeat_meta(meta: Dict[str, Any]) -> None:
    _HEARTBEAT_META_PATH.write_text(
        json.dumps(meta, indent=2, sort_keys=True) + '\n',
        encoding='utf-8',
        newline='\n',
    )


def should_run_stale_check(
    *,
    now: Optional[float] = None,
    interval_sec: int = HEARTBEAT_STALE_CHECK_INTERVAL,
) -> bool:
    now = time.time() if now is None else now
    meta = load_heartbeat_meta()
    last = float(meta.get('last_stale_check', 0) or 0)
    return (now - last) >= interval_sec


def mark_stale_check_done(*, now: Optional[float] = None) -> None:
    now = time.time() if now is None else now
    meta = load_heartbeat_meta()
    meta['last_stale_check'] = now
    meta['last_stale_message'] = agent_files_stale(now=now)[1]
    save_heartbeat_meta(meta)


def maybe_update_status_from_sources(
    *,
    force: bool = False,
    extra_issues: Optional[List[str]] = None,
) -> Dict[str, Any]:
    """Rebuild status.html only if source .txt fingerprints changed (or force).

    Returns a result dict: changed, updated, stale_issue, message.
    """
    snapshot = compute_sources_snapshot()
    changed = force or sources_changed(snapshot)
    result: Dict[str, Any] = {
        'changed': changed,
        'updated': False,
        'stale_issue': None,
        'message': '',
    }
    if not changed:
        result['message'] = 'status sources unchanged; status.html left as-is'
        return result

    # Import here so heartbeat can set SDL dummy before mini_basic imports.
    from test.progress_runner import update_project_status

    issues = list(extra_issues or [])
    # Always surface current staleness when rebuilding.
    is_stale, stale_msg = agent_files_stale()
    if is_stale:
        issues.append(stale_msg)
        result['stale_issue'] = stale_msg

    if issues:
        update_project_status(heartbeat=False, issues=issues)
    else:
        # Do not pass issues=… so progress_runner auto-fills from logs/audit.
        update_project_status(heartbeat=False)
    save_stamp(snapshot)
    result['updated'] = True
    result['message'] = 'status.html rebuilt from changed source .txt files'
    return result


def heartbeat_poll(
    *,
    force_update: bool = False,
    force_stale_check: bool = False,
) -> Dict[str, Any]:
    """Scheduled one-shot entry: update on source change; rare agent-staleness check.

    - Always compare source fingerprints.
    - Rebuild status.html only when sources changed (or force_update).
    - Every HEARTBEAT_STALE_CHECK_INTERVAL (default 30 min), if sources did
      *not* change, still check agent file age and rebuild only if stale so
      the dashboard shows a warning.
    """
    now = time.time()
    snapshot = compute_sources_snapshot()
    changed = force_update or sources_changed(snapshot)
    run_stale = force_stale_check or should_run_stale_check(now=now)

    result: Dict[str, Any] = {
        'sources_changed': changed,
        'stale_check': False,
        'updated': False,
        'message': '',
    }

    if changed:
        r = maybe_update_status_from_sources(force=True)
        result['updated'] = r['updated']
        result['message'] = r['message']
        result['stale_issue'] = r.get('stale_issue')
        if run_stale:
            mark_stale_check_done(now=now)
            result['stale_check'] = True
        return result

    # No source change: optional infrequent staleness probe.
    if not run_stale:
        result['message'] = (
            'no source change; skipping rebuild '
            f'(next agent-staleness check in up to '
            f'{HEARTBEAT_STALE_CHECK_INTERVAL // 60} min)'
        )
        return result

    result['stale_check'] = True
    is_stale, stale_msg = agent_files_stale(now=now)
    mark_stale_check_done(now=now)
    if not is_stale:
        result['message'] = f'no source change; {stale_msg}'
        return result

    # Stale agents with no file edits: force a rebuild so the warning appears.
    from test.progress_runner import update_project_status

    update_project_status(heartbeat=False, issues=[stale_msg])
    # Do not advance source stamp — sources did not change; stamp stays so a
    # real agent edit still triggers a normal rebuild.
    result['updated'] = True
    result['stale_issue'] = stale_msg
    result['message'] = f'status.html rebuilt to flag stale agents: {stale_msg}'
    return result
