"""Regenerate CHANGELOG.md from merged GitHub pull requests.

Run from the repo root:

    python scripts/update_changelog.py

Requires a GitHub token in GH_TOKEN or GITHUB_TOKEN (the GitHub Actions
workflow sets this automatically). Uses the REST API directly (not the
GraphQL-backed `gh pr list`/`gh pr view`) so it also works unattended.
"""
from __future__ import annotations

import json
import os
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CHANGELOG = ROOT / 'CHANGELOG.md'
REPO = 'pyTony/mini_basic'
API = f'https://api.github.com/repos/{REPO}/pulls'

HEADER = (
    "# Changelog (dev branch — full history)\n\n"
    "Format: one line per merged PR, newest first, auto-generated from PR "
    "descriptions by `scripts/update_changelog.py` "
    "(`.github/workflows/update-changelog.yml` refreshes this branch on "
    "every PR merged to `main`). `main`'s own `CHANGELOG.md` tracks tagged "
    "releases only. See [GitHub Issues](https://github.com/pyTony/mini_basic/issues) "
    "for open work.\n"
)


def _token() -> str | None:
    return os.environ.get('GH_TOKEN') or os.environ.get('GITHUB_TOKEN')


def fetch_merged_prs() -> list[dict]:
    headers = {
        'Accept': 'application/vnd.github+json',
        'User-Agent': 'mini_basic-changelog-script',
    }
    token = _token()
    if token:
        headers['Authorization'] = f'Bearer {token}'

    prs: list[dict] = []
    page = 1
    while True:
        url = f'{API}?state=closed&base=main&per_page=100&page={page}'
        req = urllib.request.Request(url, headers=headers)
        with urllib.request.urlopen(req) as resp:
            batch = json.load(resp)
        if not batch:
            break
        prs.extend(pr for pr in batch if pr.get('merged_at'))
        if len(batch) < 100:
            break
        page += 1
    return prs


def strip_boilerplate(body: str) -> str:
    body = body or ''
    body = re.sub(r'<!--.*?-->', '', body, flags=re.DOTALL)
    body = re.sub(r'_Requested by.*?\n', '', body)
    # Drop everything from the attribution/session footer onward.
    body = re.split(r'\n---\n_Generated by', body)[0]
    body = re.split(r'\n🤖 Generated with', body)[0]
    return body.strip()


def extract_summary(body: str) -> str:
    """Pull one explanatory line out of a PR body's own explanation."""
    text = strip_boilerplate(body)
    if not text:
        return ''

    # Prefer an explicit Before:/After: pair (the house style for this repo).
    before = re.search(r'\bBefore:\*{0,2}\s*(.+)', text)
    after = re.search(r'\bAfter:\*{0,2}\s*(.+)', text)
    if after:
        summary = after.group(1).strip()
        if before:
            summary = f'{summary}'
        return _clean(summary)

    # Otherwise take the first real paragraph, skipping headings/attribution.
    for para in re.split(r'\n\s*\n', text):
        para = para.strip()
        if not para or para.startswith('#') or para.startswith('_'):
            continue
        return _clean(para)
    return ''


def _clean(text: str) -> str:
    text = ' '.join(text.split())
    text = re.sub(r'\*\*(.+?)\*\*', r'\1', text)
    if len(text) > 320:
        text = text[:317].rsplit(' ', 1)[0] + '…'
    return text


def build_changelog(prs: list[dict]) -> str:
    prs = sorted(prs, key=lambda pr: pr['merged_at'], reverse=True)
    lines = [HEADER]
    current_date = None
    for pr in prs:
        date = pr['merged_at'][:10]
        if date != current_date:
            lines.append(f'\n## {date}\n')
            current_date = date
        summary = extract_summary(pr.get('body') or '')
        title = pr['title']
        entry = f"- [#{pr['number']}]({pr['html_url']}) {title}"
        if summary and summary.lower() not in title.lower():
            entry += f' — {summary}'
        lines.append(entry)
    lines.append('')
    return '\n'.join(lines)


def main() -> None:
    prs = fetch_merged_prs()
    CHANGELOG.write_text(build_changelog(prs), encoding='utf-8')
    print(f'Wrote {CHANGELOG.relative_to(ROOT)} from {len(prs)} merged PRs')


if __name__ == '__main__':
    main()
